// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::error {
    #[error]
    const EAlreadyRegistered: vector<u8> = b"Player already registered";
    public fun already_registered(condition: bool) { assert!(condition, EAlreadyRegistered) }

    #[error]
    const ENotRegistered: vector<u8> = b"Player not registered";
    public fun not_registered(condition: bool) { assert!(condition, ENotRegistered) }

    #[error]
    const EInsufficientGold: vector<u8> = b"Not enough gold";
    public fun insufficient_gold(condition: bool) { assert!(condition, EInsufficientGold) }

    #[error]
    const ECardNotFound: vector<u8> = b"Card not owned";
    public fun card_not_found(condition: bool) { assert!(condition, ECardNotFound) }

    #[error]
    const EInvalidCardKind: vector<u8> = b"Invalid card kind";
    public fun invalid_card_kind(condition: bool) { assert!(condition, EInvalidCardKind) }

    #[error]
    const EDeckWrongSize: vector<u8> = b"Battle deck must contain exactly 5 cards";
    public fun deck_wrong_size(condition: bool) { assert!(condition, EDeckWrongSize) }

    #[error]
    const EDeckDuplicateCard: vector<u8> = b"Battle deck contains duplicate cards";
    public fun deck_duplicate_card(condition: bool) { assert!(condition, EDeckDuplicateCard) }

    #[error]
    const ECardNotInDeck: vector<u8> = b"Card is not in your battle deck";
    public fun card_not_in_deck(condition: bool) { assert!(condition, ECardNotInDeck) }

    #[error]
    const ECardAlreadyUsed: vector<u8> = b"Card already used in this match";
    public fun card_already_used(condition: bool) { assert!(condition, ECardAlreadyUsed) }

    #[error]
    const EAlreadyInMatch: vector<u8> = b"Already in an active match";
    public fun already_in_match(condition: bool) { assert!(condition, EAlreadyInMatch) }

    #[error]
    const ENotInMatch: vector<u8> = b"Not in an active match";
    public fun not_in_match(condition: bool) { assert!(condition, ENotInMatch) }

    #[error]
    const EWrongMatch: vector<u8> = b"Storage does not belong to this match";
    public fun wrong_match(condition: bool) { assert!(condition, EWrongMatch) }

    #[error]
    const EMatchNotWaiting: vector<u8> = b"Match is not waiting for an opponent";
    public fun match_not_waiting(condition: bool) { assert!(condition, EMatchNotWaiting) }

    #[error]
    const EMatchNotActive: vector<u8> = b"Match is not active";
    public fun match_not_active(condition: bool) { assert!(condition, EMatchNotActive) }

    #[error]
    const EMatchNotFinished: vector<u8> = b"Match is not finished";
    public fun match_not_finished(condition: bool) { assert!(condition, EMatchNotFinished) }

    #[error]
    const ENotMatchWinner: vector<u8> = b"Caller is not the winner of this match";
    public fun not_match_winner(condition: bool) { assert!(condition, ENotMatchWinner) }

    #[error]
    const ENotYourTurn: vector<u8> = b"Not your turn";
    public fun not_your_turn(condition: bool) { assert!(condition, ENotYourTurn) }

    #[error]
    const ENotInvited: vector<u8> = b"Caller is not the invited opponent";
    public fun not_invited(condition: bool) { assert!(condition, ENotInvited) }

    #[error]
    const ENotChallenger: vector<u8> = b"Only the challenger can do this";
    public fun not_challenger(condition: bool) { assert!(condition, ENotChallenger) }

    #[error]
    const ECannotPlaySelf: vector<u8> = b"Cannot start a match against yourself";
    public fun cannot_play_self(condition: bool) { assert!(condition, ECannotPlaySelf) }

    #[error]
    const EInvalidStake: vector<u8> = b"Stake must be greater than zero";
    public fun invalid_stake(condition: bool) { assert!(condition, EInvalidStake) }

    #[error]
    const ETurnNotTimedOut: vector<u8> = b"Current turn has not timed out yet";
    public fun turn_not_timed_out(condition: bool) { assert!(condition, ETurnNotTimedOut) }

    #[error]
    const ETargetNotAlive: vector<u8> = b"Target is not alive in this brawl";
    public fun target_not_alive(condition: bool) { assert!(condition, ETargetNotAlive) }

    #[error]
    const EBrawlNotHost: vector<u8> = b"Only the room host can do this";
    public fun brawl_not_host(condition: bool) { assert!(condition, EBrawlNotHost) }

    #[error]
    const EBrawlFull: vector<u8> = b"Brawl room is full";
    public fun brawl_full(condition: bool) { assert!(condition, EBrawlFull) }

    #[error]
    const EBrawlTooFewPlayers: vector<u8> = b"Need at least 2 players to start";
    public fun brawl_too_few_players(condition: bool) { assert!(condition, EBrawlTooFewPlayers) }

    #[error]
    const EBrawlInvalidMaxPlayers: vector<u8> = b"Max players must be between 2 and 8";
    public fun brawl_invalid_max_players(condition: bool) { assert!(condition, EBrawlInvalidMaxPlayers) }

    #[error]
    const EAlreadyJoined: vector<u8> = b"Already joined this brawl";
    public fun already_joined(condition: bool) { assert!(condition, EAlreadyJoined) }

    #[error]
    const ENotInBrawl: vector<u8> = b"Caller has not joined this brawl";
    public fun not_in_brawl(condition: bool) { assert!(condition, ENotInBrawl) }

    #[error]
    const EHostCannotLeave: vector<u8> = b"The host must cancel the room instead of leaving";
    public fun host_cannot_leave(condition: bool) { assert!(condition, EHostCannotLeave) }
}
