// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module dubhe::error {
    #[error]
    const EAssetNotFound: vector<u8> = b"Asset not found";
    public fun asset_not_found(condition: bool) { assert!(condition, EAssetNotFound) }

    #[error]
    const EAssetAlreadyFrozen: vector<u8> = b"Asset already frozen";
    public fun asset_already_frozen(condition: bool) { assert!(condition, EAssetAlreadyFrozen) }

    #[error]
    const EInvalidSender: vector<u8> = b"Invalid sender";
    public fun invalid_sender(condition: bool) { assert!(condition, EInvalidSender) }

    #[error]
    const EInvalidReceiver: vector<u8> = b"Invalid receiver";
    public fun invalid_receiver(condition: bool) { assert!(condition, EInvalidReceiver) }

    #[error]
    const EInvalidMetadata: vector<u8> = b"Invalid metadata";
    public fun invalid_metadata(condition: bool) { assert!(condition, EInvalidMetadata) }

    #[error]
    const EAccountNotFound: vector<u8> = b"Account not found";
    public fun account_not_found(condition: bool) { assert!(condition, EAccountNotFound) }

    #[error]
    const EAccountBlocked: vector<u8> = b"Account is blocked";
    public fun account_blocked(condition: bool) { assert!(condition, EAccountBlocked) }

    #[error]
    const EAccountFrozen: vector<u8> = b"Account is frozen";
    public fun account_frozen(condition: bool) { assert!(condition, EAccountFrozen) }

    #[error]
    const EBalanceTooLow: vector<u8> = b"Balance too low";
    public fun balance_too_low(condition: bool) { assert!(condition, EBalanceTooLow) }

    #[error]
    const EOverflows: vector<u8> = b"Operation overflows";
    public fun overflows(condition: bool) { assert!(condition, EOverflows) }

    #[error]
    const ENoPermission: vector<u8> = b"No permission";
    public fun no_permission(condition: bool) { assert!(condition, ENoPermission) }

    #[error]
    const ENotMintable: vector<u8> = b"Asset is not mintable";
    public fun not_mintable(condition: bool) { assert!(condition, ENotMintable) }

    #[error]
    const ENotBurnable: vector<u8> = b"Asset is not burnable";
    public fun not_burnable(condition: bool) { assert!(condition, ENotBurnable) }

    #[error]
    const ENotFreezable: vector<u8> = b"Asset is not freezable";
    public fun not_freezable(condition: bool) { assert!(condition, ENotFreezable) }

    #[error]
    const EBelowMinAmount: vector<u8> = b"Amount is below minimum";
    public fun below_min_amount(condition: bool) { assert!(condition, EBelowMinAmount) }

    #[error]
    const ELiquidityCannotBeZero: vector<u8> = b"Liquidity cannot be 0";
    public fun liquidity_cannot_be_zero(condition: bool) { assert!(condition, ELiquidityCannotBeZero) }

    #[error]
    const EMoreThanMaxSwapPathLen: vector<u8> = b"More than Max";
    public fun more_than_max_swap_path_len(condition: bool) { assert!(condition, EMoreThanMaxSwapPathLen) }

    #[error]
    const EMoreThanReserve: vector<u8> = b"More than reserve";
    public fun more_than_reserve(condition: bool) { assert!(condition, EMoreThanReserve) }

    #[error]
    const ESwapPathTooSmall: vector<u8> = b"Swap path too small";
    public fun swap_path_too_small(condition: bool) { assert!(condition, ESwapPathTooSmall) }

    #[error]
    const EReservesCannotBeZero: vector<u8> = b"Reserve cannot be 0";
    public fun reserves_cannot_be_zero(condition: bool) { assert!(condition, EReservesCannotBeZero) }

    #[error]
    const EAmountCannotBeZero: vector<u8> = b"Amount cannot be 0";
    public fun amount_cannot_be_zero(condition: bool) { assert!(condition, EAmountCannotBeZero) }

    #[error]
    const ELessThanAmountOutMin: vector<u8> = b"Less than expected";
    public fun less_than_amount_out_min(condition: bool) { assert!(condition, ELessThanAmountOutMin) }

    #[error]
    const EMoreThanAmountInMax: vector<u8> = b"More than expected";
    public fun more_than_amount_in_max(condition: bool) { assert!(condition, EMoreThanAmountInMax) }

    #[error]
    const EBridgeNotOpened: vector<u8> = b"Bridge is not opened";
    public fun bridge_not_opened(condition: bool) { assert!(condition, EBridgeNotOpened) }

    #[error]
    const ENotLatestVersion: vector<u8> = b"Not latest version";
    public fun not_latest_version(condition: bool) { assert!(condition, ENotLatestVersion) }

    #[error]
    const EDappPaused: vector<u8> = b"Dapp is paused";
    public fun dapp_paused(condition: bool) { assert!(condition, EDappPaused) }

    #[error]
    const EInvalidPackageId: vector<u8> = b"Invalid package id";
    public fun invalid_package_id(condition: bool) { assert!(condition, EInvalidPackageId) }

    #[error]
    const EInvalidVersion: vector<u8> = b"Invalid version";
    public fun invalid_version(condition: bool) { assert!(condition, EInvalidVersion) }

    #[error]
    const EDappNotInitialized: vector<u8> = b"Dapp not initialized";
    public fun dapp_not_initialized(condition: bool) { assert!(condition, EDappNotInitialized) }

    #[error]
    const EDappAlreadyInitialized: vector<u8> = b"Dapp already initialized";
    public fun dapp_already_initialized(condition: bool) { assert!(condition, EDappAlreadyInitialized) }

    #[error]
    const EInsufficientCredit: vector<u8> = b"Insufficient credit";
    public fun insufficient_credit(condition: bool) { assert!(condition, EInsufficientCredit) }

    #[error]
    const EDappNotBeenDelegated: vector<u8> = b"Dapp not been delegated";
    public fun dapp_not_been_delegated(condition: bool) { assert!(condition, EDappNotBeenDelegated) }

    #[error]
    const EDappAlreadyDelegated: vector<u8> = b"Dapp already delegated";
    public fun dapp_already_delegated(condition: bool) { assert!(condition, EDappAlreadyDelegated) }

    #[error]
    const ENoPendingOwnershipTransfer: vector<u8> = b"No pending ownership transfer";
    public fun no_pending_ownership_transfer(condition: bool) { assert!(condition, ENoPendingOwnershipTransfer) }

    #[error]
    const EUserDebtLimitExceeded: vector<u8> = b"User debt limit exceeded";
    public fun user_debt_limit_exceeded(condition: bool) { assert!(condition, EUserDebtLimitExceeded) }

    #[error]
    const EDappSuspended: vector<u8> = b"Dapp is suspended";
    public fun dapp_suspended(condition: bool) { assert!(condition, EDappSuspended) }

    #[error]
    const EDappKeyMismatch: vector<u8> = b"Dapp key mismatch";
    public fun dapp_key_mismatch(condition: bool) { assert!(condition, EDappKeyMismatch) }

    #[error]
    const ENoActiveSession: vector<u8> = b"No active session";
    public fun no_active_session(condition: bool) { assert!(condition, ENoActiveSession) }

    #[error]
    const ENotCanonicalOwner: vector<u8> = b"Not canonical owner";
    public fun not_canonical_owner(condition: bool) { assert!(condition, ENotCanonicalOwner) }

    #[error]
    const EInsufficientCreditToUnsuspend: vector<u8> = b"Insufficient credit to unsuspend";
    public fun insufficient_credit_to_unsuspend(condition: bool) { assert!(condition, EInsufficientCreditToUnsuspend) }

    #[error]
    const EUserStorageAlreadyExists: vector<u8> = b"User storage already exists";
    public fun user_storage_already_exists(condition: bool) { assert!(condition, EUserStorageAlreadyExists) }

    #[error]
    const EInvalidSessionKey: vector<u8> = b"Invalid session key";
    public fun invalid_session_key(condition: bool) { assert!(condition, EInvalidSessionKey) }

    #[error]
    const EInvalidSessionDuration: vector<u8> = b"Invalid session duration";
    public fun invalid_session_duration(condition: bool) { assert!(condition, EInvalidSessionDuration) }

    #[error]
    const EWrongPaymentCoinType: vector<u8> = b"Wrong payment coin type";
    public fun wrong_payment_coin_type(condition: bool) { assert!(condition, EWrongPaymentCoinType) }

    #[error]
    const ENoPendingCoinTypeChange: vector<u8> = b"No pending coin type change";
    public fun no_pending_coin_type_change(condition: bool) { assert!(condition, ENoPendingCoinTypeChange) }

    #[error]
    const ECoinTypeChangeNotReady: vector<u8> = b"Coin type change not ready";
    public fun coin_type_change_not_ready(condition: bool) { assert!(condition, ECoinTypeChangeNotReady) }

    #[error]
    const EWrongSettlementMode: vector<u8> = b"Wrong settlement mode";
    public fun wrong_settlement_mode(condition: bool) { assert!(condition, EWrongSettlementMode) }

    #[error]
    const ERevenueShareExceedsMax: vector<u8> = b"Revenue share exceeds max";
    public fun revenue_share_exceeds_max(condition: bool) { assert!(condition, ERevenueShareExceedsMax) }

    #[error]
    const ENoRevenueToWithdraw: vector<u8> = b"No revenue to withdraw";
    public fun no_revenue_to_withdraw(condition: bool) { assert!(condition, ENoRevenueToWithdraw) }

    #[error]
    const EWriteLimitOutOfRange: vector<u8> = b"Write limit out of range";
    public fun write_limit_out_of_range(condition: bool) { assert!(condition, EWriteLimitOutOfRange) }

    #[error]
    const ESceneExpired: vector<u8> = b"Scene has expired";
    public fun scene_expired(condition: bool) { assert!(condition, ESceneExpired) }

    #[error]
    const ENotSceneParticipant: vector<u8> = b"Not a scene participant";
    public fun not_scene_participant(condition: bool) { assert!(condition, ENotSceneParticipant) }

    #[error]
    const EEntityNotFound: vector<u8> = b"Entity not found";
    public fun entity_not_found(condition: bool) { assert!(condition, EEntityNotFound) }

    #[error]
    const EEntityIdAlreadyExists: vector<u8> = b"Entity id already exists";
    public fun entity_id_already_exists(condition: bool) { assert!(condition, EEntityIdAlreadyExists) }

    #[error]
    const EInsufficientBalance: vector<u8> = b"Insufficient balance";
    public fun insufficient_balance(condition: bool) { assert!(condition, EInsufficientBalance) }

    #[error]
    const EMarketplaceFeeExceedsMax: vector<u8> = b"Marketplace fee bps cannot exceed 10000";
    public fun marketplace_fee_exceeds_max(condition: bool) { assert!(condition, EMarketplaceFeeExceedsMax) }

    #[error]
    const ENotParticipant: vector<u8> = b"Sender is not a participant or invitee";
    public fun not_participant(condition: bool) { assert!(condition, ENotParticipant) }

    #[error]
    const ESceneFull: vector<u8> = b"Scene has reached its maximum participant limit";
    public fun scene_full(condition: bool) { assert!(condition, ESceneFull) }

    #[error]
    const EInvitationExpired: vector<u8> = b"Invitation window has expired";
    public fun invitation_expired(condition: bool) { assert!(condition, EInvitationExpired) }

    #[error]
    const EListingNotFound: vector<u8> = b"Listing not found";
    public fun listing_not_found(condition: bool) { assert!(condition, EListingNotFound) }

    #[error]
    const EListingTypeMismatch: vector<u8> = b"Listing type mismatch";
    public fun listing_type_mismatch(condition: bool) { assert!(condition, EListingTypeMismatch) }

    #[error]
    const EOnlySellerCanCancel: vector<u8> = b"Only the original seller can cancel";
    public fun only_seller_can_cancel(condition: bool) { assert!(condition, EOnlySellerCanCancel) }

    #[error]
    const EInvalidKey: vector<u8> = b"Invalid key";
    public fun invalid_key(condition: bool) { assert!(condition, EInvalidKey) }

    #[error]
    const EInvalidSolanaAddress: vector<u8> = b"Invalid Solana address";
    public fun invalid_solana_address(condition: bool) { assert!(condition, EInvalidSolanaAddress) }

    #[error]
    const EInvalidEvmAddress: vector<u8> = b"Invalid EVM address";
    public fun invalid_evm_address(condition: bool) { assert!(condition, EInvalidEvmAddress) }

    #[error]
    const ELengthMismatch: vector<u8> = b"Length mismatch";
    public fun length_mismatch(condition: bool) { assert!(condition, ELengthMismatch) }

    #[error]
    const EMathOverflow: vector<u8> = b"Math overflow";
    public fun math_overflow(condition: bool) { assert!(condition, EMathOverflow) }

    #[error]
    const EDivisionByZero: vector<u8> = b"Division by zero";
    public fun division_by_zero(condition: bool) { assert!(condition, EDivisionByZero) }

    #[error]
    const EInvalidWindowSize: vector<u8> = b"Invalid window size";
    public fun invalid_window_size(condition: bool) { assert!(condition, EInvalidWindowSize) }

    #[error]
    const EParticipantsStillPresent: vector<u8> = b"Cannot destroy scene while participants are still present";
    public fun participants_still_present(condition: bool) { assert!(condition, EParticipantsStillPresent) }
}
