// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module guild::guild {
    use sui::bag::{Self, Bag};
    use dubhe::dapp_service::{DappStorage, UserStorage};
    use dubhe::dapp_system;
    use guild::dapp_key;
    use guild::dapp_key::DappKey;
    use std::ascii::{string, String};
    use guild::dungeon_run::{Self, DungeonRunStorage};

    // ─── Error constants ───────────────────────────────────────────────────
    const EFieldNotFound: u64 = 1;
    const EInsufficientAmount: u64 = 2;
    const EDuplicateItemId: u64 = 3;
    const EWrongEntityId: u64 = 4;
    const ENoPermission: u64 = 5;

    const TYPE_TAG: vector<u8> = b"guild";

    // ─── Struct definition ─────────────────────────────────────────────────
    /// Typed shared object for DApp-managed entity: guild.
    /// entity_id is unique within this type across the DApp.
    public struct GuildStorage has key {
        id:        sui::object::UID,
        entity_id: vector<u8>,
        data:      Bag,
    }

    // ─── ID accessor ───────────────────────────────────────────────────────
    public fun entity_id(storage: &GuildStorage): vector<u8> { storage.entity_id }


    public fun assert_guild_id(storage: &GuildStorage, expected: vector<u8>) {
        assert!(storage.entity_id == expected, EWrongEntityId);
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_level(storage: &GuildStorage): u32 {
        assert!(sui::bag::contains(&storage.data, b"level"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, u32>(&storage.data, b"level")
    }

    public(package) fun set_level(storage: &mut GuildStorage, value: u32) {
        if (sui::bag::contains(&storage.data, b"level")) {
            *sui::bag::borrow_mut<vector<u8>, u32>(&mut storage.data, b"level") = value;
        } else {
            sui::bag::add(&mut storage.data, b"level", value);
        }
    }

    public fun get_name(storage: &GuildStorage): String {
        assert!(sui::bag::contains(&storage.data, b"name"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, String>(&storage.data, b"name")
    }

    public(package) fun set_name(storage: &mut GuildStorage, value: String) {
        if (sui::bag::contains(&storage.data, b"name")) {
            *sui::bag::borrow_mut<vector<u8>, String>(&mut storage.data, b"name") = value;
        } else {
            sui::bag::add(&mut storage.data, b"name", value);
        }
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &GuildStorage): u64 {
        if (sui::bag::contains(&storage.data, b"gold")) {
            *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut GuildStorage, amount: u64) {
        if (sui::bag::contains(&storage.data, b"gold")) {
            let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
            *current = *current + amount;
        } else {
            sui::bag::add(&mut storage.data, b"gold", amount);
        }
    }

    public(package) fun sub_gold(storage: &mut GuildStorage, amount: u64) {
        assert!(sui::bag::contains(&storage.data, b"gold"), EInsufficientAmount);
        let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
        assert!(*current >= amount, EInsufficientAmount);
        *current = *current - amount;
    }

    public fun has_weapon(storage: &GuildStorage, item_id: u64): bool {
        let key = sui::bcs::to_bytes(&item_id);
        sui::bag::contains_with_type<vector<u8>, vector<u8>>(&storage.data, key)
    }

    public fun get_weapon_data(storage: &GuildStorage, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(sui::bag::contains(&storage.data, key), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, vector<u8>>(&storage.data, key)
    }

    public(package) fun set_weapon_data(storage: &mut GuildStorage, item_id: u64, data: vector<u8>) {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(!sui::bag::contains(&storage.data, key), EDuplicateItemId);
        sui::bag::add(&mut storage.data, key, data);
    }

    public(package) fun remove_weapon_data(storage: &mut GuildStorage, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(sui::bag::contains(&storage.data, key), EFieldNotFound);
        sui::bag::remove(&mut storage.data, key)
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer gold (fungible) from dungeon_run into this guild.
    public(package) fun transfer_dungeon_run_to_guild_gold(
        from:   &mut DungeonRunStorage,
        to:     &mut GuildStorage,
        amount: u64,
    ) {
        dungeon_run::sub_gold(from, amount);
        add_gold(to, amount);
    }

    // ─── Lifecycle entry functions ─────────────────────────────────────────
    public entry fun create_guild(
        dapp_storage: &mut DappStorage,
        entity_id:    vector<u8>,
        ctx:          &mut TxContext,
    ) {

        let id = sui::object::new(ctx);
        let object_id = sui::object::uid_to_address(&id);
        dapp_system::register_object_entity<DappKey>(
            dapp_key::new(), dapp_storage, TYPE_TAG, entity_id, object_id
        );
        let storage = GuildStorage {
            id,
            entity_id,
            data:      bag::new(ctx),
        };
        sui::transfer::share_object(storage);
    }

    public entry fun destroy_guild(
        dapp_storage: &mut DappStorage,
        storage:      GuildStorage,
        _ctx:         &mut TxContext,
    ) {
        let GuildStorage { id, entity_id, data } = storage;
        bag::destroy_empty(data);
        dapp_system::unregister_object_entity<DappKey>(
            dapp_key::new(), dapp_storage, TYPE_TAG, entity_id
        );
        sui::object::delete(id);
    }
}
