# Dubhe Indexer Configuration Example
# 
# Logging configuration examples:
# 1. Development mode (verbose logging):
#    level = "debug"
#
# 2. Production mode (standard logging):
#    level = "info"
#
# 3. Error only mode (minimal logging):
#    level = "error"
#
# Available log levels: debug, info, warn, error

[sui]
rpc_url = "https://fullnode.testnet.sui.io:443"
checkpoint_url = "https://checkpoints.testnet.sui.io"
origin_package_id = "0x2"
start_checkpoint = 10

# Database configuration
[database]
# Database type: sqlite or postgres
db_type = "sqlite"
# Database connection URL
# SQLite example: "sqlite:///data/indexer.db"
# PostgreSQL example: "postgres://user:password@localhost:5432/indexer"
# url = "postgres://postgres:password@localhost:5432/indexer"
url = "./indexer.db"
# Maximum number of connections in the pool
max_connections = 10

# GRPC service configuration
[grpc]
# Listen address
addr = "0.0.0.0:50051"
# TLS certificate configuration (optional)
tls_cert = "/path/to/cert.pem"
tls_key = "/path/to/key.pem"

# Subscription system configuration
[subscription]
# Maximum number of client connections
max_clients = 1000
# Channel buffer capacity
channel_capacity = 1000

# Logging configuration
[logging]
# Log level: debug, info, warn, error
level = "info"

# Monitoring configuration
[metrics]
# Enable Prometheus monitoring
enabled = true
# Prometheus monitoring address
addr = "0.0.0.0:9090"

# Event processing configuration
[events]
# Batch size
batch_size = 100
# Batch interval (milliseconds)
batch_interval_ms = 1000

# Event processing retry configuration
[events.retry]
# Maximum retry attempts
max_attempts = 3
# Initial retry interval (milliseconds)
initial_interval_ms = 1000
# Retry interval multiplier
multiplier = 2

# Cache configuration
[cache]
# Enable caching
enabled = true
# Cache type: memory or redis
type = "memory"
# Cache size (MB)
size_mb = 1024

# Redis configuration (used when type is redis)
[cache.redis]
url = "redis://localhost:6379"
password = ""
db = 0

# System resource limits
[limits]
# Maximum memory usage (MB)
max_memory_mb = 4096
# Maximum CPU usage (percentage)
max_cpu_percent = 80
# Maximum disk usage (GB)
max_disk_gb = 100 