packages:
    - packages/aptos-cli
    - packages/aptos-client
    - packages/aptos-common
    - packages/sui-cli
    - packages/sui-client
    - packages/sui-common
    # - packages/*
    # - packages/create-obelisk/* # just for test
