[package]
name = "sov-nft-module"
description = "A Sovereign SDK module for managing non-fungible tokens"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde = { workspace = true }
schemars = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }

sov-modules-api = { workspace = true }
sov-state = { workspace = true }

postgres = { version = "0.19.7", optional = true }
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
sov-nft-module = { version = "*", features = ["native"], path = "." }
tempfile = { workspace = true }
sov-test-utils = { workspace = true }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }

[features]
default = []
offchain = ["postgres", "sov-nft-module/offchain", "tokio", "tracing"]
native = [
    "jsonrpsee",
    "schemars",
    "sov-modules-api/native",
    "sov-nft-module/native",
    "sov-state/native",
]
