// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::agent {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"agent";
    const OFFCHAIN: bool = false;

    public struct Agent has copy, drop, store {
        name: String,
        personality: String,
        occupation: u8,
        energy: u64,
        mood: u64,
        location: u8,
        last_action_ms: u64,
        last_work_ms: u64,
        last_sleep_ms: u64,
        born_at: u64,
    }

    public fun new(name: String, personality: String, occupation: u8, energy: u64, mood: u64, location: u8, last_action_ms: u64, last_work_ms: u64, last_sleep_ms: u64, born_at: u64): Agent {
        Agent {
            name,
            personality,
            occupation,
            energy,
            mood,
            location,
            last_action_ms,
            last_work_ms,
            last_sleep_ms,
            born_at,
        }
    }

    public fun name(self: &Agent): String {
        self.name
    }

    public fun personality(self: &Agent): String {
        self.personality
    }

    public fun occupation(self: &Agent): u8 {
        self.occupation
    }

    public fun energy(self: &Agent): u64 {
        self.energy
    }

    public fun mood(self: &Agent): u64 {
        self.mood
    }

    public fun location(self: &Agent): u8 {
        self.location
    }

    public fun last_action_ms(self: &Agent): u64 {
        self.last_action_ms
    }

    public fun last_work_ms(self: &Agent): u64 {
        self.last_work_ms
    }

    public fun last_sleep_ms(self: &Agent): u64 {
        self.last_sleep_ms
    }

    public fun born_at(self: &Agent): u64 {
        self.born_at
    }

    public fun update_name(self: &mut Agent, name: String) {
        self.name = name
    }

    public fun update_personality(self: &mut Agent, personality: String) {
        self.personality = personality
    }

    public fun update_occupation(self: &mut Agent, occupation: u8) {
        self.occupation = occupation
    }

    public fun update_energy(self: &mut Agent, energy: u64) {
        self.energy = energy
    }

    public fun update_mood(self: &mut Agent, mood: u64) {
        self.mood = mood
    }

    public fun update_location(self: &mut Agent, location: u8) {
        self.location = location
    }

    public fun update_last_action_ms(self: &mut Agent, last_action_ms: u64) {
        self.last_action_ms = last_action_ms
    }

    public fun update_last_work_ms(self: &mut Agent, last_work_ms: u64) {
        self.last_work_ms = last_work_ms
    }

    public fun update_last_sleep_ms(self: &mut Agent, last_sleep_ms: u64) {
        self.last_sleep_ms = last_sleep_ms
    }

    public fun update_born_at(self: &mut Agent, born_at: u64) {
        self.born_at = born_at
    }

    public fun has(user_storage: &UserStorage, agent_id: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, agent_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, agent_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, agent_id: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"name", b"personality", b"occupation", b"energy", b"mood", b"location", b"last_action_ms", b"last_work_ms", b"last_sleep_ms", b"born_at"], ctx);
    }

    public fun get_name(user_storage: &UserStorage, agent_id: address): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        name
    }

    public(package) fun set_name(user_storage: &mut UserStorage, agent_id: address, name: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&into_bytes(name));
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"name", value, ctx);
    }

    public fun get_personality(user_storage: &UserStorage, agent_id: address): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let personality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"personality");
        let mut personality_bcs = sui::bcs::new(personality_raw);
        let personality = dubhe::bcs::peel_string(&mut personality_bcs);
        personality
    }

    public(package) fun set_personality(user_storage: &mut UserStorage, agent_id: address, personality: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&into_bytes(personality));
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"personality", value, ctx);
    }

    public fun get_occupation(user_storage: &UserStorage, agent_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let occupation_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"occupation");
        let mut occupation_bcs = sui::bcs::new(occupation_raw);
        let occupation = sui::bcs::peel_u8(&mut occupation_bcs);
        occupation
    }

    public(package) fun set_occupation(user_storage: &mut UserStorage, agent_id: address, occupation: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&occupation);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"occupation", value, ctx);
    }

    public fun get_energy(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let energy_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"energy");
        let mut energy_bcs = sui::bcs::new(energy_raw);
        let energy = sui::bcs::peel_u64(&mut energy_bcs);
        energy
    }

    public(package) fun set_energy(user_storage: &mut UserStorage, agent_id: address, energy: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&energy);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"energy", value, ctx);
    }

    public fun get_mood(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let mood_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"mood");
        let mut mood_bcs = sui::bcs::new(mood_raw);
        let mood = sui::bcs::peel_u64(&mut mood_bcs);
        mood
    }

    public(package) fun set_mood(user_storage: &mut UserStorage, agent_id: address, mood: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&mood);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"mood", value, ctx);
    }

    public fun get_location(user_storage: &UserStorage, agent_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let location_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"location");
        let mut location_bcs = sui::bcs::new(location_raw);
        let location = sui::bcs::peel_u8(&mut location_bcs);
        location
    }

    public(package) fun set_location(user_storage: &mut UserStorage, agent_id: address, location: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&location);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"location", value, ctx);
    }

    public fun get_last_action_ms(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let last_action_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_action_ms");
        let mut last_action_ms_bcs = sui::bcs::new(last_action_ms_raw);
        let last_action_ms = sui::bcs::peel_u64(&mut last_action_ms_bcs);
        last_action_ms
    }

    public(package) fun set_last_action_ms(user_storage: &mut UserStorage, agent_id: address, last_action_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&last_action_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"last_action_ms", value, ctx);
    }

    public fun get_last_work_ms(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let last_work_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_work_ms");
        let mut last_work_ms_bcs = sui::bcs::new(last_work_ms_raw);
        let last_work_ms = sui::bcs::peel_u64(&mut last_work_ms_bcs);
        last_work_ms
    }

    public(package) fun set_last_work_ms(user_storage: &mut UserStorage, agent_id: address, last_work_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&last_work_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"last_work_ms", value, ctx);
    }

    public fun get_last_sleep_ms(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let last_sleep_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_sleep_ms");
        let mut last_sleep_ms_bcs = sui::bcs::new(last_sleep_ms_raw);
        let last_sleep_ms = sui::bcs::peel_u64(&mut last_sleep_ms_bcs);
        last_sleep_ms
    }

    public(package) fun set_last_sleep_ms(user_storage: &mut UserStorage, agent_id: address, last_sleep_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&last_sleep_ms);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"last_sleep_ms", value, ctx);
    }

    public fun get_born_at(user_storage: &UserStorage, agent_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        born_at
    }

    public(package) fun set_born_at(user_storage: &mut UserStorage, agent_id: address, born_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let value = to_bytes(&born_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"born_at", value, ctx);
    }

    public fun get(user_storage: &UserStorage, agent_id: address): (String, String, u8, u64, u64, u8, u64, u64, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        let personality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"personality");
        let mut personality_bcs = sui::bcs::new(personality_raw);
        let personality = dubhe::bcs::peel_string(&mut personality_bcs);
        let occupation_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"occupation");
        let mut occupation_bcs = sui::bcs::new(occupation_raw);
        let occupation = sui::bcs::peel_u8(&mut occupation_bcs);
        let energy_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"energy");
        let mut energy_bcs = sui::bcs::new(energy_raw);
        let energy = sui::bcs::peel_u64(&mut energy_bcs);
        let mood_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"mood");
        let mut mood_bcs = sui::bcs::new(mood_raw);
        let mood = sui::bcs::peel_u64(&mut mood_bcs);
        let location_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"location");
        let mut location_bcs = sui::bcs::new(location_raw);
        let location = sui::bcs::peel_u8(&mut location_bcs);
        let last_action_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_action_ms");
        let mut last_action_ms_bcs = sui::bcs::new(last_action_ms_raw);
        let last_action_ms = sui::bcs::peel_u64(&mut last_action_ms_bcs);
        let last_work_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_work_ms");
        let mut last_work_ms_bcs = sui::bcs::new(last_work_ms_raw);
        let last_work_ms = sui::bcs::peel_u64(&mut last_work_ms_bcs);
        let last_sleep_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_sleep_ms");
        let mut last_sleep_ms_bcs = sui::bcs::new(last_sleep_ms_raw);
        let last_sleep_ms = sui::bcs::peel_u64(&mut last_sleep_ms_bcs);
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        (name, personality, occupation, energy, mood, location, last_action_ms, last_work_ms, last_sleep_ms, born_at)
    }

    public(package) fun set(user_storage: &mut UserStorage, agent_id: address, name: String, personality: String, occupation: u8, energy: u64, mood: u64, location: u8, last_action_ms: u64, last_work_ms: u64, last_sleep_ms: u64, born_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"name", b"personality", b"occupation", b"energy", b"mood", b"location", b"last_action_ms", b"last_work_ms", b"last_sleep_ms", b"born_at"];
        let value_tuple = encode(name, personality, occupation, energy, mood, location, last_action_ms, last_work_ms, last_sleep_ms, born_at);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, agent_id: address): Agent {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        let personality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"personality");
        let mut personality_bcs = sui::bcs::new(personality_raw);
        let personality = dubhe::bcs::peel_string(&mut personality_bcs);
        let occupation_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"occupation");
        let mut occupation_bcs = sui::bcs::new(occupation_raw);
        let occupation = sui::bcs::peel_u8(&mut occupation_bcs);
        let energy_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"energy");
        let mut energy_bcs = sui::bcs::new(energy_raw);
        let energy = sui::bcs::peel_u64(&mut energy_bcs);
        let mood_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"mood");
        let mut mood_bcs = sui::bcs::new(mood_raw);
        let mood = sui::bcs::peel_u64(&mut mood_bcs);
        let location_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"location");
        let mut location_bcs = sui::bcs::new(location_raw);
        let location = sui::bcs::peel_u8(&mut location_bcs);
        let last_action_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_action_ms");
        let mut last_action_ms_bcs = sui::bcs::new(last_action_ms_raw);
        let last_action_ms = sui::bcs::peel_u64(&mut last_action_ms_bcs);
        let last_work_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_work_ms");
        let mut last_work_ms_bcs = sui::bcs::new(last_work_ms_raw);
        let last_work_ms = sui::bcs::peel_u64(&mut last_work_ms_bcs);
        let last_sleep_ms_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_sleep_ms");
        let mut last_sleep_ms_bcs = sui::bcs::new(last_sleep_ms_raw);
        let last_sleep_ms = sui::bcs::peel_u64(&mut last_sleep_ms_bcs);
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        Agent { name, personality, occupation, energy, mood, location, last_action_ms, last_work_ms, last_sleep_ms, born_at }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, agent_id: address, agent: Agent, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"name", b"personality", b"occupation", b"energy", b"mood", b"location", b"last_action_ms", b"last_work_ms", b"last_sleep_ms", b"born_at"];
        let value_tuple = encode_struct(agent);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(name: String, personality: String, occupation: u8, energy: u64, mood: u64, location: u8, last_action_ms: u64, last_work_ms: u64, last_sleep_ms: u64, born_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&into_bytes(name)));
        value_tuple.push_back(to_bytes(&into_bytes(personality)));
        value_tuple.push_back(to_bytes(&occupation));
        value_tuple.push_back(to_bytes(&energy));
        value_tuple.push_back(to_bytes(&mood));
        value_tuple.push_back(to_bytes(&location));
        value_tuple.push_back(to_bytes(&last_action_ms));
        value_tuple.push_back(to_bytes(&last_work_ms));
        value_tuple.push_back(to_bytes(&last_sleep_ms));
        value_tuple.push_back(to_bytes(&born_at));
        value_tuple
    }

    public fun encode_struct(agent: Agent): vector<vector<u8>> {
        encode(agent.name, agent.personality, agent.occupation, agent.energy, agent.mood, agent.location, agent.last_action_ms, agent.last_work_ms, agent.last_sleep_ms, agent.born_at)
    }

    public fun decode(data: vector<u8>): Agent {
        let mut bcs_type = sui::bcs::new(data);
        let name = string(sui::bcs::peel_vec_u8(&mut bcs_type));
        let personality = string(sui::bcs::peel_vec_u8(&mut bcs_type));
        let occupation = sui::bcs::peel_u8(&mut bcs_type);
        let energy = sui::bcs::peel_u64(&mut bcs_type);
        let mood = sui::bcs::peel_u64(&mut bcs_type);
        let location = sui::bcs::peel_u8(&mut bcs_type);
        let last_action_ms = sui::bcs::peel_u64(&mut bcs_type);
        let last_work_ms = sui::bcs::peel_u64(&mut bcs_type);
        let last_sleep_ms = sui::bcs::peel_u64(&mut bcs_type);
        let born_at = sui::bcs::peel_u64(&mut bcs_type);
        Agent {
            name,
            personality,
            occupation,
            energy,
            mood,
            location,
            last_action_ms,
            last_work_ms,
            last_sleep_ms,
            born_at,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        agent_id: address, name: String, personality: String, occupation: u8, energy: u64, mood: u64, location: u8, last_action_ms: u64, last_work_ms: u64, last_sleep_ms: u64, born_at: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, agent_id);
        set(user_storage, agent_id, name, personality, occupation, energy, mood, location, last_action_ms, last_work_ms, last_sleep_ms, born_at, ctx);
    }
}