// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::agent_position {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"agent_position";
    const OFFCHAIN: bool = true;

    public struct AgentPosition has copy, drop, store {
        x: u64,
        y: u64,
        activity: u8,
    }

    public fun new(x: u64, y: u64, activity: u8): AgentPosition {
        AgentPosition {
            x,
            y,
            activity,
        }
    }

    public fun x(self: &AgentPosition): u64 {
        self.x
    }

    public fun y(self: &AgentPosition): u64 {
        self.y
    }

    public fun activity(self: &AgentPosition): u8 {
        self.activity
    }

    public fun update_x(self: &mut AgentPosition, x: u64) {
        self.x = x
    }

    public fun update_y(self: &mut AgentPosition, y: u64) {
        self.y = y
    }

    public fun update_activity(self: &mut AgentPosition, activity: u8) {
        self.activity = activity
    }

    public(package) fun set(user_storage: &mut UserStorage, agent_id: address, x: u64, y: u64, activity: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"x", b"y", b"activity"];
        let value_tuple = encode(x, y, activity);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, agent_id: address, agent_position: AgentPosition, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"x", b"y", b"activity"];
        let value_tuple = encode_struct(agent_position);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(x: u64, y: u64, activity: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&x));
        value_tuple.push_back(to_bytes(&y));
        value_tuple.push_back(to_bytes(&activity));
        value_tuple
    }

    public fun encode_struct(agent_position: AgentPosition): vector<vector<u8>> {
        encode(agent_position.x, agent_position.y, agent_position.activity)
    }
}