// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::election_state {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"election_state";
    const OFFCHAIN: bool = false;

    public struct ElectionState has copy, drop, store {
        round: u64,
        ends_at: u64,
        candidate_a: address,
        candidate_b: address,
        votes_a: u64,
        votes_b: u64,
    }

    public fun new(round: u64, ends_at: u64, candidate_a: address, candidate_b: address, votes_a: u64, votes_b: u64): ElectionState {
        ElectionState {
            round,
            ends_at,
            candidate_a,
            candidate_b,
            votes_a,
            votes_b,
        }
    }

    public fun round(self: &ElectionState): u64 {
        self.round
    }

    public fun ends_at(self: &ElectionState): u64 {
        self.ends_at
    }

    public fun candidate_a(self: &ElectionState): address {
        self.candidate_a
    }

    public fun candidate_b(self: &ElectionState): address {
        self.candidate_b
    }

    public fun votes_a(self: &ElectionState): u64 {
        self.votes_a
    }

    public fun votes_b(self: &ElectionState): u64 {
        self.votes_b
    }

    public fun update_round(self: &mut ElectionState, round: u64) {
        self.round = round
    }

    public fun update_ends_at(self: &mut ElectionState, ends_at: u64) {
        self.ends_at = ends_at
    }

    public fun update_candidate_a(self: &mut ElectionState, candidate_a: address) {
        self.candidate_a = candidate_a
    }

    public fun update_candidate_b(self: &mut ElectionState, candidate_b: address) {
        self.candidate_b = candidate_b
    }

    public fun update_votes_a(self: &mut ElectionState, votes_a: u64) {
        self.votes_a = votes_a
    }

    public fun update_votes_b(self: &mut ElectionState, votes_b: u64) {
        self.votes_b = votes_b
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"round", b"ends_at", b"candidate_a", b"candidate_b", b"votes_a", b"votes_b"]);
    }

    public fun get_round(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let round_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u64(&mut round_bcs);
        round
    }

    public(package) fun set_round(dapp_storage: &mut DappStorage, round: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&round);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"round", value);
    }

    public fun get_ends_at(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let ends_at_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"ends_at");
        let mut ends_at_bcs = sui::bcs::new(ends_at_raw);
        let ends_at = sui::bcs::peel_u64(&mut ends_at_bcs);
        ends_at
    }

    public(package) fun set_ends_at(dapp_storage: &mut DappStorage, ends_at: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&ends_at);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"ends_at", value);
    }

    public fun get_candidate_a(dapp_storage: &DappStorage): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let candidate_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_a");
        let mut candidate_a_bcs = sui::bcs::new(candidate_a_raw);
        let candidate_a = sui::bcs::peel_address(&mut candidate_a_bcs);
        candidate_a
    }

    public(package) fun set_candidate_a(dapp_storage: &mut DappStorage, candidate_a: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&candidate_a);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"candidate_a", value);
    }

    public fun get_candidate_b(dapp_storage: &DappStorage): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let candidate_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_b");
        let mut candidate_b_bcs = sui::bcs::new(candidate_b_raw);
        let candidate_b = sui::bcs::peel_address(&mut candidate_b_bcs);
        candidate_b
    }

    public(package) fun set_candidate_b(dapp_storage: &mut DappStorage, candidate_b: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&candidate_b);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"candidate_b", value);
    }

    public fun get_votes_a(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let votes_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_a");
        let mut votes_a_bcs = sui::bcs::new(votes_a_raw);
        let votes_a = sui::bcs::peel_u64(&mut votes_a_bcs);
        votes_a
    }

    public(package) fun set_votes_a(dapp_storage: &mut DappStorage, votes_a: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&votes_a);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"votes_a", value);
    }

    public fun get_votes_b(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let votes_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_b");
        let mut votes_b_bcs = sui::bcs::new(votes_b_raw);
        let votes_b = sui::bcs::peel_u64(&mut votes_b_bcs);
        votes_b
    }

    public(package) fun set_votes_b(dapp_storage: &mut DappStorage, votes_b: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&votes_b);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"votes_b", value);
    }

    public fun get(dapp_storage: &DappStorage): (u64, u64, address, address, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let round_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u64(&mut round_bcs);
        let ends_at_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"ends_at");
        let mut ends_at_bcs = sui::bcs::new(ends_at_raw);
        let ends_at = sui::bcs::peel_u64(&mut ends_at_bcs);
        let candidate_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_a");
        let mut candidate_a_bcs = sui::bcs::new(candidate_a_raw);
        let candidate_a = sui::bcs::peel_address(&mut candidate_a_bcs);
        let candidate_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_b");
        let mut candidate_b_bcs = sui::bcs::new(candidate_b_raw);
        let candidate_b = sui::bcs::peel_address(&mut candidate_b_bcs);
        let votes_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_a");
        let mut votes_a_bcs = sui::bcs::new(votes_a_raw);
        let votes_a = sui::bcs::peel_u64(&mut votes_a_bcs);
        let votes_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_b");
        let mut votes_b_bcs = sui::bcs::new(votes_b_raw);
        let votes_b = sui::bcs::peel_u64(&mut votes_b_bcs);
        (round, ends_at, candidate_a, candidate_b, votes_a, votes_b)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, round: u64, ends_at: u64, candidate_a: address, candidate_b: address, votes_a: u64, votes_b: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"round", b"ends_at", b"candidate_a", b"candidate_b", b"votes_a", b"votes_b"];
        let value_tuple = encode(round, ends_at, candidate_a, candidate_b, votes_a, votes_b);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): ElectionState {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let round_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"round");
        let mut round_bcs = sui::bcs::new(round_raw);
        let round = sui::bcs::peel_u64(&mut round_bcs);
        let ends_at_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"ends_at");
        let mut ends_at_bcs = sui::bcs::new(ends_at_raw);
        let ends_at = sui::bcs::peel_u64(&mut ends_at_bcs);
        let candidate_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_a");
        let mut candidate_a_bcs = sui::bcs::new(candidate_a_raw);
        let candidate_a = sui::bcs::peel_address(&mut candidate_a_bcs);
        let candidate_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"candidate_b");
        let mut candidate_b_bcs = sui::bcs::new(candidate_b_raw);
        let candidate_b = sui::bcs::peel_address(&mut candidate_b_bcs);
        let votes_a_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_a");
        let mut votes_a_bcs = sui::bcs::new(votes_a_raw);
        let votes_a = sui::bcs::peel_u64(&mut votes_a_bcs);
        let votes_b_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"votes_b");
        let mut votes_b_bcs = sui::bcs::new(votes_b_raw);
        let votes_b = sui::bcs::peel_u64(&mut votes_b_bcs);
        ElectionState { round, ends_at, candidate_a, candidate_b, votes_a, votes_b }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, election_state: ElectionState) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"round", b"ends_at", b"candidate_a", b"candidate_b", b"votes_a", b"votes_b"];
        let value_tuple = encode_struct(election_state);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(round: u64, ends_at: u64, candidate_a: address, candidate_b: address, votes_a: u64, votes_b: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&round));
        value_tuple.push_back(to_bytes(&ends_at));
        value_tuple.push_back(to_bytes(&candidate_a));
        value_tuple.push_back(to_bytes(&candidate_b));
        value_tuple.push_back(to_bytes(&votes_a));
        value_tuple.push_back(to_bytes(&votes_b));
        value_tuple
    }

    public fun encode_struct(election_state: ElectionState): vector<vector<u8>> {
        encode(election_state.round, election_state.ends_at, election_state.candidate_a, election_state.candidate_b, election_state.votes_a, election_state.votes_b)
    }

    public fun decode(data: vector<u8>): ElectionState {
        let mut bcs_type = sui::bcs::new(data);
        let round = sui::bcs::peel_u64(&mut bcs_type);
        let ends_at = sui::bcs::peel_u64(&mut bcs_type);
        let candidate_a = sui::bcs::peel_address(&mut bcs_type);
        let candidate_b = sui::bcs::peel_address(&mut bcs_type);
        let votes_a = sui::bcs::peel_u64(&mut bcs_type);
        let votes_b = sui::bcs::peel_u64(&mut bcs_type);
        ElectionState {
            round,
            ends_at,
            candidate_a,
            candidate_b,
            votes_a,
            votes_b,
        }
    }
}