// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::item {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::{UserStorage, DappStorage};
    use dubhe::dapp_service::ScenePermit;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"item";
    const OFFCHAIN: bool = false;

    public struct Item has copy, drop, store {
        kind: u8,
        quality: u8,
    }

    public fun new(kind: u8, quality: u8): Item {
        Item {
            kind,
            quality,
        }
    }

    public fun kind(self: &Item): u8 {
        self.kind
    }

    public fun quality(self: &Item): u8 {
        self.quality
    }

    public fun update_kind(self: &mut Item, kind: u8) {
        self.kind = kind
    }

    public fun update_quality(self: &mut Item, quality: u8) {
        self.quality = quality
    }

    public fun has(user_storage: &UserStorage, item_id: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, item_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, item_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, item_id: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"kind", b"quality"], ctx);
    }

    public fun get_kind(user_storage: &UserStorage, item_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"kind");
        let mut kind_bcs = sui::bcs::new(kind_raw);
        let kind = sui::bcs::peel_u8(&mut kind_bcs);
        kind
    }

    public(package) fun set_kind(user_storage: &mut UserStorage, item_id: address, kind: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let value = to_bytes(&kind);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"kind", value, ctx);
    }

    public fun get_quality(user_storage: &UserStorage, item_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let quality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"quality");
        let mut quality_bcs = sui::bcs::new(quality_raw);
        let quality = sui::bcs::peel_u8(&mut quality_bcs);
        quality
    }

    public(package) fun set_quality(user_storage: &mut UserStorage, item_id: address, quality: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let value = to_bytes(&quality);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"quality", value, ctx);
    }

    public fun get(user_storage: &UserStorage, item_id: address): (u8, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"kind");
        let mut kind_bcs = sui::bcs::new(kind_raw);
        let kind = sui::bcs::peel_u8(&mut kind_bcs);
        let quality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"quality");
        let mut quality_bcs = sui::bcs::new(quality_raw);
        let quality = sui::bcs::peel_u8(&mut quality_bcs);
        (kind, quality)
    }

    public(package) fun set(user_storage: &mut UserStorage, item_id: address, kind: u8, quality: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let field_names = vector[b"kind", b"quality"];
        let value_tuple = encode(kind, quality);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, item_id: address): Item {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let kind_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"kind");
        let mut kind_bcs = sui::bcs::new(kind_raw);
        let kind = sui::bcs::peel_u8(&mut kind_bcs);
        let quality_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"quality");
        let mut quality_bcs = sui::bcs::new(quality_raw);
        let quality = sui::bcs::peel_u8(&mut quality_bcs);
        Item { kind, quality }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, item_id: address, item: Item, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let field_names = vector[b"kind", b"quality"];
        let value_tuple = encode_struct(item);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(kind: u8, quality: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&kind));
        value_tuple.push_back(to_bytes(&quality));
        value_tuple
    }

    public fun encode_struct(item: Item): vector<vector<u8>> {
        encode(item.kind, item.quality)
    }

    public fun decode(data: vector<u8>): Item {
        let mut bcs_type = sui::bcs::new(data);
        let kind = sui::bcs::peel_u8(&mut bcs_type);
        let quality = sui::bcs::peel_u8(&mut bcs_type);
        Item {
            kind,
            quality,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        item_id: address, kind: u8, quality: u8,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, item_id);
        set(user_storage, item_id, kind, quality, ctx);
    }

    // ─── reactive: cross-user write variants ───────────────────────────
    // Package-level helpers: add pause checks and access control in your system
    // functions before calling these.
    public(package) fun set_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        item_id: address, kind: u8, quality: u8,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&item_id));
        let field_names = vector[b"kind", b"quality"];
        let value_tuple = encode(kind, quality);
        dapp_system::set_record_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, field_names, value_tuple, ctx);
    }

    public(package) fun set_kind_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        item_id: address, kind: u8,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&item_id));
        let value = sui::bcs::to_bytes(&kind);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"kind", value, ctx);
    }

    public(package) fun set_quality_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        item_id: address, quality: u8,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&item_id));
        let value = sui::bcs::to_bytes(&quality);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"quality", value, ctx);
    }

    // ─── listable: market protocol (keyed) ──────────────────────────────
    // Package-level helpers: call these from your system functions.
    // Add pause checks, access control, and custom logic there.
    public(package) fun list<CoinType>(
        user_storage: &mut UserStorage,
        item_id:   address,
        price:        u64,
        listed_until: std::option::Option<u64>,
        ctx:          &mut TxContext,
    ) {
        let mut record_key = vector::empty();
        record_key.push_back(TABLE_NAME);
        record_key.push_back(sui::bcs::to_bytes(&item_id));
        dubhe::dapp_system::take_record<DappKey, CoinType>(
            dapp_key::new(),
            user_storage,
            b"item",
            record_key,
            vector[b"kind", b"quality"],
            price,
            listed_until,
            ctx,
        );
    }

    public(package) fun buy<CoinType>(
        dh:            &dubhe::dapp_service::DappHub,
        dapp_storage:  &mut DappStorage,
        listing:       dubhe::dapp_service::Listing<CoinType>,
        user_storage:  &mut UserStorage,
        payment:       sui::coin::Coin<CoinType>,
        ctx:           &mut TxContext,
    ): sui::coin::Coin<CoinType> {
        dubhe::dapp_system::buy_record<DappKey, CoinType>(
            dapp_key::new(), dh, dapp_storage, listing, user_storage, payment, ctx
        )
    }

    public(package) fun cancel_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::restore_record<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public(package) fun expire_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::expire_listing<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }
}