// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::profile {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"profile";
    const OFFCHAIN: bool = false;

    public struct Profile has copy, drop, store {
        agents_minted: u32,
        total_earned: u64,
    }

    public fun new(agents_minted: u32, total_earned: u64): Profile {
        Profile {
            agents_minted,
            total_earned,
        }
    }

    public fun agents_minted(self: &Profile): u32 {
        self.agents_minted
    }

    public fun total_earned(self: &Profile): u64 {
        self.total_earned
    }

    public fun update_agents_minted(self: &mut Profile, agents_minted: u32) {
        self.agents_minted = agents_minted
    }

    public fun update_total_earned(self: &mut Profile, total_earned: u64) {
        self.total_earned = total_earned
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"agents_minted", b"total_earned"], ctx);
    }

    public fun get_agents_minted(user_storage: &UserStorage): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let agents_minted_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"agents_minted");
        let mut agents_minted_bcs = sui::bcs::new(agents_minted_raw);
        let agents_minted = sui::bcs::peel_u32(&mut agents_minted_bcs);
        agents_minted
    }

    public(package) fun set_agents_minted(user_storage: &mut UserStorage, agents_minted: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&agents_minted);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"agents_minted", value, ctx);
    }

    public fun get_total_earned(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        total_earned
    }

    public(package) fun set_total_earned(user_storage: &mut UserStorage, total_earned: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&total_earned);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"total_earned", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (u32, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let agents_minted_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"agents_minted");
        let mut agents_minted_bcs = sui::bcs::new(agents_minted_raw);
        let agents_minted = sui::bcs::peel_u32(&mut agents_minted_bcs);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        (agents_minted, total_earned)
    }

    public(package) fun set(user_storage: &mut UserStorage, agents_minted: u32, total_earned: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"agents_minted", b"total_earned"];
        let value_tuple = encode(agents_minted, total_earned);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): Profile {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let agents_minted_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"agents_minted");
        let mut agents_minted_bcs = sui::bcs::new(agents_minted_raw);
        let agents_minted = sui::bcs::peel_u32(&mut agents_minted_bcs);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        Profile { agents_minted, total_earned }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, profile: Profile, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"agents_minted", b"total_earned"];
        let value_tuple = encode_struct(profile);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(agents_minted: u32, total_earned: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&agents_minted));
        value_tuple.push_back(to_bytes(&total_earned));
        value_tuple
    }

    public fun encode_struct(profile: Profile): vector<vector<u8>> {
        encode(profile.agents_minted, profile.total_earned)
    }

    public fun decode(data: vector<u8>): Profile {
        let mut bcs_type = sui::bcs::new(data);
        let agents_minted = sui::bcs::peel_u32(&mut bcs_type);
        let total_earned = sui::bcs::peel_u64(&mut bcs_type);
        Profile {
            agents_minted,
            total_earned,
        }
    }
}