// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::relationship {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_service::ScenePermit;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"relationship";
    const OFFCHAIN: bool = false;

    public struct Relationship has copy, drop, store {
        affinity: u64,
        interactions: u64,
    }

    public fun new(affinity: u64, interactions: u64): Relationship {
        Relationship {
            affinity,
            interactions,
        }
    }

    public fun affinity(self: &Relationship): u64 {
        self.affinity
    }

    public fun interactions(self: &Relationship): u64 {
        self.interactions
    }

    public fun update_affinity(self: &mut Relationship, affinity: u64) {
        self.affinity = affinity
    }

    public fun update_interactions(self: &mut Relationship, interactions: u64) {
        self.interactions = interactions
    }

    public fun has(user_storage: &UserStorage, agent_id: address, other_agent: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, agent_id: address, other_agent: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, agent_id: address, other_agent: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, agent_id: address, other_agent: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"affinity", b"interactions"], ctx);
    }

    public fun get_affinity(user_storage: &UserStorage, agent_id: address, other_agent: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let affinity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"affinity");
        let mut affinity_bcs = sui::bcs::new(affinity_raw);
        let affinity = sui::bcs::peel_u64(&mut affinity_bcs);
        affinity
    }

    public(package) fun set_affinity(user_storage: &mut UserStorage, agent_id: address, other_agent: address, affinity: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let value = to_bytes(&affinity);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"affinity", value, ctx);
    }

    public fun get_interactions(user_storage: &UserStorage, agent_id: address, other_agent: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let interactions_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"interactions");
        let mut interactions_bcs = sui::bcs::new(interactions_raw);
        let interactions = sui::bcs::peel_u64(&mut interactions_bcs);
        interactions
    }

    public(package) fun set_interactions(user_storage: &mut UserStorage, agent_id: address, other_agent: address, interactions: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let value = to_bytes(&interactions);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"interactions", value, ctx);
    }

    public fun get(user_storage: &UserStorage, agent_id: address, other_agent: address): (u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let affinity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"affinity");
        let mut affinity_bcs = sui::bcs::new(affinity_raw);
        let affinity = sui::bcs::peel_u64(&mut affinity_bcs);
        let interactions_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"interactions");
        let mut interactions_bcs = sui::bcs::new(interactions_raw);
        let interactions = sui::bcs::peel_u64(&mut interactions_bcs);
        (affinity, interactions)
    }

    public(package) fun set(user_storage: &mut UserStorage, agent_id: address, other_agent: address, affinity: u64, interactions: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let field_names = vector[b"affinity", b"interactions"];
        let value_tuple = encode(affinity, interactions);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, agent_id: address, other_agent: address): Relationship {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let affinity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"affinity");
        let mut affinity_bcs = sui::bcs::new(affinity_raw);
        let affinity = sui::bcs::peel_u64(&mut affinity_bcs);
        let interactions_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"interactions");
        let mut interactions_bcs = sui::bcs::new(interactions_raw);
        let interactions = sui::bcs::peel_u64(&mut interactions_bcs);
        Relationship { affinity, interactions }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, agent_id: address, other_agent: address, relationship: Relationship, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&agent_id));
        key_tuple.push_back(to_bytes(&other_agent));
        let field_names = vector[b"affinity", b"interactions"];
        let value_tuple = encode_struct(relationship);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(affinity: u64, interactions: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&affinity));
        value_tuple.push_back(to_bytes(&interactions));
        value_tuple
    }

    public fun encode_struct(relationship: Relationship): vector<vector<u8>> {
        encode(relationship.affinity, relationship.interactions)
    }

    public fun decode(data: vector<u8>): Relationship {
        let mut bcs_type = sui::bcs::new(data);
        let affinity = sui::bcs::peel_u64(&mut bcs_type);
        let interactions = sui::bcs::peel_u64(&mut bcs_type);
        Relationship {
            affinity,
            interactions,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        agent_id: address, other_agent: address, affinity: u64, interactions: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, agent_id, other_agent);
        set(user_storage, agent_id, other_agent, affinity, interactions, ctx);
    }

    // ─── reactive: cross-user write variants ───────────────────────────
    // Package-level helpers: add pause checks and access control in your system
    // functions before calling these.
    public(package) fun set_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        agent_id: address, other_agent: address, affinity: u64, interactions: u64,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&agent_id));
        key_tuple.push_back(sui::bcs::to_bytes(&other_agent));
        let field_names = vector[b"affinity", b"interactions"];
        let value_tuple = encode(affinity, interactions);
        dapp_system::set_record_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, field_names, value_tuple, ctx);
    }

    public(package) fun set_affinity_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        agent_id: address, other_agent: address, affinity: u64,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&agent_id));
        key_tuple.push_back(sui::bcs::to_bytes(&other_agent));
        let value = sui::bcs::to_bytes(&affinity);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"affinity", value, ctx);
    }

    public(package) fun set_interactions_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        agent_id: address, other_agent: address, interactions: u64,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(sui::bcs::to_bytes(&agent_id));
        key_tuple.push_back(sui::bcs::to_bytes(&other_agent));
        let value = sui::bcs::to_bytes(&interactions);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"interactions", value, ctx);
    }
}