// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::town_config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"town_config";
    const OFFCHAIN: bool = false;

    public struct TownConfig has copy, drop, store {
        day: u64,
        day_start_ms: u64,
        day_length_ms: u64,
        festival_until: u64,
        mayor_agent: address,
        mayor_owner: address,
        population: u64,
    }

    public fun new(day: u64, day_start_ms: u64, day_length_ms: u64, festival_until: u64, mayor_agent: address, mayor_owner: address, population: u64): TownConfig {
        TownConfig {
            day,
            day_start_ms,
            day_length_ms,
            festival_until,
            mayor_agent,
            mayor_owner,
            population,
        }
    }

    public fun day(self: &TownConfig): u64 {
        self.day
    }

    public fun day_start_ms(self: &TownConfig): u64 {
        self.day_start_ms
    }

    public fun day_length_ms(self: &TownConfig): u64 {
        self.day_length_ms
    }

    public fun festival_until(self: &TownConfig): u64 {
        self.festival_until
    }

    public fun mayor_agent(self: &TownConfig): address {
        self.mayor_agent
    }

    public fun mayor_owner(self: &TownConfig): address {
        self.mayor_owner
    }

    public fun population(self: &TownConfig): u64 {
        self.population
    }

    public fun update_day(self: &mut TownConfig, day: u64) {
        self.day = day
    }

    public fun update_day_start_ms(self: &mut TownConfig, day_start_ms: u64) {
        self.day_start_ms = day_start_ms
    }

    public fun update_day_length_ms(self: &mut TownConfig, day_length_ms: u64) {
        self.day_length_ms = day_length_ms
    }

    public fun update_festival_until(self: &mut TownConfig, festival_until: u64) {
        self.festival_until = festival_until
    }

    public fun update_mayor_agent(self: &mut TownConfig, mayor_agent: address) {
        self.mayor_agent = mayor_agent
    }

    public fun update_mayor_owner(self: &mut TownConfig, mayor_owner: address) {
        self.mayor_owner = mayor_owner
    }

    public fun update_population(self: &mut TownConfig, population: u64) {
        self.population = population
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"day", b"day_start_ms", b"day_length_ms", b"festival_until", b"mayor_agent", b"mayor_owner", b"population"]);
    }

    public fun get_day(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let day_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day");
        let mut day_bcs = sui::bcs::new(day_raw);
        let day = sui::bcs::peel_u64(&mut day_bcs);
        day
    }

    public(package) fun set_day(dapp_storage: &mut DappStorage, day: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&day);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"day", value);
    }

    public fun get_day_start_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let day_start_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_start_ms");
        let mut day_start_ms_bcs = sui::bcs::new(day_start_ms_raw);
        let day_start_ms = sui::bcs::peel_u64(&mut day_start_ms_bcs);
        day_start_ms
    }

    public(package) fun set_day_start_ms(dapp_storage: &mut DappStorage, day_start_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&day_start_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"day_start_ms", value);
    }

    public fun get_day_length_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let day_length_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_length_ms");
        let mut day_length_ms_bcs = sui::bcs::new(day_length_ms_raw);
        let day_length_ms = sui::bcs::peel_u64(&mut day_length_ms_bcs);
        day_length_ms
    }

    public(package) fun set_day_length_ms(dapp_storage: &mut DappStorage, day_length_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&day_length_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"day_length_ms", value);
    }

    public fun get_festival_until(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let festival_until_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"festival_until");
        let mut festival_until_bcs = sui::bcs::new(festival_until_raw);
        let festival_until = sui::bcs::peel_u64(&mut festival_until_bcs);
        festival_until
    }

    public(package) fun set_festival_until(dapp_storage: &mut DappStorage, festival_until: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&festival_until);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"festival_until", value);
    }

    public fun get_mayor_agent(dapp_storage: &DappStorage): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let mayor_agent_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_agent");
        let mut mayor_agent_bcs = sui::bcs::new(mayor_agent_raw);
        let mayor_agent = sui::bcs::peel_address(&mut mayor_agent_bcs);
        mayor_agent
    }

    public(package) fun set_mayor_agent(dapp_storage: &mut DappStorage, mayor_agent: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&mayor_agent);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"mayor_agent", value);
    }

    public fun get_mayor_owner(dapp_storage: &DappStorage): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let mayor_owner_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_owner");
        let mut mayor_owner_bcs = sui::bcs::new(mayor_owner_raw);
        let mayor_owner = sui::bcs::peel_address(&mut mayor_owner_bcs);
        mayor_owner
    }

    public(package) fun set_mayor_owner(dapp_storage: &mut DappStorage, mayor_owner: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&mayor_owner);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"mayor_owner", value);
    }

    public fun get_population(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let population_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"population");
        let mut population_bcs = sui::bcs::new(population_raw);
        let population = sui::bcs::peel_u64(&mut population_bcs);
        population
    }

    public(package) fun set_population(dapp_storage: &mut DappStorage, population: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&population);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"population", value);
    }

    public fun get(dapp_storage: &DappStorage): (u64, u64, u64, u64, address, address, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let day_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day");
        let mut day_bcs = sui::bcs::new(day_raw);
        let day = sui::bcs::peel_u64(&mut day_bcs);
        let day_start_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_start_ms");
        let mut day_start_ms_bcs = sui::bcs::new(day_start_ms_raw);
        let day_start_ms = sui::bcs::peel_u64(&mut day_start_ms_bcs);
        let day_length_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_length_ms");
        let mut day_length_ms_bcs = sui::bcs::new(day_length_ms_raw);
        let day_length_ms = sui::bcs::peel_u64(&mut day_length_ms_bcs);
        let festival_until_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"festival_until");
        let mut festival_until_bcs = sui::bcs::new(festival_until_raw);
        let festival_until = sui::bcs::peel_u64(&mut festival_until_bcs);
        let mayor_agent_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_agent");
        let mut mayor_agent_bcs = sui::bcs::new(mayor_agent_raw);
        let mayor_agent = sui::bcs::peel_address(&mut mayor_agent_bcs);
        let mayor_owner_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_owner");
        let mut mayor_owner_bcs = sui::bcs::new(mayor_owner_raw);
        let mayor_owner = sui::bcs::peel_address(&mut mayor_owner_bcs);
        let population_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"population");
        let mut population_bcs = sui::bcs::new(population_raw);
        let population = sui::bcs::peel_u64(&mut population_bcs);
        (day, day_start_ms, day_length_ms, festival_until, mayor_agent, mayor_owner, population)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, day: u64, day_start_ms: u64, day_length_ms: u64, festival_until: u64, mayor_agent: address, mayor_owner: address, population: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"day", b"day_start_ms", b"day_length_ms", b"festival_until", b"mayor_agent", b"mayor_owner", b"population"];
        let value_tuple = encode(day, day_start_ms, day_length_ms, festival_until, mayor_agent, mayor_owner, population);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): TownConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let day_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day");
        let mut day_bcs = sui::bcs::new(day_raw);
        let day = sui::bcs::peel_u64(&mut day_bcs);
        let day_start_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_start_ms");
        let mut day_start_ms_bcs = sui::bcs::new(day_start_ms_raw);
        let day_start_ms = sui::bcs::peel_u64(&mut day_start_ms_bcs);
        let day_length_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"day_length_ms");
        let mut day_length_ms_bcs = sui::bcs::new(day_length_ms_raw);
        let day_length_ms = sui::bcs::peel_u64(&mut day_length_ms_bcs);
        let festival_until_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"festival_until");
        let mut festival_until_bcs = sui::bcs::new(festival_until_raw);
        let festival_until = sui::bcs::peel_u64(&mut festival_until_bcs);
        let mayor_agent_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_agent");
        let mut mayor_agent_bcs = sui::bcs::new(mayor_agent_raw);
        let mayor_agent = sui::bcs::peel_address(&mut mayor_agent_bcs);
        let mayor_owner_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"mayor_owner");
        let mut mayor_owner_bcs = sui::bcs::new(mayor_owner_raw);
        let mayor_owner = sui::bcs::peel_address(&mut mayor_owner_bcs);
        let population_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"population");
        let mut population_bcs = sui::bcs::new(population_raw);
        let population = sui::bcs::peel_u64(&mut population_bcs);
        TownConfig { day, day_start_ms, day_length_ms, festival_until, mayor_agent, mayor_owner, population }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, town_config: TownConfig) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"day", b"day_start_ms", b"day_length_ms", b"festival_until", b"mayor_agent", b"mayor_owner", b"population"];
        let value_tuple = encode_struct(town_config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(day: u64, day_start_ms: u64, day_length_ms: u64, festival_until: u64, mayor_agent: address, mayor_owner: address, population: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&day));
        value_tuple.push_back(to_bytes(&day_start_ms));
        value_tuple.push_back(to_bytes(&day_length_ms));
        value_tuple.push_back(to_bytes(&festival_until));
        value_tuple.push_back(to_bytes(&mayor_agent));
        value_tuple.push_back(to_bytes(&mayor_owner));
        value_tuple.push_back(to_bytes(&population));
        value_tuple
    }

    public fun encode_struct(town_config: TownConfig): vector<vector<u8>> {
        encode(town_config.day, town_config.day_start_ms, town_config.day_length_ms, town_config.festival_until, town_config.mayor_agent, town_config.mayor_owner, town_config.population)
    }

    public fun decode(data: vector<u8>): TownConfig {
        let mut bcs_type = sui::bcs::new(data);
        let day = sui::bcs::peel_u64(&mut bcs_type);
        let day_start_ms = sui::bcs::peel_u64(&mut bcs_type);
        let day_length_ms = sui::bcs::peel_u64(&mut bcs_type);
        let festival_until = sui::bcs::peel_u64(&mut bcs_type);
        let mayor_agent = sui::bcs::peel_address(&mut bcs_type);
        let mayor_owner = sui::bcs::peel_address(&mut bcs_type);
        let population = sui::bcs::peel_u64(&mut bcs_type);
        TownConfig {
            day,
            day_start_ms,
            day_length_ms,
            festival_until,
            mayor_agent,
            mayor_owner,
            population,
        }
    }
}