// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::vote_record {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"vote_record";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage, round: u64, agent_id: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, round: u64, agent_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, round: u64, agent_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, round: u64, agent_id: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"candidate"], ctx);
    }

    public fun get(user_storage: &UserStorage, round: u64, agent_id: address): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        let candidate_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"candidate");
        let mut candidate_bcs = sui::bcs::new(candidate_raw);
        let value = sui::bcs::peel_address(&mut candidate_bcs);
        value
    }

    public(package) fun set(user_storage: &mut UserStorage, round: u64, agent_id: address, value: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&round));
        key_tuple.push_back(to_bytes(&agent_id));
        let field_names = vector[b"candidate"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: address): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        round: u64, agent_id: address, candidate: address,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, round, agent_id);
        set(user_storage, round, agent_id, candidate, ctx);
    }
}