[package]
name = "sov-bank"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

sov-modules-api = { workspace = true }
sov-state = { workspace = true }

[dev-dependencies]
sov-bank = { path = ".", features = ["native", "test-utils"] }
tempfile = { workspace = true }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }
sov-test-utils = { workspace = true }

[features]
default = []
native = [
    "jsonrpsee",
    "schemars",
    "sov-bank/native",
    "sov-modules-api/native",
    "sov-state/native",
]
cli = ["native"]
test-utils = []
