// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module guild::error {
    #[error]
    const ENotGuildMember: vector<u8> = b"Caller is not a guild member";
    public fun not_guild_member(condition: bool) { assert!(condition, ENotGuildMember) }

    #[error]
    const EMatchAlreadyEnded: vector<u8> = b"Match has already ended";
    public fun match_already_ended(condition: bool) { assert!(condition, EMatchAlreadyEnded) }
}
