[package]
name = "sov-risc0-adapter"
authors = { workspace = true }
description = "An adapter allowing Risc0 to be used with the Sovereign SDK"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "README.md"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
digest = { workspace = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"] }
risc0-zkvm-platform = { workspace = true }
serde = { workspace = true }
bytemuck = "1.15.0"
once_cell = { workspace = true, optional = true }
parking_lot = { version = "0.12.1", optional = true }
risc0-cycle-utils = { workspace = true }
sov-rollup-interface = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true, optional = true }

sha2 = { version = "0.10.6" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.0-risczero.1", features = ["serde"] }

arbitrary = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }

[features]
default = []
native = [
    "ed25519-dalek/default",
    "ed25519-dalek/rand_core",
    "rand",
    "risc0-cycle-utils/native",
    "risc0-zkvm/prove",
    "sov-rollup-interface/native",
]
bench = ["native", "once_cell", "parking_lot", "risc0-cycle-utils/native"]
arbitrary = ["dep:arbitrary", "sov-rollup-interface/arbitrary"]

[[test]]
name = "native"
required-features = ["native"]
