// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::arena {
    use dubhe::dapp_service::DappStorage;
    use card_duel::dapp_key;
    use card_duel::dapp_key::DappKey;
    use std::ascii::String;
    use card_duel::duel;
    use card_duel::brawl;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const EWrongEntityId: vector<u8> = b"Wrong entity id";
    #[error]
    const ENoPermission: vector<u8> = b"Caller does not have permission";

    const TYPE_TAG: vector<u8> = b"arena";

    // ─── Phantom marker type ───────────────────────────────────────────────
    /// Phantom type that distinguishes ArenaStorage from other ObjectStorage types
    /// at the Move compiler level, preserving compile-time type safety.
    /// All functions use ObjectStorage<Arena> directly in their signatures.
    public struct Arena has copy, drop {}

    // ─── ID / entity accessors ─────────────────────────────────────────────

    public fun entity_id(storage: &dubhe::dapp_service::ObjectStorage<Arena>): vector<u8> {
        *dubhe::dapp_service::object_storage_entity_id(storage)
    }


    public fun assert_arena_id(storage: &dubhe::dapp_service::ObjectStorage<Arena>, expected: vector<u8>) {
        assert!(*dubhe::dapp_service::object_storage_entity_id(storage) == expected, EWrongEntityId);
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_name(storage: &dubhe::dapp_service::ObjectStorage<Arena>): String {
        dubhe::dapp_system::get_object_field<Arena, String>(storage, b"name")
    }

    public(package) fun set_name(storage: &mut dubhe::dapp_service::ObjectStorage<Arena>, value: String) {
        dubhe::dapp_system::set_object_field<DappKey, Arena, String>(
            dapp_key::new(), storage, b"name", value
        );
    }

    public fun get_season(storage: &dubhe::dapp_service::ObjectStorage<Arena>): u8 {
        dubhe::dapp_system::get_object_field<Arena, u8>(storage, b"season")
    }

    public(package) fun set_season(storage: &mut dubhe::dapp_service::ObjectStorage<Arena>, value: u8) {
        dubhe::dapp_system::set_object_field<DappKey, Arena, u8>(
            dapp_key::new(), storage, b"season", value
        );
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::ObjectStorage<Arena>): u64 {
        if (dubhe::dapp_system::has_object_field<Arena, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_object_field<Arena, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Arena>, amount: u64) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_object_field<DappKey, Arena, u64>(
            dapp_key::new(), storage, b"gold", current + amount
        );
    }

    public(package) fun sub_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Arena>, amount: u64) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_object_field<DappKey, Arena, u64>(
            dapp_key::new(), storage, b"gold", current - amount
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer gold (fungible) from duel into this arena.
    public(package) fun transfer_duel_to_arena_gold(
        source_permit: &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        from:   &mut dubhe::dapp_service::SceneStorage<card_duel::duel::Duel>,
        to:     &mut dubhe::dapp_service::ObjectStorage<Arena>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount: u64,
        ctx:        &TxContext,

    ) {
        duel::sub_gold(source_permit, from, user_storage, amount, ctx);
        add_gold(to, amount);
    }

    /// Transfer gold (fungible) from brawl into this arena.
    public(package) fun transfer_brawl_to_arena_gold(
        source_permit: &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        from:   &mut dubhe::dapp_service::SceneStorage<card_duel::brawl::Brawl>,
        to:     &mut dubhe::dapp_service::ObjectStorage<Arena>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount: u64,
        ctx:        &TxContext,

    ) {
        brawl::sub_gold(source_permit, from, user_storage, amount, ctx);
        add_gold(to, amount);
    }

    // ─── Lifecycle entry functions ─────────────────────────────────────────
    public(package) fun create_arena(
        dapp_storage: &mut DappStorage,
        entity_id:    vector<u8>,
        ctx:          &mut TxContext,
    ) {
        assert!(ctx.sender() == dubhe::dapp_service::dapp_admin(dapp_storage), ENoPermission);
        dubhe::dapp_system::create_and_share_typed_object<DappKey, Arena>(
            dapp_key::new(), dapp_storage, TYPE_TAG, entity_id, ctx
        );
    }

    public(package) fun destroy_arena(
        dapp_storage: &mut DappStorage,
        storage:      dubhe::dapp_service::ObjectStorage<Arena>,
        _ctx:         &TxContext,
    ) {
        dubhe::dapp_system::destroy_typed_object<DappKey, Arena>(
            dapp_key::new(), dapp_storage, storage
        );
    }
}
