[package]
name = "sov-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sov_cli"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-bank = { workspace = true, features = ["native"] }
sov-nonces = { workspace = true, features = ["native"] }
sov-rollup-interface = { workspace = true }
sov-ledger-json-client = { workspace = true }
sov-sequencer-json-client = { workspace = true }
directories = "5.0.1"
anyhow = { workspace = true }
hex = { workspace = true, features = ["serde"] }
borsh = { workspace = true }
semver = "1.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
jsonrpsee = { workspace = true, features = ["client"] }

[dev-dependencies]
tempfile = { workspace = true }
demo-stf = { workspace = true, features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
