  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::proxy_config { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use dubhe::dapp_key;
    use dubhe::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"proxy_config";
    const OFFCHAIN: bool = false;

    public fun has(dapp_hub: &DappHub, dapp_key: String, account: String): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::has_record<DappKey>(dapp_hub, dapp_key::package_id().to_ascii_string(), key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::ensure_has_record<DappKey>(dapp_hub, dapp_key::package_id().to_ascii_string(), key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::ensure_has_not_record<DappKey>(dapp_hub, dapp_key::package_id().to_ascii_string(), key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, dapp_key::package_id().to_ascii_string());
    }

    public fun get(dapp_hub: &DappHub, dapp_key: String, account: String): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let value = dapp_service::get_field<DappKey>(dapp_hub, dapp_key::package_id().to_ascii_string(), key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let value = dubhe::bcs::peel_string(&mut bsc_type);
        value
    }

    public(package) fun set(dapp_hub: &mut DappHub, dapp_key: String, account: String, value: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let value_tuple = encode(value);
        dapp_service::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, dapp_key::package_id().to_ascii_string(), OFFCHAIN, ctx);
    }

    public fun encode(value: String): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&into_bytes(value)));
        value_tuple
    }
}