  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module test_project::resource10 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use test_project::dapp_key;
    use test_project::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"resource10";
    const OFFCHAIN: bool = false;

    public struct Resource10 has copy, drop, store {
        player: address,
        value: String,
    }

    public fun new(player: address, value: String): Resource10 {
        Resource10 {
            player,
            value,
        }
    }

    public fun player(self: &Resource10): address {
        self.player
    }

    public fun value(self: &Resource10): String {
        self.value
    }

    public fun update_player(self: &mut Resource10, player: address) {
        self.player = player
    }

    public fun update_value(self: &mut Resource10, value: String) {
        self.value = value
    }

    public fun has(user_storage: &UserStorage, name: String): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, name: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, name: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, name: String, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"player", b"value"], ctx);
    }

    public fun get_player(user_storage: &UserStorage, name: String): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        player
    }

    public(package) fun set_player(user_storage: &mut UserStorage, name: String, player: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let value = to_bytes(&player);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"player", value, ctx);
    }

    public fun get_value(user_storage: &UserStorage, name: String): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = dubhe::bcs::peel_string(&mut value_bcs);
        value
    }

    public(package) fun set_value(user_storage: &mut UserStorage, name: String, value: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let value = to_bytes(&into_bytes(value));
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"value", value, ctx);
    }

    public fun get(user_storage: &UserStorage, name: String): (address, String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = dubhe::bcs::peel_string(&mut value_bcs);
        (player, value)
    }

    public(package) fun set(user_storage: &mut UserStorage, name: String, player: address, value: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let field_names = vector[b"player", b"value"];
        let value_tuple = encode(player, value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, name: String): Resource10 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = dubhe::bcs::peel_string(&mut value_bcs);
        Resource10 { player, value }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, name: String, resource10: Resource10, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&name));
        let field_names = vector[b"player", b"value"];
        let value_tuple = encode_struct(resource10);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(player: address, value: String): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&player));
        value_tuple.push_back(to_bytes(&into_bytes(value)));
        value_tuple
    }

    public fun encode_struct(resource10: Resource10): vector<vector<u8>> {
        encode(resource10.player, resource10.value)
    }

    public fun decode(data: vector<u8>): Resource10 {
        let mut bsc_type = sui::bcs::new(data);
        let player = sui::bcs::peel_address(&mut bsc_type);
        let value = string(sui::bcs::peel_vec_u8(&mut bsc_type));
        Resource10 {
            player,
            value,
        }
    }
}