[package]
name = "sov-prover-storage-manager"
description = "Hierarchical storage manager for prover storage"
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-db = { workspace = true }
rockbound = { workspace = true }
sov-state = { workspace = true, features = ["native"] }
tracing = { workspace = true }

[dev-dependencies]
sov-mock-da = { workspace = true, features = ["native"] }
sov-mock-zkvm = { workspace = true, features = ["native"] }
rockbound = { workspace = true, features = ["test-utils"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros"] }
criterion = "0.5.1"
rand = { workspace = true }
sha2 = { workspace = true }

[[bench]]
name = "single_thread_storage_bench"
path = "benches/single_thread_progression.rs"
harness = false

[features]
default = []
test-utils = ["rockbound/test-utils"]
