[package]
name = "sov-attester-incentives"
description = "A Sovereign SDK module for incentivizing provers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"
publish = false

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
sov-attester-incentives = { workspace = true, features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-mock-zkvm = { workspace = true }
sov-test-utils = { workspace = true }
sov-modules-api = { workspace = true, features = ["test-utils"] }
sov-rollup-interface = { workspace = true }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
bcs = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
derivative = { workspace = true }
tracing = { workspace = true }

sov-bank = { workspace = true }
sov-chain-state = { workspace = true }
sov-modules-api = { workspace = true }
sov-state = { workspace = true }

[features]
default = []
native = [
    "sov-attester-incentives/native",
    "sov-bank/native",
    "sov-chain-state/native",
    "sov-mock-da/native",
    "sov-mock-zkvm/native",
    "sov-modules-api/native",
    "sov-rollup-interface/native",
    "sov-state/native",
]
