[package]
name = "demo-simple-stf"
version = { workspace = true }
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

[lints]
workspace = true

[features]
native = [
    "sov-mock-da/native",
    "sov-mock-zkvm/native",
    "sov-rollup-interface/native",
]

[dependencies]
serde = { workspace = true }
sha2 = { workspace = true }

sov-rollup-interface = { workspace = true }

[dev-dependencies]
sov-mock-da = { workspace = true }
sov-mock-zkvm = { workspace = true }
