// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module guild::dungeon_run_permit {
    use dubhe::dapp_service::{Self, DappStorage};
    use guild::dapp_key;
    use guild::dapp_key::DappKey;

    const PERMIT_TYPE: vector<u8> = b"dungeon_run_permit";

    #[error]
    const EPermitNotExpiredYet: vector<u8> = b"Scene permit is still active";

    /// Phantom type that distinguishes this permit from others at compile time.
    public struct DungeonRunPermit has copy, drop {}

    public fun meta(permit: &dubhe::dapp_service::ScenePermit<DungeonRunPermit>): &dubhe::dapp_service::PermitMetadata {
        dapp_service::scene_permit_meta(permit)
    }

    public fun is_active(permit: &dubhe::dapp_service::ScenePermit<DungeonRunPermit>, now_ms: u64): bool {
        dapp_service::is_scene_active(dapp_service::scene_permit_meta(permit), now_ms)
    }

    public fun is_participant(permit: &dubhe::dapp_service::ScenePermit<DungeonRunPermit>, addr: address): bool {
        dubhe::dapp_system::is_scene_permit_participant<DungeonRunPermit>(permit, addr)
    }

    public(package) fun new_dungeon_run_permit(
        dapp_storage:     &DappStorage,
        participants:     vector<address>,
        expires_at:       std::option::Option<u64>,
        max_participants: std::option::Option<u64>,
        ctx:              &mut TxContext,
    ): dubhe::dapp_service::ScenePermit<DungeonRunPermit> {
        dubhe::dapp_system::new_scene_permit<DappKey, DungeonRunPermit>(
            dapp_key::new(), dapp_storage, PERMIT_TYPE, participants, expires_at, max_participants, ctx
        )
    }

    public(package) fun new_dungeon_run_permit_with_invitations(
        dapp_storage:      &DappStorage,
        invitees:          vector<address>,
        invites_expire_at: std::option::Option<u64>,
        scene_expires_at:  std::option::Option<u64>,
        max_participants:  std::option::Option<u64>,
        ctx:               &mut TxContext,
    ): dubhe::dapp_service::ScenePermit<DungeonRunPermit> {
        dubhe::dapp_system::new_scene_permit_with_invitations<DappKey, DungeonRunPermit>(
            dapp_key::new(), dapp_storage, PERMIT_TYPE, invitees, invites_expire_at, scene_expires_at, max_participants, ctx
        )
    }

    public(package) fun share_dungeon_run_permit(permit: dubhe::dapp_service::ScenePermit<DungeonRunPermit>) {
        dubhe::dapp_system::share_scene_permit<DappKey, DungeonRunPermit>(
            dapp_key::new(), permit
        );
    }

    public(package) fun create_dungeon_run_permit(
        dapp_storage:     &DappStorage,
        participants:     vector<address>,
        expires_at:       std::option::Option<u64>,
        max_participants: std::option::Option<u64>,
        ctx:              &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_scene_permit<DappKey, DungeonRunPermit>(
            dapp_key::new(), dapp_storage, PERMIT_TYPE, participants, expires_at, max_participants, ctx
        );
    }

    public(package) fun create_dungeon_run_permit_with_invitations(
        dapp_storage:      &DappStorage,
        invitees:          vector<address>,
        invites_expire_at: std::option::Option<u64>,
        scene_expires_at:  std::option::Option<u64>,
        max_participants:  std::option::Option<u64>,
        ctx:               &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_scene_permit_with_invitations<DappKey, DungeonRunPermit>(
            dapp_key::new(), dapp_storage, PERMIT_TYPE, invitees, invites_expire_at, scene_expires_at, max_participants, ctx
        );
    }

    public(package) fun accept_dungeon_run_permit(
        permit: &mut dubhe::dapp_service::ScenePermit<DungeonRunPermit>,
        ctx:    &TxContext,
    ) {
        dubhe::dapp_system::accept_scene_permit_invitation<DappKey, DungeonRunPermit>(
            dapp_key::new(), permit, ctx
        );
    }

    public(package) fun join_dungeon_run_permit(
        permit: &mut dubhe::dapp_service::ScenePermit<DungeonRunPermit>,
        ctx:    &TxContext,
    ) {
        dubhe::dapp_system::join_scene_permit<DappKey, DungeonRunPermit>(dapp_key::new(), permit, ctx);
    }

    public(package) fun leave_dungeon_run_permit(
        permit: &mut dubhe::dapp_service::ScenePermit<DungeonRunPermit>,
        ctx:    &TxContext,
    ) {
        dubhe::dapp_system::leave_scene_permit<DappKey, DungeonRunPermit>(dapp_key::new(), permit, ctx);
    }

    public(package) fun expire_dungeon_run_permit(
        permit: dubhe::dapp_service::ScenePermit<DungeonRunPermit>,
        ctx:    &TxContext,
    ) {
        assert!(
            !dapp_service::is_scene_active(dapp_service::scene_permit_meta(&permit), ctx.epoch_timestamp_ms()),
            EPermitNotExpiredYet
        );
        dubhe::dapp_system::destroy_scene_permit<DappKey, DungeonRunPermit>(
            dapp_key::new(), permit
        );
    }
}
