import { DubheConfig } from '@0xobelisk/sui-common';

export const dubheConfig = {
  name: 'dubhe',
  description: 'Dubhe Protocol',
  errors: {
    asset_not_found: 'Asset not found',
    asset_already_frozen: 'Asset already frozen',
    invalid_sender: 'Invalid sender',
    invalid_receiver: 'Invalid receiver',
    invalid_metadata: 'Invalid metadata',
    account_not_found: 'Account not found',
    account_blocked: 'Account is blocked',
    account_frozen: 'Account is frozen',
    balance_too_low: 'Balance too low',
    overflows: 'Operation overflows',
    no_permission: 'No permission',
    not_mintable: 'Asset is not mintable',
    not_burnable: 'Asset is not burnable',
    not_freezable: 'Asset is not freezable',
    below_min_amount: 'Amount is below minimum',
    liquidity_cannot_be_zero: 'Liquidity cannot be 0',
    more_than_max_swap_path_len: 'More than Max',
    more_than_reserve: 'More than reserve',
    swap_path_too_small: 'Swap path too small',
    reserves_cannot_be_zero: 'Reserve cannot be 0',
    amount_cannot_be_zero: 'Amount cannot be 0',
    less_than_amount_out_min: 'Less than expected',
    more_than_amount_in_max: 'More than expected',
    bridge_not_opened: 'Bridge is not opened',
    not_latest_version: 'Not latest version',
    dapp_paused: 'Dapp is paused',
    invalid_package_id: 'Invalid package id',
    invalid_version: 'Invalid version',
    dapp_not_initialized: 'Dapp not initialized',
    dapp_already_initialized: 'Dapp already initialized',
    insufficient_credit: 'Insufficient credit',
    dapp_not_been_delegated: 'Dapp not been delegated',
    dapp_already_delegated: 'Dapp already delegated',
    no_pending_ownership_transfer: 'No pending ownership transfer',
    user_debt_limit_exceeded: 'User debt limit exceeded',
    dapp_suspended: 'Dapp is suspended',
    dapp_key_mismatch: 'Dapp key mismatch',
    no_active_session: 'No active session',
    not_canonical_owner: 'Not canonical owner',
    insufficient_credit_to_unsuspend: 'Insufficient credit to unsuspend',
    user_storage_already_exists: 'User storage already exists',
    invalid_session_key: 'Invalid session key',
    invalid_session_duration: 'Invalid session duration',
    wrong_payment_coin_type: 'Wrong payment coin type',
    no_pending_coin_type_change: 'No pending coin type change',
    coin_type_change_not_ready: 'Coin type change not ready',
    wrong_settlement_mode: 'Wrong settlement mode',
    revenue_share_exceeds_max: 'Revenue share exceeds max',
    no_revenue_to_withdraw: 'No revenue to withdraw',

    // ── Scene / ObjectStorage framework errors ──────────────────────────────
    // These are used by dapp_system.move (e.g. accept_scene_invitation,
    // set_record_reactive). They must be present in error.move so that the
    // e2e copy of dapp_system.move compiles correctly.
    write_limit_out_of_range: 'Write limit out of range',
    scene_expired: 'Scene has expired',
    not_scene_participant: 'Not a scene participant',
    entity_not_found: 'Entity not found',
    entity_id_already_exists: 'Entity id already exists',
    insufficient_balance: 'Insufficient balance',
    marketplace_fee_exceeds_max: 'Marketplace fee bps cannot exceed 10000',
    not_participant: 'Sender is not a participant or invitee',
    scene_full: 'Scene has reached its maximum participant limit',
    invitation_expired: 'Invitation window has expired',
    listing_not_found: 'Listing not found',
    listing_type_mismatch: 'Listing type mismatch',
    only_seller_can_cancel: 'Only the original seller can cancel',
    invalid_key: 'Invalid key',
    invalid_solana_address: 'Invalid Solana address',
    invalid_evm_address: 'Invalid EVM address',
    length_mismatch: 'Length mismatch',
    math_overflow: 'Math overflow',
    division_by_zero: 'Division by zero',
    invalid_window_size: 'Invalid window size',
    participants_still_present: 'Cannot destroy scene while participants are still present',
    insufficient_payment: 'Insufficient payment for listing price',
    item_already_owned: 'Buyer already owns an item with this key'
  }
} as DubheConfig;
