import fs from 'node:fs/promises';
import path from 'node:path';
import { debug } from '../debug';

export async function formatAndWriteMove(
  output: string,
  fullOutputPath: string,
  logPrefix?: string
): Promise<void> {
  const formattedOutput = output;
  const fileHeader = `// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

`;

  const initPrefix = `#[test_only]\n`;

  let code = fileHeader + formattedOutput;

  const deployHookPrefix = `#[allow(lint(share_owned))]\n`;

  if (
    fullOutputPath.includes('.toml') ||
    fullOutputPath.includes('system') ||
    fullOutputPath.includes('migrate')
  ) {
    code = formattedOutput;
  } else if (fullOutputPath.includes('init_test')) {
    code = initPrefix + formattedOutput;
  } else if (fullOutputPath.includes('genesis')) {
    code = deployHookPrefix + formattedOutput;
  }

  await fs.mkdir(path.dirname(fullOutputPath), { recursive: true });
  await fs.writeFile(fullOutputPath, code);
  debug(`${logPrefix}: ${fullOutputPath}`);
}
