[package]
name = "sov-sequencer-registry"
description = "A Sovereign SDK module for registering rollup sequencers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"

resolver = "2"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
sov-bank = { workspace = true }
sov-modules-api = { workspace = true }
sov-state = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
risc0-cycle-macros = { workspace = true, optional = true }
risc0-cycle-utils = { workspace = true, optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
sov-sequencer-registry = { path = ".", features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }
sov-modules-api = { workspace = true, features = ["test-utils"] }

[features]
bench = [
    "risc0-cycle-macros",
    "risc0-cycle-macros?/bench",
    "risc0-cycle-utils",
    "risc0-zkvm",
    "risc0-zkvm-platform",
    "sov-modules-api/bench",
    "sov-sequencer-registry/bench",
    "sov-state/bench",
]
default = []
arbitrary = [
    "dep:arbitrary",
    "dep:proptest",
    "dep:proptest-derive",
    "sov-modules-api/arbitrary",
    "sov-sequencer-registry/arbitrary",
    "sov-state/arbitrary",
    "sov-test-utils/arbitrary",
]
native = [
    "jsonrpsee",
    "risc0-cycle-utils?/native",
    "schemars",
    # This:
    "sov-bank/native",
    "sov-mock-da/native",
    "sov-modules-api/native",
    "sov-sequencer-registry/native",
    "sov-state/native",
]
