// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::error {
    #[error]
    const ENotAuthorized: vector<u8> = b"Caller is not authorized";
    public fun not_authorized(condition: bool) { assert!(condition, ENotAuthorized) }

    #[error]
    const EInsufficientLevel: vector<u8> = b"Level requirement not met";
    public fun insufficient_level(condition: bool) { assert!(condition, EInsufficientLevel) }
}
