// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::vault {
    use dubhe::dapp_service::DappStorage;
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::dungeon;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EFieldNotFound: vector<u8> = b"Field not found";
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const EDuplicateItemId: vector<u8> = b"Duplicate item id";
    #[error]
    const EWrongEntityId: vector<u8> = b"Wrong entity id";

    const TYPE_TAG: vector<u8> = b"vault";

    // ─── Phantom marker type ───────────────────────────────────────────────
    /// Phantom type that distinguishes VaultStorage from other ObjectStorage types
    /// at the Move compiler level, preserving compile-time type safety.
    /// All functions use ObjectStorage<Vault> directly in their signatures.
    public struct Vault has copy, drop {}

    // ─── ID / entity accessors ─────────────────────────────────────────────

    public fun entity_id(storage: &dubhe::dapp_service::ObjectStorage<Vault>): vector<u8> {
        *dubhe::dapp_service::object_storage_entity_id(storage)
    }


    public fun assert_vault_id(storage: &dubhe::dapp_service::ObjectStorage<Vault>, expected: vector<u8>) {
        assert!(*dubhe::dapp_service::object_storage_entity_id(storage) == expected, EWrongEntityId);
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_level(storage: &dubhe::dapp_service::ObjectStorage<Vault>): u32 {
        dubhe::dapp_system::get_object_field<Vault, u32>(storage, b"level")
    }

    public(package) fun set_level(storage: &mut dubhe::dapp_service::ObjectStorage<Vault>, value: u32) {
        dubhe::dapp_system::set_object_field<DappKey, Vault, u32>(
            dapp_key::new(), storage, b"level", value
        );
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::ObjectStorage<Vault>): u64 {
        if (dubhe::dapp_system::has_object_field<Vault, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_object_field<Vault, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Vault>, amount: u64) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_object_field<DappKey, Vault, u64>(
            dapp_key::new(), storage, b"gold", current + amount
        );
    }

    public(package) fun sub_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Vault>, amount: u64) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_object_field<DappKey, Vault, u64>(
            dapp_key::new(), storage, b"gold", current - amount
        );
    }

    public fun has_sword(storage: &dubhe::dapp_service::ObjectStorage<Vault>, item_id: u64): bool {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::has_object_field<Vault, vector<u8>>(storage, key)
    }

    public fun get_sword_data(storage: &dubhe::dapp_service::ObjectStorage<Vault>, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::get_object_field<Vault, vector<u8>>(storage, key)
    }

    public(package) fun set_sword_data(storage: &mut dubhe::dapp_service::ObjectStorage<Vault>, item_id: u64, data: vector<u8>) {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(!dubhe::dapp_system::has_object_field<Vault, vector<u8>>(storage, key), EDuplicateItemId);
        dubhe::dapp_system::set_object_field<DappKey, Vault, vector<u8>>(
            dapp_key::new(), storage, key, data
        );
    }

    public(package) fun remove_sword_data(storage: &mut dubhe::dapp_service::ObjectStorage<Vault>, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(dubhe::dapp_system::has_object_field<Vault, vector<u8>>(storage, key), EFieldNotFound);
        dubhe::dapp_system::remove_object_field<DappKey, Vault, vector<u8>>(dapp_key::new(), storage, key)
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer gold (fungible) from dungeon into this vault.
    public(package) fun transfer_dungeon_to_vault_gold(
        source_permit: &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        from:   &mut dubhe::dapp_service::SceneStorage<example::dungeon::Dungeon>,
        to:     &mut dubhe::dapp_service::ObjectStorage<Vault>,
        amount: u64,
        ctx:        &TxContext,

    ) {
        dungeon::sub_gold(source_permit, from, amount, ctx);
        add_gold(to, amount);
    }

    /// Transfer sword (unique item) from dungeon into this vault.
    public(package) fun transfer_dungeon_to_vault_sword(
        source_permit: &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        from:       &mut dubhe::dapp_service::SceneStorage<example::dungeon::Dungeon>,
        to:         &mut dubhe::dapp_service::ObjectStorage<Vault>,
        item_id: u64,
        ctx:        &TxContext,

    ) {
        let data = dungeon::remove_sword_data(source_permit, from, item_id, ctx);
        set_sword_data(to, item_id, data);
    }

    // ─── Lifecycle entry functions ─────────────────────────────────────────
    public fun create_vault(
        dapp_storage: &mut DappStorage,
        entity_id:    vector<u8>,
        ctx:          &mut TxContext,
    ) {

        dubhe::dapp_system::create_and_share_typed_object<DappKey, Vault>(
            dapp_key::new(), dapp_storage, TYPE_TAG, entity_id, ctx
        );
    }

    public fun destroy_vault(
        dapp_storage: &mut DappStorage,
        storage:      dubhe::dapp_service::ObjectStorage<Vault>,
        _ctx:         &TxContext,
    ) {
        dubhe::dapp_system::destroy_typed_object<DappKey, Vault>(
            dapp_key::new(), dapp_storage, storage
        );
    }
}
