[package]
name = "sov-blob-storage"
description = "A Sovereign SDK module for holding blobs from Data Availability Layer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "README.md"

resolver = "2"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }

sov-modules-api = { workspace = true }
sov-state = { workspace = true }
sov-sequencer-registry = { workspace = true }
sov-chain-state = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
sov-blob-storage = { path = ".", features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-bank = { workspace = true }
sov-test-utils = { workspace = true }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }
sov-kernels = { workspace = true, features = ["native", "test-utils"] }

[features]
default = []
native = [
    "sov-bank/native",
    "sov-blob-storage/native",
    "sov-chain-state/native",
    "sov-kernels/native",
    "sov-mock-da/native",
    "sov-modules-api/native",
    "sov-sequencer-registry/native",
    "sov-state/native",
]
