// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::building {
    use dubhe::dapp_service::DappStorage;
    use ville::dapp_key;
    use ville::dapp_key::DappKey;
    use std::ascii::String;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const EWrongEntityId: vector<u8> = b"Wrong entity id";
    #[error]
    const ENoPermission: vector<u8> = b"Caller does not have permission";

    const TYPE_TAG: vector<u8> = b"building";

    // ─── Phantom marker type ───────────────────────────────────────────────
    /// Phantom type that distinguishes BuildingStorage from other ObjectStorage types
    /// at the Move compiler level, preserving compile-time type safety.
    /// All functions use ObjectStorage<Building> directly in their signatures.
    public struct Building has copy, drop {}

    // ─── ID / entity accessors ─────────────────────────────────────────────

    public fun entity_id(storage: &dubhe::dapp_service::ObjectStorage<Building>): vector<u8> {
        *dubhe::dapp_service::object_storage_entity_id(storage)
    }


    public fun assert_building_id(storage: &dubhe::dapp_service::ObjectStorage<Building>, expected: vector<u8>) {
        assert!(*dubhe::dapp_service::object_storage_entity_id(storage) == expected, EWrongEntityId);
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_kind(storage: &dubhe::dapp_service::ObjectStorage<Building>): u8 {
        dubhe::dapp_system::get_object_field<Building, u8>(storage, b"kind")
    }

    public(package) fun set_kind(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, value: u8) {
        dubhe::dapp_system::set_object_field<DappKey, Building, u8>(
            dapp_key::new(), storage, b"kind", value
        );
    }

    public fun get_name(storage: &dubhe::dapp_service::ObjectStorage<Building>): String {
        dubhe::dapp_system::get_object_field<Building, String>(storage, b"name")
    }

    public(package) fun set_name(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, value: String) {
        dubhe::dapp_system::set_object_field<DappKey, Building, String>(
            dapp_key::new(), storage, b"name", value
        );
    }

    public fun get_wage(storage: &dubhe::dapp_service::ObjectStorage<Building>): u64 {
        dubhe::dapp_system::get_object_field<Building, u64>(storage, b"wage")
    }

    public(package) fun set_wage(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, value: u64) {
        dubhe::dapp_system::set_object_field<DappKey, Building, u64>(
            dapp_key::new(), storage, b"wage", value
        );
    }

    public fun get_meal_price(storage: &dubhe::dapp_service::ObjectStorage<Building>): u64 {
        dubhe::dapp_system::get_object_field<Building, u64>(storage, b"meal_price")
    }

    public(package) fun set_meal_price(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, value: u64) {
        dubhe::dapp_system::set_object_field<DappKey, Building, u64>(
            dapp_key::new(), storage, b"meal_price", value
        );
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::ObjectStorage<Building>): u64 {
        if (dubhe::dapp_system::has_object_field<Building, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_object_field<Building, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, amount: u64) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_object_field<DappKey, Building, u64>(
            dapp_key::new(), storage, b"gold", current + amount
        );
    }

    public(package) fun sub_gold(storage: &mut dubhe::dapp_service::ObjectStorage<Building>, amount: u64) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_object_field<DappKey, Building, u64>(
            dapp_key::new(), storage, b"gold", current - amount
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────


    // ─── Lifecycle entry functions ─────────────────────────────────────────
    public(package) fun create_building(
        dapp_storage: &mut DappStorage,
        entity_id:    vector<u8>,
        ctx:          &mut TxContext,
    ) {
        assert!(ctx.sender() == dubhe::dapp_service::dapp_admin(dapp_storage), ENoPermission);
        dubhe::dapp_system::create_and_share_typed_object<DappKey, Building>(
            dapp_key::new(), dapp_storage, TYPE_TAG, entity_id, ctx
        );
    }

    public(package) fun destroy_building(
        dapp_storage: &mut DappStorage,
        storage:      dubhe::dapp_service::ObjectStorage<Building>,
        _ctx:         &TxContext,
    ) {
        dubhe::dapp_system::destroy_typed_object<DappKey, Building>(
            dapp_key::new(), dapp_storage, storage
        );
    }
}
