// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::card_kind {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum CardKind has copy, drop, store {
        Fireball,Heal,None,Shield,Strike
    }

    public fun new_fireball(): CardKind {
        CardKind::Fireball
    }

    public fun new_heal(): CardKind {
        CardKind::Heal
    }

    public fun new_none(): CardKind {
        CardKind::None
    }

    public fun new_shield(): CardKind {
        CardKind::Shield
    }

    public fun new_strike(): CardKind {
        CardKind::Strike
    }

    public fun encode(self: CardKind): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): CardKind {
        match(peel_enum_tag(bytes)) {
            0 => CardKind::Fireball,
            1 => CardKind::Heal,
            2 => CardKind::None,
            3 => CardKind::Shield,
            4 => CardKind::Strike,
            _ => abort,
        }
    }
}