// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::rarity {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum Rarity has copy, drop, store {
        Common,Epic,Rare
    }

    public fun new_common(): Rarity {
        Rarity::Common
    }

    public fun new_epic(): Rarity {
        Rarity::Epic
    }

    public fun new_rare(): Rarity {
        Rarity::Rare
    }

    public fun encode(self: Rarity): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): Rarity {
        match(peel_enum_tag(bytes)) {
            0 => Rarity::Common,
            1 => Rarity::Epic,
            2 => Rarity::Rare,
            _ => abort,
        }
    }
}