[package]
name = "sov-rest-utils"
description = "Utilities for building opinionated REST(ful) APIs according to the Sovereign SDK API guidelines"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
publish = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["query", "json", "original-uri"] }
derive_more = { workspace = true, default-features = true }
proptest = { workspace = true, features = ["std"], optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = "0.7"
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace", "compression-gzip", "propagate-header", "set-header"] }
tower-request-id = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
sov-rest-utils = { path = ".", features = ["arbitrary"] }

[features]
arbitrary = ["proptest", "proptest-derive", "sov-rest-utils/arbitrary"]
