// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::activity {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum Activity has copy, drop, store {
        Chatting,Eating,Idle,Sleeping,Wandering,Working
    }

    public fun new_chatting(): Activity {
        Activity::Chatting
    }

    public fun new_eating(): Activity {
        Activity::Eating
    }

    public fun new_idle(): Activity {
        Activity::Idle
    }

    public fun new_sleeping(): Activity {
        Activity::Sleeping
    }

    public fun new_wandering(): Activity {
        Activity::Wandering
    }

    public fun new_working(): Activity {
        Activity::Working
    }

    public fun encode(self: Activity): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): Activity {
        match(peel_enum_tag(bytes)) {
            0 => Activity::Chatting,
            1 => Activity::Eating,
            2 => Activity::Idle,
            3 => Activity::Sleeping,
            4 => Activity::Wandering,
            5 => Activity::Working,
            _ => abort,
        }
    }
}