// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::building_kind {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum BuildingKind has copy, drop, store {
        Cafe,Dock,Farm,None,Tavern,TownHall,Workshop
    }

    public fun new_cafe(): BuildingKind {
        BuildingKind::Cafe
    }

    public fun new_dock(): BuildingKind {
        BuildingKind::Dock
    }

    public fun new_farm(): BuildingKind {
        BuildingKind::Farm
    }

    public fun new_none(): BuildingKind {
        BuildingKind::None
    }

    public fun new_tavern(): BuildingKind {
        BuildingKind::Tavern
    }

    public fun new_townhall(): BuildingKind {
        BuildingKind::TownHall
    }

    public fun new_workshop(): BuildingKind {
        BuildingKind::Workshop
    }

    public fun encode(self: BuildingKind): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): BuildingKind {
        match(peel_enum_tag(bytes)) {
            0 => BuildingKind::Cafe,
            1 => BuildingKind::Dock,
            2 => BuildingKind::Farm,
            3 => BuildingKind::None,
            4 => BuildingKind::Tavern,
            5 => BuildingKind::TownHall,
            6 => BuildingKind::Workshop,
            _ => abort,
        }
    }
}