// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::event_kind {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum EventKind has copy, drop, store {
        MarketDay,Merchant,None,Storm
    }

    public fun new_marketday(): EventKind {
        EventKind::MarketDay
    }

    public fun new_merchant(): EventKind {
        EventKind::Merchant
    }

    public fun new_none(): EventKind {
        EventKind::None
    }

    public fun new_storm(): EventKind {
        EventKind::Storm
    }

    public fun encode(self: EventKind): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): EventKind {
        match(peel_enum_tag(bytes)) {
            0 => EventKind::MarketDay,
            1 => EventKind::Merchant,
            2 => EventKind::None,
            3 => EventKind::Storm,
            _ => abort,
        }
    }
}