// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::item_kind {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum ItemKind has copy, drop, store {
        Bread,Coffee,Craftwork,Fish,Flower,None
    }

    public fun new_bread(): ItemKind {
        ItemKind::Bread
    }

    public fun new_coffee(): ItemKind {
        ItemKind::Coffee
    }

    public fun new_craftwork(): ItemKind {
        ItemKind::Craftwork
    }

    public fun new_fish(): ItemKind {
        ItemKind::Fish
    }

    public fun new_flower(): ItemKind {
        ItemKind::Flower
    }

    public fun new_none(): ItemKind {
        ItemKind::None
    }

    public fun encode(self: ItemKind): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): ItemKind {
        match(peel_enum_tag(bytes)) {
            0 => ItemKind::Bread,
            1 => ItemKind::Coffee,
            2 => ItemKind::Craftwork,
            3 => ItemKind::Fish,
            4 => ItemKind::Flower,
            5 => ItemKind::None,
            _ => abort,
        }
    }
}