// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module ville::occupation {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum Occupation has copy, drop, store {
        Artisan,Barista,Farmer,Fisher,None
    }

    public fun new_artisan(): Occupation {
        Occupation::Artisan
    }

    public fun new_barista(): Occupation {
        Occupation::Barista
    }

    public fun new_farmer(): Occupation {
        Occupation::Farmer
    }

    public fun new_fisher(): Occupation {
        Occupation::Fisher
    }

    public fun new_none(): Occupation {
        Occupation::None
    }

    public fun encode(self: Occupation): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): Occupation {
        match(peel_enum_tag(bytes)) {
            0 => Occupation::Artisan,
            1 => Occupation::Barista,
            2 => Occupation::Farmer,
            3 => Occupation::Fisher,
            4 => Occupation::None,
            _ => abort,
        }
    }
}