[package]
name = "Kiosk"
version = "0.0.2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.68.1", override = true }

[addresses]
kiosk = "0x0"
