import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import {
  readPublishedToml,
  writePublishedToml,
  updatePublishedToml,
  clearPublishedTomlEntry,
  restorePublishedTomlEntry
} from '../src/utils/utils';

const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000000000000000000000000000';
const PKG_ID_1 = '0x1111111111111111111111111111111111111111111111111111111111111111';
const PKG_ID_2 = '0x2222222222222222222222222222222222222222222222222222222222222222';
const TESTNET_CHAIN_ID = '4c78adac';
const LOCALNET_CHAIN_ID = '31a2786f';

describe('readPublishedToml', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'published-toml-test-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should return empty object when Published.toml does not exist', () => {
    const result = readPublishedToml(tempDir);
    expect(result).toEqual({});
  });

  it('should parse a single environment entry', () => {
    const content = `# Generated by Move
# This file SHOULD be committed to source control

[published.testnet]
chain-id = "${TESTNET_CHAIN_ID}"
published-at = "${PKG_ID_1}"
original-id = "${PKG_ID_1}"
version = 1
`;
    fs.writeFileSync(path.join(tempDir, 'Published.toml'), content, 'utf-8');

    const result = readPublishedToml(tempDir);
    expect(result).toEqual({
      testnet: {
        chainId: TESTNET_CHAIN_ID,
        publishedAt: PKG_ID_1,
        originalId: PKG_ID_1,
        version: 1
      }
    });
  });

  it('should parse multiple environment entries', () => {
    const content = `# Generated by Move

[published.testnet]
chain-id = "${TESTNET_CHAIN_ID}"
published-at = "${PKG_ID_1}"
original-id = "${PKG_ID_1}"
version = 1

[published.localnet]
chain-id = "${LOCALNET_CHAIN_ID}"
published-at = "${PKG_ID_2}"
original-id = "${PKG_ID_2}"
version = 1
`;
    fs.writeFileSync(path.join(tempDir, 'Published.toml'), content, 'utf-8');

    const result = readPublishedToml(tempDir);
    expect(result.testnet?.chainId).toBe(TESTNET_CHAIN_ID);
    expect(result.testnet?.publishedAt).toBe(PKG_ID_1);
    expect(result.localnet?.chainId).toBe(LOCALNET_CHAIN_ID);
    expect(result.localnet?.publishedAt).toBe(PKG_ID_2);
  });

  it('should handle upgraded package (version > 1)', () => {
    const content = `[published.testnet]
chain-id = "${TESTNET_CHAIN_ID}"
published-at = "${PKG_ID_2}"
original-id = "${PKG_ID_1}"
version = 3
`;
    fs.writeFileSync(path.join(tempDir, 'Published.toml'), content, 'utf-8');

    const result = readPublishedToml(tempDir);
    expect(result.testnet?.publishedAt).toBe(PKG_ID_2);
    expect(result.testnet?.originalId).toBe(PKG_ID_1);
    expect(result.testnet?.version).toBe(3);
  });
});

describe('writePublishedToml', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'published-toml-test-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should create Published.toml with correct format', () => {
    writePublishedToml(tempDir, {
      testnet: {
        chainId: TESTNET_CHAIN_ID,
        publishedAt: PKG_ID_1,
        originalId: PKG_ID_1,
        version: 1
      }
    });

    const filePath = path.join(tempDir, 'Published.toml');
    expect(fs.existsSync(filePath)).toBe(true);

    const content = fs.readFileSync(filePath, 'utf-8');
    expect(content).toContain('[published.testnet]');
    expect(content).toContain(`chain-id = "${TESTNET_CHAIN_ID}"`);
    expect(content).toContain(`published-at = "${PKG_ID_1}"`);
    expect(content).toContain(`original-id = "${PKG_ID_1}"`);
    expect(content).toContain('version = 1');
  });

  it('should write multiple environments', () => {
    writePublishedToml(tempDir, {
      testnet: {
        chainId: TESTNET_CHAIN_ID,
        publishedAt: PKG_ID_1,
        originalId: PKG_ID_1,
        version: 1
      },
      localnet: {
        chainId: LOCALNET_CHAIN_ID,
        publishedAt: PKG_ID_2,
        originalId: PKG_ID_2,
        version: 1
      }
    });

    const content = fs.readFileSync(path.join(tempDir, 'Published.toml'), 'utf-8');
    expect(content).toContain('[published.testnet]');
    expect(content).toContain('[published.localnet]');
  });

  it('should overwrite existing Published.toml', () => {
    fs.writeFileSync(path.join(tempDir, 'Published.toml'), 'old content', 'utf-8');

    writePublishedToml(tempDir, {
      testnet: {
        chainId: TESTNET_CHAIN_ID,
        publishedAt: PKG_ID_1,
        originalId: PKG_ID_1,
        version: 1
      }
    });

    const content = fs.readFileSync(path.join(tempDir, 'Published.toml'), 'utf-8');
    expect(content).not.toContain('old content');
    expect(content).toContain('[published.testnet]');
  });

  it('should include header comment', () => {
    writePublishedToml(tempDir, {});
    const content = fs.readFileSync(path.join(tempDir, 'Published.toml'), 'utf-8');
    expect(content).toContain('# Generated by Move');
    expect(content).toContain('SHOULD be committed');
  });
});

describe('updatePublishedToml', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'published-toml-test-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should create Published.toml on first publish', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet).toEqual({
      chainId: TESTNET_CHAIN_ID,
      publishedAt: PKG_ID_1,
      originalId: PKG_ID_1,
      version: 1
    });
  });

  it('should add new environment without overwriting existing', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);
    updatePublishedToml(tempDir, 'localnet', LOCALNET_CHAIN_ID, PKG_ID_2, PKG_ID_2, 1);

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet?.publishedAt).toBe(PKG_ID_1);
    expect(entries.localnet?.publishedAt).toBe(PKG_ID_2);
  });

  it('should update existing environment on upgrade', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_2, PKG_ID_1, 2);

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet?.publishedAt).toBe(PKG_ID_2);
    expect(entries.testnet?.originalId).toBe(PKG_ID_1);
    expect(entries.testnet?.version).toBe(2);
  });

  it('should preserve originalId from first publish across upgrades', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_2, undefined, undefined);

    const entries = readPublishedToml(tempDir);
    // originalId should be preserved from first publish
    expect(entries.testnet?.originalId).toBe(PKG_ID_1);
    expect(entries.testnet?.publishedAt).toBe(PKG_ID_2);
  });
});

describe('clearPublishedTomlEntry', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'published-toml-test-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should return undefined when no Published.toml exists', () => {
    const result = clearPublishedTomlEntry(tempDir, 'testnet');
    expect(result).toBeUndefined();
  });

  it('should return undefined when environment does not exist', () => {
    updatePublishedToml(tempDir, 'localnet', LOCALNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);
    const result = clearPublishedTomlEntry(tempDir, 'testnet');
    expect(result).toBeUndefined();
  });

  it('should zero out published-at and original-id for upgrade build', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    clearPublishedTomlEntry(tempDir, 'testnet');

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet?.publishedAt).toBe(ZERO_ADDRESS);
    expect(entries.testnet?.originalId).toBe(ZERO_ADDRESS);
    expect(entries.testnet?.chainId).toBe(TESTNET_CHAIN_ID);
  });

  it('should return original entry so it can be restored', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    const original = clearPublishedTomlEntry(tempDir, 'testnet');

    expect(original).toEqual({
      chainId: TESTNET_CHAIN_ID,
      publishedAt: PKG_ID_1,
      originalId: PKG_ID_1,
      version: 1
    });
  });

  it('should not affect other environments when clearing one', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);
    updatePublishedToml(tempDir, 'localnet', LOCALNET_CHAIN_ID, PKG_ID_2, PKG_ID_2, 1);

    clearPublishedTomlEntry(tempDir, 'testnet');

    const entries = readPublishedToml(tempDir);
    expect(entries.localnet?.publishedAt).toBe(PKG_ID_2);
  });
});

describe('restorePublishedTomlEntry', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'published-toml-test-'));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('should restore a cleared entry after failed upgrade', () => {
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    const original = clearPublishedTomlEntry(tempDir, 'testnet')!;
    // Simulate: upgrade failed, restore
    restorePublishedTomlEntry(tempDir, 'testnet', original);

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet).toEqual(original);
  });

  it('should simulate full upgrade cycle: clear -> build -> restore/update', () => {
    // Initial publish
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_1, PKG_ID_1, 1);

    // Before upgrade build: clear
    const original = clearPublishedTomlEntry(tempDir, 'testnet')!;
    expect(original.publishedAt).toBe(PKG_ID_1);

    // After successful upgrade: update with new package ID
    updatePublishedToml(tempDir, 'testnet', TESTNET_CHAIN_ID, PKG_ID_2, original.originalId, 2);

    const entries = readPublishedToml(tempDir);
    expect(entries.testnet?.publishedAt).toBe(PKG_ID_2);
    expect(entries.testnet?.originalId).toBe(PKG_ID_1);
    expect(entries.testnet?.version).toBe(2);
  });
});
