[package]
name = "sov-chain-state"
authors = { workspace = true }
description = "A Sovereign SDK module for storing a rollup's historical state"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde = { workspace = true }
jsonrpsee = { workspace = true, features = ["client-core"], optional = true }
tracing = { workspace = true }
derivative = { workspace = true }

sov-modules-api = { workspace = true }
sov-state = { workspace = true }

[dev-dependencies]
sov-chain-state = { path = ".", features = ["native", "test-utils"] }
tempfile = { workspace = true }
sov-test-utils = { workspace = true }
sov-mock-da = { workspace = true }
sov-mock-zkvm = { workspace = true }
sov-modules-api = { workspace = true, features = ["test-utils"] }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }

[features]
default = []
test-utils = []
native = [
    "jsonrpsee",
    "sov-chain-state/native",
    "sov-mock-da/native",
    "sov-mock-zkvm/native",
    "sov-modules-api/native",
    "sov-state/native",
]
