// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module guild::dungeon_run {
    use sui::bag::{Self, Bag};
    use dubhe::dapp_service::{Self, DappStorage, UserStorage, SceneMetadata};
    use dubhe::dapp_system;
    use guild::dapp_key;
    use guild::dapp_key::DappKey;
    use sui::ed25519;
    use guild::pvp_match::{Self, PvpMatchStorage};

    // ─── Error constants ───────────────────────────────────────────────────
    const EFieldNotFound: u64 = 1;
    const EInsufficientAmount: u64 = 2;
    const EDuplicateItemId: u64 = 3;
    const ENotParticipant: u64 = 4;
    const ESceneExpired: u64 = 5;

    // ─── Struct definition ─────────────────────────────────────────────────
    /// Typed shared scene object for: dungeon_run.
    /// Embeds SceneMetadata used for reactive write authorization.
    public struct DungeonRunStorage has key {
        id:   sui::object::UID,
        meta: SceneMetadata,
        data: Bag,
    }


    /// Expose the embedded SceneMetadata for reactive writes and join/expire checks.
    public fun meta(storage: &DungeonRunStorage): &dubhe::dapp_service::SceneMetadata {
        &storage.meta
    }

    public(package) fun meta_mut(storage: &mut DungeonRunStorage): &mut dubhe::dapp_service::SceneMetadata {
        &mut storage.meta
    }

    public fun is_active(storage: &DungeonRunStorage, now_ms: u64): bool {
        dubhe::dapp_service::is_scene_active(&storage.meta, now_ms)
    }

    public fun is_participant(storage: &DungeonRunStorage, addr: address): bool {
        dubhe::dapp_service::is_scene_participant(&storage.meta, addr)
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_floor(storage: &DungeonRunStorage): u32 {
        assert!(sui::bag::contains(&storage.data, b"floor"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, u32>(&storage.data, b"floor")
    }

    public(package) fun set_floor(storage: &mut DungeonRunStorage, value: u32) {
        if (sui::bag::contains(&storage.data, b"floor")) {
            *sui::bag::borrow_mut<vector<u8>, u32>(&mut storage.data, b"floor") = value;
        } else {
            sui::bag::add(&mut storage.data, b"floor", value);
        }
    }

    public fun get_boss_id(storage: &DungeonRunStorage): u64 {
        assert!(sui::bag::contains(&storage.data, b"boss_id"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"boss_id")
    }

    public(package) fun set_boss_id(storage: &mut DungeonRunStorage, value: u64) {
        if (sui::bag::contains(&storage.data, b"boss_id")) {
            *sui::bag::borrow_mut<vector<u8>, u64>(&mut storage.data, b"boss_id") = value;
        } else {
            sui::bag::add(&mut storage.data, b"boss_id", value);
        }
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &DungeonRunStorage): u64 {
        if (sui::bag::contains(&storage.data, b"gold")) {
            *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut DungeonRunStorage, amount: u64) {
        if (sui::bag::contains(&storage.data, b"gold")) {
            let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
            *current = *current + amount;
        } else {
            sui::bag::add(&mut storage.data, b"gold", amount);
        }
    }

    public(package) fun sub_gold(storage: &mut DungeonRunStorage, amount: u64) {
        assert!(sui::bag::contains(&storage.data, b"gold"), EInsufficientAmount);
        let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
        assert!(*current >= amount, EInsufficientAmount);
        *current = *current - amount;
    }

    public fun get_loot(storage: &DungeonRunStorage): u64 {
        if (sui::bag::contains(&storage.data, b"loot")) {
            *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"loot")
        } else { 0 }
    }

    public(package) fun add_loot(storage: &mut DungeonRunStorage, amount: u64) {
        if (sui::bag::contains(&storage.data, b"loot")) {
            let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"loot");
            *current = *current + amount;
        } else {
            sui::bag::add(&mut storage.data, b"loot", amount);
        }
    }

    public(package) fun sub_loot(storage: &mut DungeonRunStorage, amount: u64) {
        assert!(sui::bag::contains(&storage.data, b"loot"), EInsufficientAmount);
        let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"loot");
        assert!(*current >= amount, EInsufficientAmount);
        *current = *current - amount;
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer loot (fungible) from pvp_match into this dungeon_run.
    public(package) fun transfer_pvp_match_to_dungeon_run_loot(
        from:   &mut PvpMatchStorage,
        to:     &mut DungeonRunStorage,
        amount: u64,
    ) {
        pvp_match::sub_loot(from, amount);
        add_loot(to, amount);
    }

    // ─── Scene lifecycle entry functions ───────────────────────────────────

    /// Create a scene with off-chain multi-sig consent from all n participants.
    public entry fun create_dungeon_run_with_consent(
        dapp_storage: &mut DappStorage,
        participants: vector<address>,
        sigs:         vector<vector<u8>>,
        pubkeys:      vector<vector<u8>>,
        nonce:        u64,
        expires_at:   u64,
        ctx:          &mut TxContext,
    ) {
        dapp_system::consume_nonce<DappKey>(dapp_key::new(), dapp_storage, nonce);
        assert!(ctx.epoch_timestamp_ms() <= expires_at, ESceneExpired);

        let msg = encode_consent_msg(&participants, nonce, expires_at);
        let n = participants.length();
        assert!(sigs.length() == n, 0);
        assert!(pubkeys.length() == n, 0);

        let mut i = 0;
        while (i < n) {
            let pk  = *pubkeys.borrow(i);
            let sig = *sigs.borrow(i);
            assert!(ed25519::ed25519_verify(&sig, &pk, &msg), ENotParticipant);
            i = i + 1;
        };

        let scene = DungeonRunStorage {
            id:   sui::object::new(ctx),
            meta: dapp_system::new_scene_meta(
                participants,
                std::option::some(expires_at),
            ),
            data: bag::new(ctx),
        };
        sui::transfer::share_object(scene);
    }

    /// Dynamically join an open scene (no consent needed — scene must not have expired).
    public entry fun join_dungeon_run(
        storage: &mut DungeonRunStorage,
        ctx:     &mut TxContext,
    ) {
        assert!(dapp_service::is_scene_active(&storage.meta, ctx.epoch_timestamp_ms()), ESceneExpired);
        dapp_service::add_scene_participant(&mut storage.meta, ctx.sender());
    }

    /// Expire and destroy a scene once its deadline has passed.
    /// The scene's Bag must be empty before this can succeed.
    public entry fun expire_dungeon_run(
        storage: DungeonRunStorage,
        ctx:     &TxContext,
    ) {
        assert!(!dapp_service::is_scene_active(&storage.meta, ctx.epoch_timestamp_ms()), ESceneExpired);
        let DungeonRunStorage { id, meta: _, data } = storage;
        bag::destroy_empty(data);
        sui::object::delete(id);
    }

    // ─── Internal helpers ──────────────────────────────────────────────────

    fun encode_consent_msg(participants: &vector<address>, nonce: u64, expires_at: u64): vector<u8> {
        let mut msg = vector::empty<u8>();
        let p_bytes = sui::bcs::to_bytes(participants);
        let n_bytes = sui::bcs::to_bytes(&nonce);
        let e_bytes = sui::bcs::to_bytes(&expires_at);
        msg.append(p_bytes);
        msg.append(n_bytes);
        msg.append(e_bytes);
        msg
    }
}
