// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module guild::dungeon_run {
    use sui::bag::{Self, Bag};
    use dubhe::dapp_service::{Self, SceneMetadata};
    use dubhe::dapp_system;
    use guild::dapp_key;
    use guild::dapp_key::DappKey;
    use guild::pvp_match::{Self, PvpMatchStorage};

    // ─── Error constants ───────────────────────────────────────────────────
        #[error]
    const EFieldNotFound: vector<u8> = b"Field not found";
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const ESceneExpired: vector<u8> = b"Scene has expired";
    #[error]
    const ESceneNotExpiredYet: vector<u8> = b"Scene is still active and cannot be destroyed yet";

    // ─── Struct definition ─────────────────────────────────────────────────
    /// Typed shared scene object for: dungeon_run.
    /// Embeds SceneMetadata used for reactive write authorization.
    public struct DungeonRunStorage has key {
        id:   sui::object::UID,
        meta: SceneMetadata,
        data: Bag,
    }


    /// Expose the embedded SceneMetadata for reactive writes and join/expire checks.
    public fun meta(storage: &DungeonRunStorage): &dubhe::dapp_service::SceneMetadata {
        &storage.meta
    }

    public(package) fun meta_mut(storage: &mut DungeonRunStorage): &mut dubhe::dapp_service::SceneMetadata {
        &mut storage.meta
    }

    public fun is_active(storage: &DungeonRunStorage, now_ms: u64): bool {
        dubhe::dapp_service::is_scene_active(&storage.meta, now_ms)
    }

    public fun is_participant(storage: &DungeonRunStorage, addr: address): bool {
        dubhe::dapp_service::is_scene_participant(&storage.id, addr)
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_floor(storage: &DungeonRunStorage): u32 {
        assert!(sui::bag::contains(&storage.data, b"floor"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, u32>(&storage.data, b"floor")
    }

    public(package) fun set_floor(storage: &mut DungeonRunStorage, value: u32) {
        if (sui::bag::contains(&storage.data, b"floor")) {
            *sui::bag::borrow_mut<vector<u8>, u32>(&mut storage.data, b"floor") = value;
        } else {
            sui::bag::add(&mut storage.data, b"floor", value);
        }
    }

    public fun get_boss_id(storage: &DungeonRunStorage): u64 {
        assert!(sui::bag::contains(&storage.data, b"boss_id"), EFieldNotFound);
        *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"boss_id")
    }

    public(package) fun set_boss_id(storage: &mut DungeonRunStorage, value: u64) {
        if (sui::bag::contains(&storage.data, b"boss_id")) {
            *sui::bag::borrow_mut<vector<u8>, u64>(&mut storage.data, b"boss_id") = value;
        } else {
            sui::bag::add(&mut storage.data, b"boss_id", value);
        }
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &DungeonRunStorage): u64 {
        if (sui::bag::contains(&storage.data, b"gold")) {
            *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut DungeonRunStorage, amount: u64) {
        if (sui::bag::contains(&storage.data, b"gold")) {
            let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
            *current = *current + amount;
        } else {
            sui::bag::add(&mut storage.data, b"gold", amount);
        }
    }

    public(package) fun sub_gold(storage: &mut DungeonRunStorage, amount: u64) {
        assert!(sui::bag::contains(&storage.data, b"gold"), EInsufficientAmount);
        let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"gold");
        assert!(*current >= amount, EInsufficientAmount);
        *current = *current - amount;
    }

    public fun get_loot(storage: &DungeonRunStorage): u64 {
        if (sui::bag::contains(&storage.data, b"loot")) {
            *sui::bag::borrow<vector<u8>, u64>(&storage.data, b"loot")
        } else { 0 }
    }

    public(package) fun add_loot(storage: &mut DungeonRunStorage, amount: u64) {
        if (sui::bag::contains(&storage.data, b"loot")) {
            let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"loot");
            *current = *current + amount;
        } else {
            sui::bag::add(&mut storage.data, b"loot", amount);
        }
    }

    public(package) fun sub_loot(storage: &mut DungeonRunStorage, amount: u64) {
        assert!(sui::bag::contains(&storage.data, b"loot"), EInsufficientAmount);
        let current: &mut u64 = sui::bag::borrow_mut(&mut storage.data, b"loot");
        assert!(*current >= amount, EInsufficientAmount);
        *current = *current - amount;
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer loot (fungible) from pvp_match into this dungeon_run.
    public(package) fun transfer_pvp_match_to_dungeon_run_loot(
        from:   &mut PvpMatchStorage,
        to:     &mut DungeonRunStorage,
        amount: u64,
    ) {
        pvp_match::sub_loot(from, amount);
        add_loot(to, amount);
    }

    // ─── Scene lifecycle entry functions ───────────────────────────────────

    /// Create an open scene without consent signatures.
    /// participants can be empty — use join_dungeon_run to add dynamically.
    /// expires_at is optional: pass none() for a scene that never auto-expires.
    /// max_participants caps the participant list size; pass none() for unlimited.
    /// Access control (e.g. admin-only) must be enforced in the calling system function.
    public fun create_dungeon_run(
        participants:     vector<address>,
        expires_at:       std::option::Option<u64>,
        max_participants: std::option::Option<u64>,
        ctx:              &mut TxContext,
    ) {
        let mut id = sui::object::new(ctx);
        let meta = dapp_system::init_scene_meta(&mut id, participants, expires_at, max_participants);
        let scene = DungeonRunStorage { id, meta, data: bag::new(ctx) };
        sui::transfer::share_object(scene);
    }

    /// Create a scene with an invitation list — supports ALL Sui wallet types
    /// including zkLogin, multisig, Passkey, and Ed25519.
    ///
    /// Each invitee must call accept_dungeon_run from their own wallet to confirm.
    /// The scene becomes usable for reactive writes only after a participant has
    /// accepted.  Invitations optionally expire at invites_expire_at (epoch ms).
    /// The scene itself optionally expires at scene_expires_at.
    /// max_participants caps how many invitees may be accepted; pass none() for unlimited.
    public fun create_dungeon_run_with_invitations(
        invitees:          vector<address>,
        invites_expire_at: std::option::Option<u64>,
        scene_expires_at:  std::option::Option<u64>,
        max_participants:  std::option::Option<u64>,
        ctx:               &mut TxContext,
    ) {
        let scene = DungeonRunStorage {
            id:   sui::object::new(ctx),
            meta: dapp_system::new_scene_meta_with_invitations(
                invitees,
                invites_expire_at,
                scene_expires_at,
                max_participants,
            ),
            data: bag::new(ctx),
        };
        sui::transfer::share_object(scene);
    }

    /// Accept an invitation to this scene.
    ///
    /// The caller (ctx.sender()) must be in the invitees list and the invitation
    /// window must not have expired.  On success the caller is moved from the
    /// invitees list to the confirmed participants list (DF) and may participate
    /// in reactive writes.
    ///
    /// Because auth is handled by Sui's native transaction signing, this works
    /// for ALL wallet types: Ed25519, Secp256k1, Secp256r1 (Passkey), and zkLogin.
    public fun accept_dungeon_run(
        storage: &mut DungeonRunStorage,
        ctx:     &TxContext,
    ) {
        dapp_system::accept_scene_invitation<DappKey>(
            dapp_key::new(), &mut storage.id, &mut storage.meta, ctx
        );
    }

    /// Dynamically join an open scene.
    ///
    /// NOTE: This is intentionally public(package), consistent with leave_dungeon_run.
    /// DApp system functions should add their own admission guard logic (e.g. check
    /// registration, payment, or whitelist) before calling this.
    public(package) fun join_dungeon_run(
        storage: &mut DungeonRunStorage,
        ctx:     &TxContext,
    ) {
        assert!(dapp_service::is_scene_active(&storage.meta, ctx.epoch_timestamp_ms()), ESceneExpired);
        dapp_service::add_scene_participant(&mut storage.id, &mut storage.meta, ctx.sender());
    }

    /// Leave this scene voluntarily — removes the caller from the participant list.
    ///
    /// NOTE: This is intentionally public(package) to prevent griefing (e.g. a
    /// player rage-quitting mid-match to block reactive writes). DApp system
    /// functions should add guard logic (e.g. only allow leaving during a lobby
    /// phase) before calling this.
    public(package) fun leave_dungeon_run(
        storage: &mut DungeonRunStorage,
        ctx:     &TxContext,
    ) {
        dapp_service::remove_scene_participant(&mut storage.id, &mut storage.meta, ctx.sender());
    }

    /// Expire and destroy a scene once its deadline has passed.
    /// The scene's Bag must be empty before this can succeed.
    ///
    /// IMPORTANT — Dynamic Field cleanup:
    /// Participant membership is stored as Dynamic Fields on the scene's UID.
    /// Calling this function while participants remain will orphan those DFs
    /// (their storage rebate cannot be recovered).
    ///
    /// Recommended usage:
    ///   - Small/competitive scenes (PvP, dungeon runs): ensure all participants
    ///     have called leave_dungeon_run before expiring to reclaim storage rebate.
    ///   - Large open-world or long-lived scenes: skip expiry altogether.
    ///     Expired scenes are completely inert (reactive writes abort, join aborts)
    ///     and safe to leave on-chain indefinitely.
    public fun expire_dungeon_run(
        storage: DungeonRunStorage,
        ctx:     &TxContext,
    ) {
        assert!(!dapp_service::is_scene_active(&storage.meta, ctx.epoch_timestamp_ms()), ESceneNotExpiredYet);
        let DungeonRunStorage { id, meta: _, data } = storage;
        bag::destroy_empty(data);
        sui::object::delete(id);
    }
}
