// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module guild::pvp_match {
    use dubhe::dapp_service::{Self, DappStorage};
    use guild::dapp_key;
    use guild::dapp_key::DappKey;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const ESceneExpired: vector<u8> = b"Scene has expired";
    #[error]
    const ESceneNotExpiredYet: vector<u8> = b"Scene is still active and cannot be destroyed yet";

    const SCENE_TYPE: vector<u8> = b"pvp_match";

    // ─── Phantom marker type ───────────────────────────────────────────────
    /// Phantom type that distinguishes this scene from others at compile time.
    /// All functions use SceneStorage<PvpMatch> directly in their signatures.
    public struct PvpMatch has copy, drop {}

    // ─── SceneMetadata helpers ─────────────────────────────────────────────

    public fun meta(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): &dubhe::dapp_service::SceneMetadata {
        dubhe::dapp_service::scene_storage_meta(storage)
    }

    public fun is_active(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>, now_ms: u64): bool {
        dubhe::dapp_service::is_scene_active(dubhe::dapp_service::scene_storage_meta(storage), now_ms)
    }

    public fun is_participant(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>, addr: address): bool {
        dubhe::dapp_service::is_participant_in_scene_storage(storage, addr)
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_round(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u32 {
        dubhe::dapp_system::get_scene_field<PvpMatch, u32>(storage, b"round")
    }

    public(package) fun set_round(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>, value: u32) {
        dubhe::dapp_system::set_scene_field<DappKey, PvpMatch, u32>(
            dapp_key::new(), storage, b"round", value
        );
    }

    public fun get_map_id(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u64 {
        dubhe::dapp_system::get_scene_field<PvpMatch, u64>(storage, b"map_id")
    }

    public(package) fun set_map_id(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>, value: u64) {
        dubhe::dapp_system::set_scene_field<DappKey, PvpMatch, u64>(
            dapp_key::new(), storage, b"map_id", value
        );
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_loot(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u64 {
        if (dubhe::dapp_system::has_scene_field<PvpMatch, u64>(storage, b"loot")) {
            dubhe::dapp_system::get_scene_field<PvpMatch, u64>(storage, b"loot")
        } else { 0 }
    }

    public(package) fun add_loot(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>, amount: u64) {
        let current = get_loot(storage);
        dubhe::dapp_system::set_scene_field<DappKey, PvpMatch, u64>(
            dapp_key::new(), storage, b"loot", current + amount
        );
    }

    public(package) fun sub_loot(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>, amount: u64) {
        let current = get_loot(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, PvpMatch, u64>(
            dapp_key::new(), storage, b"loot", current - amount
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────


    // ─── Scene lifecycle entry functions ───────────────────────────────────

    /// Create an open scene.
    /// participants can be empty — use join_pvp_match to add dynamically.
    /// expires_at is optional: pass none() for a scene that never auto-expires.
    /// max_participants caps the participant list size; pass none() for unlimited.
    public fun create_pvp_match(
        dapp_storage:     &DappStorage,
        participants:     vector<address>,
        expires_at:       std::option::Option<u64>,
        max_participants: std::option::Option<u64>,
        ctx:              &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene<DappKey, PvpMatch>(
            dapp_key::new(), dapp_storage, SCENE_TYPE, participants, expires_at, max_participants, ctx
        );
    }

    /// Create a scene with an invitation list — supports ALL Sui wallet types
    /// including zkLogin, multisig, Passkey, and Ed25519.
    ///
    /// Each invitee must call accept_pvp_match from their own wallet to confirm.
    public fun create_pvp_match_with_invitations(
        dapp_storage:      &DappStorage,
        invitees:          vector<address>,
        invites_expire_at: std::option::Option<u64>,
        scene_expires_at:  std::option::Option<u64>,
        max_participants:  std::option::Option<u64>,
        ctx:               &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_invitations<DappKey, PvpMatch>(
            dapp_key::new(), dapp_storage, SCENE_TYPE, invitees, invites_expire_at, scene_expires_at, max_participants, ctx
        );
    }

    /// Accept an invitation to this scene.
    ///
    /// The caller (ctx.sender()) must be in the invitees list and the invitation
    /// window must not have expired.
    public fun accept_pvp_match(
        storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        ctx:     &TxContext,
    ) {
        dubhe::dapp_system::accept_typed_scene_invitation<DappKey, PvpMatch>(
            dapp_key::new(), storage, ctx
        );
    }

    /// Dynamically join an open scene.
    ///
    /// NOTE: public(package) — DApp system functions should add admission guards
    /// (registration check, payment, whitelist) before calling this.
    public(package) fun join_pvp_match(
        storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        ctx:     &TxContext,
    ) {
        assert!(
            dapp_service::is_scene_active(dapp_service::scene_storage_meta(storage), ctx.epoch_timestamp_ms()),
            ESceneExpired
        );
        dubhe::dapp_system::join_typed_scene<PvpMatch>(storage, ctx);
    }

    /// Leave this scene voluntarily.
    ///
    /// NOTE: public(package) to prevent griefing. DApp system functions should
    /// add guard logic before calling this.
    public(package) fun leave_pvp_match(
        storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        ctx:     &TxContext,
    ) {
        dubhe::dapp_system::leave_typed_scene<PvpMatch>(storage, ctx);
    }

    /// Expire and destroy a scene once its deadline has passed.
    /// The scene's Bag must be empty before this can succeed.
    ///
    /// IMPORTANT — Dynamic Field cleanup:
    /// Participant membership is stored as Dynamic Fields on the scene's UID.
    /// Calling this function while participants remain will orphan those DFs
    /// (their storage rebate cannot be recovered).
    ///
    /// Recommended usage:
    ///   - Small/competitive scenes (PvP, dungeon runs): ensure all participants
    ///     have called leave_pvp_match before expiring to reclaim storage rebate.
    ///   - Large open-world or long-lived scenes: skip expiry altogether.
    ///     Expired scenes are completely inert (reactive writes abort, join aborts)
    ///     and safe to leave on-chain indefinitely.
    public fun expire_pvp_match(
        storage: dubhe::dapp_service::SceneStorage<PvpMatch>,
        ctx:     &TxContext,
    ) {
        assert!(
            !dapp_service::is_scene_active(dapp_service::scene_storage_meta(&storage), ctx.epoch_timestamp_ms()),
            ESceneNotExpiredYet
        );
        dubhe::dapp_system::destroy_typed_scene<DappKey, PvpMatch>(dapp_key::new(), storage);
    }
}
