// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module guild::pvp_match {
    use dubhe::dapp_service::DappStorage;
    use guild::dapp_key;
    use guild::dapp_key::DappKey;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";

    const SCENE_TYPE: vector<u8> = b"pvp_match";

    /// Phantom type that distinguishes this scene storage at compile time.
    public struct PvpMatch has copy, drop {}

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_round(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u32 {
        dubhe::dapp_system::get_scene_field<PvpMatch, u32>(storage, b"round")
    }

    public(package) fun set_round(
        permit:       &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u32,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch, u32>(
            dapp_key::new(), permit, storage, user_storage, b"round", value, ctx
        );
    }

    public(package) fun remove_round_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>): u32 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, PvpMatch, u32>(
            dapp_key::new(), storage, b"round"
        )
    }

    public fun get_map_id(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u64 {
        dubhe::dapp_system::get_scene_field<PvpMatch, u64>(storage, b"map_id")
    }

    public(package) fun set_map_id(
        permit:       &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch, u64>(
            dapp_key::new(), permit, storage, user_storage, b"map_id", value, ctx
        );
    }

    public(package) fun remove_map_id_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, PvpMatch, u64>(
            dapp_key::new(), storage, b"map_id"
        )
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_loot(storage: &dubhe::dapp_service::SceneStorage<PvpMatch>): u64 {
        if (dubhe::dapp_system::has_scene_field<PvpMatch, u64>(storage, b"loot")) {
            dubhe::dapp_system::get_scene_field<PvpMatch, u64>(storage, b"loot")
        } else { 0 }
    }

    public(package) fun add_loot(
        permit:  &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_loot(storage);
        dubhe::dapp_system::set_scene_field<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch, u64>(
            dapp_key::new(), permit, storage, user_storage, b"loot", current + amount, ctx
        );
    }

    public(package) fun sub_loot(
        permit:  &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<PvpMatch>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_loot(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch, u64>(
            dapp_key::new(), permit, storage, user_storage, b"loot", current - amount, ctx
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────


    // ─── SceneStorage lifecycle wrappers ──────────────────────────────────

    public(package) fun new_pvp_match_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        ctx:          &mut TxContext,
    ): dubhe::dapp_service::SceneStorage<PvpMatch> {
        dubhe::dapp_system::new_typed_scene_with_permit<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        )
    }

    public(package) fun create_pvp_match_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<guild::pvp_match_permit::PvpMatchPermit>,
        ctx:          &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_permit<DappKey, guild::pvp_match_permit::PvpMatchPermit, PvpMatch>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        );
    }

    public(package) fun share_pvp_match(storage: dubhe::dapp_service::SceneStorage<PvpMatch>) {
        dubhe::dapp_system::share_scene_storage<DappKey, PvpMatch>(
            dapp_key::new(), storage
        );
    }

    public(package) fun destroy_pvp_match(storage: dubhe::dapp_service::SceneStorage<PvpMatch>) {
        dubhe::dapp_system::destroy_typed_scene<DappKey, PvpMatch>(
            dapp_key::new(), storage
        );
    }
}
