  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component2 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"component2";
    const OFFCHAIN: bool = false;

    public fun has(dapp_hub: &DappHub, resource_account: String, player_id: u32): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player_id));
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String, player_id: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player_id));
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String, player_id: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player_id));
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String, player_id: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player_id));
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, player_id: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player_id));
        let value_tuple = vector::empty();
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }
}