  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component12 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::direction;
    use example::direction::{Direction};

    const TABLE_NAME: vector<u8> = b"component12";
    const OFFCHAIN: bool = false;

    public struct Component12 has copy, drop, store {
        player: address,
        value: u32,
    }

    public fun new(player: address, value: u32): Component12 {
        Component12 {
            player,
            value,
        }
    }

    public fun player(self: &Component12): address {
        self.player
    }

    public fun value(self: &Component12): u32 {
        self.value
    }

    public fun update_player(self: &mut Component12, player: address) {
        self.player = player
    }

    public fun update_value(self: &mut Component12, value: u32) {
        self.value = value
    }

    public fun has(user_storage: &UserStorage, direction: Direction): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, direction: Direction) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, direction: Direction) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, direction: Direction, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"player", b"value"], ctx);
    }

    public fun get_player(user_storage: &UserStorage, direction: Direction): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        player
    }

    public(package) fun set_player(user_storage: &mut UserStorage, direction: Direction, player: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let value = to_bytes(&player);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"player", value, ctx);
    }

    public fun get_value(user_storage: &UserStorage, direction: Direction): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        value
    }

    public(package) fun set_value(user_storage: &mut UserStorage, direction: Direction, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let value = to_bytes(&value);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"value", value, ctx);
    }

    public fun get(user_storage: &UserStorage, direction: Direction): (address, u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        (player, value)
    }

    public(package) fun set(user_storage: &mut UserStorage, direction: Direction, player: address, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let field_names = vector[b"player", b"value"];
        let value_tuple = encode(player, value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, direction: Direction): Component12 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        Component12 { player, value }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, direction: Direction, component12: Component12, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&direction));
        let field_names = vector[b"player", b"value"];
        let value_tuple = encode_struct(component12);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(player: address, value: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&player));
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }

    public fun encode_struct(component12: Component12): vector<vector<u8>> {
        encode(component12.player, component12.value)
    }

    public fun decode(data: vector<u8>): Component12 {
        let mut bsc_type = sui::bcs::new(data);
        let player = sui::bcs::peel_address(&mut bsc_type);
        let value = sui::bcs::peel_u32(&mut bsc_type);
        Component12 {
            player,
            value,
        }
    }
}