  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component14 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::direction;
    use example::direction::{Direction};

    const TABLE_NAME: vector<u8> = b"component14";
    const OFFCHAIN: bool = true;

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, value: Direction, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = encode(value);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(value: Direction): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(example::direction::encode(value));
        value_tuple
    }
}