// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module example::component34 {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"component34";
    const OFFCHAIN: bool = false;

    public struct Component34 has copy, drop, store {
        name: vector<String>,
        age: u8,
    }

    public fun new(name: vector<String>, age: u8): Component34 {
        Component34 {
            name,
            age,
        }
    }

    public fun name(self: &Component34): vector<String> {
        self.name
    }

    public fun age(self: &Component34): u8 {
        self.age
    }

    public fun update_name(self: &mut Component34, name: vector<String>) {
        self.name = name
    }

    public fun update_age(self: &mut Component34, age: u8) {
        self.age = age
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"name", b"age"], ctx);
    }

    public fun get_name(user_storage: &UserStorage): vector<String> {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        name
    }

    public(package) fun set_name(dapp_hub: &DappHub, user_storage: &mut UserStorage, name: vector<String>, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&name);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"name", value, ctx);
    }

    public fun get_age(user_storage: &UserStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u8(&mut age_bcs);
        age
    }

    public(package) fun set_age(dapp_hub: &DappHub, user_storage: &mut UserStorage, age: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&age);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"age", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (vector<String>, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u8(&mut age_bcs);
        (name, age)
    }

    public(package) fun set(dapp_hub: &DappHub, user_storage: &mut UserStorage, name: vector<String>, age: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"name", b"age"];
        let value_tuple = encode(name, age);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): Component34 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u8(&mut age_bcs);
        Component34 { name, age }
    }

    public(package) fun set_struct(dapp_hub: &DappHub, user_storage: &mut UserStorage, component34: Component34, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"name", b"age"];
        let value_tuple = encode_struct(component34);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(name: vector<String>, age: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&name));
        value_tuple.push_back(to_bytes(&age));
        value_tuple
    }

    public fun encode_struct(component34: Component34): vector<vector<u8>> {
        encode(component34.name, component34.age)
    }

    public fun decode(data: vector<u8>): Component34 {
        let mut bcs_type = sui::bcs::new(data);
        let name = dubhe::bcs::peel_vec_string(&mut bcs_type);
        let age = sui::bcs::peel_u8(&mut bcs_type);
        Component34 {
            name,
            age,
        }
    }
}