  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component6 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"component6";
    const OFFCHAIN: bool = false;

    public struct Component6 has copy, drop, store {
        attack: u32,
        hp: u32,
    }

    public fun new(attack: u32, hp: u32): Component6 {
        Component6 {
            attack,
            hp,
        }
    }

    public fun attack(self: &Component6): u32 {
        self.attack
    }

    public fun hp(self: &Component6): u32 {
        self.hp
    }

    public fun update_attack(self: &mut Component6, attack: u32) {
        self.attack = attack
    }

    public fun update_hp(self: &mut Component6, hp: u32) {
        self.hp = hp
    }

    public fun has(dapp_hub: &DappHub, resource_account: String): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public fun get_attack(dapp_hub: &DappHub, resource_account: String): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let attack = sui::bcs::peel_u32(&mut bsc_type);
        attack
    }

    public(package) fun set_attack(dapp_hub: &mut DappHub, resource_account: String, attack: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&attack);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 0, value, ctx);
    }

    public fun get_hp(dapp_hub: &DappHub, resource_account: String): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 1);
        let mut bsc_type = sui::bcs::new(value);
        let hp = sui::bcs::peel_u32(&mut bsc_type);
        hp
    }

    public(package) fun set_hp(dapp_hub: &mut DappHub, resource_account: String, hp: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&hp);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 1, value, ctx);
    }

    public fun get(dapp_hub: &DappHub, resource_account: String): (u32, u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        let mut bsc_type = sui::bcs::new(value_tuple);
        let attack = sui::bcs::peel_u32(&mut bsc_type);
        let hp = sui::bcs::peel_u32(&mut bsc_type);
        (attack, hp)
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, attack: u32, hp: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = encode(attack, hp);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_hub: &DappHub, resource_account: String): Component6 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        decode(value_tuple)
    }

    public(package) fun set_struct(dapp_hub: &mut DappHub, resource_account: String, component6: Component6, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = encode_struct(component6);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(attack: u32, hp: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&attack));
        value_tuple.push_back(to_bytes(&hp));
        value_tuple
    }

    public fun encode_struct(component6: Component6): vector<vector<u8>> {
        encode(component6.attack, component6.hp)
    }

    public fun decode(data: vector<u8>): Component6 {
        let mut bsc_type = sui::bcs::new(data);
        let attack = sui::bcs::peel_u32(&mut bsc_type);
        let hp = sui::bcs::peel_u32(&mut bsc_type);
        Component6 {
            attack,
            hp,
        }
    }
}