// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module example::component11 {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::direction;
    use example::direction::{Direction};

    const TABLE_NAME: vector<u8> = b"component11";
    const OFFCHAIN: bool = false;

    public struct Component11 has copy, drop, store {
        value: u32,
        direction: Direction,
    }

    public fun new(value: u32, direction: Direction): Component11 {
        Component11 {
            value,
            direction,
        }
    }

    public fun value(self: &Component11): u32 {
        self.value
    }

    public fun direction(self: &Component11): Direction {
        self.direction
    }

    public fun update_value(self: &mut Component11, value: u32) {
        self.value = value
    }

    public fun update_direction(self: &mut Component11, direction: Direction) {
        self.direction = direction
    }

    public fun has(user_storage: &UserStorage, player: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, player: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"value", b"direction"], ctx);
    }

    public fun get_value(user_storage: &UserStorage, player: address): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        value
    }

    public(package) fun set_value(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value = to_bytes(&value);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"value", value, ctx);
    }

    public fun get_direction(user_storage: &UserStorage, player: address): Direction {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let direction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"direction");
        let mut direction_bcs = sui::bcs::new(direction_raw);
        let direction = example::direction::decode(&mut direction_bcs);
        direction
    }

    public(package) fun set_direction(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, direction: Direction, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value = example::direction::encode(direction);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"direction", value, ctx);
    }

    public fun get(user_storage: &UserStorage, player: address): (u32, Direction) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        let direction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"direction");
        let mut direction_bcs = sui::bcs::new(direction_raw);
        let direction = example::direction::decode(&mut direction_bcs);
        (value, direction)
    }

    public(package) fun set(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, value: u32, direction: Direction, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let field_names = vector[b"value", b"direction"];
        let value_tuple = encode(value, direction);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, player: address): Component11 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        let direction_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"direction");
        let mut direction_bcs = sui::bcs::new(direction_raw);
        let direction = example::direction::decode(&mut direction_bcs);
        Component11 { value, direction }
    }

    public(package) fun set_struct(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, component11: Component11, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let field_names = vector[b"value", b"direction"];
        let value_tuple = encode_struct(component11);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: u32, direction: Direction): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple.push_back(example::direction::encode(direction));
        value_tuple
    }

    public fun encode_struct(component11: Component11): vector<vector<u8>> {
        encode(component11.value, component11.direction)
    }

    public fun decode(data: vector<u8>): Component11 {
        let mut bcs_type = sui::bcs::new(data);
        let value = sui::bcs::peel_u32(&mut bcs_type);
        let direction = example::direction::decode(&mut bcs_type);
        Component11 {
            value,
            direction,
        }
    }
}