  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::component4 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"component4";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage, player: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, player: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"value"], ctx);
    }

    public fun get(user_storage: &UserStorage, player: address): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"value");
        let mut value_bcs = sui::bcs::new(value_raw);
        let value = sui::bcs::peel_u32(&mut value_bcs);
        value
    }

    public(package) fun set(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let field_names = vector[b"value"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }
}