// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::game_config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"game_config";
    const OFFCHAIN: bool = false;

    public struct GameConfig has copy, drop, store {
        max_players: u32,
        season: u32,
    }

    public fun new(max_players: u32, season: u32): GameConfig {
        GameConfig {
            max_players,
            season,
        }
    }

    public fun max_players(self: &GameConfig): u32 {
        self.max_players
    }

    public fun season(self: &GameConfig): u32 {
        self.season
    }

    public fun update_max_players(self: &mut GameConfig, max_players: u32) {
        self.max_players = max_players
    }

    public fun update_season(self: &mut GameConfig, season: u32) {
        self.season = season
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"max_players", b"season"]);
    }

    public fun get_max_players(dapp_storage: &DappStorage): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let max_players_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_players");
        let mut max_players_bcs = sui::bcs::new(max_players_raw);
        let max_players = sui::bcs::peel_u32(&mut max_players_bcs);
        max_players
    }

    public(package) fun set_max_players(dapp_storage: &mut DappStorage, max_players: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&max_players);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"max_players", value);
    }

    public fun get_season(dapp_storage: &DappStorage): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let season_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season");
        let mut season_bcs = sui::bcs::new(season_raw);
        let season = sui::bcs::peel_u32(&mut season_bcs);
        season
    }

    public(package) fun set_season(dapp_storage: &mut DappStorage, season: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&season);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"season", value);
    }

    public fun get(dapp_storage: &DappStorage): (u32, u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let max_players_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_players");
        let mut max_players_bcs = sui::bcs::new(max_players_raw);
        let max_players = sui::bcs::peel_u32(&mut max_players_bcs);
        let season_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season");
        let mut season_bcs = sui::bcs::new(season_raw);
        let season = sui::bcs::peel_u32(&mut season_bcs);
        (max_players, season)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, max_players: u32, season: u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"max_players", b"season"];
        let value_tuple = encode(max_players, season);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): GameConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let max_players_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"max_players");
        let mut max_players_bcs = sui::bcs::new(max_players_raw);
        let max_players = sui::bcs::peel_u32(&mut max_players_bcs);
        let season_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season");
        let mut season_bcs = sui::bcs::new(season_raw);
        let season = sui::bcs::peel_u32(&mut season_bcs);
        GameConfig { max_players, season }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, game_config: GameConfig) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"max_players", b"season"];
        let value_tuple = encode_struct(game_config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(max_players: u32, season: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&max_players));
        value_tuple.push_back(to_bytes(&season));
        value_tuple
    }

    public fun encode_struct(game_config: GameConfig): vector<vector<u8>> {
        encode(game_config.max_players, game_config.season)
    }

    public fun decode(data: vector<u8>): GameConfig {
        let mut bcs_type = sui::bcs::new(data);
        let max_players = sui::bcs::peel_u32(&mut bcs_type);
        let season = sui::bcs::peel_u32(&mut bcs_type);
        GameConfig {
            max_players,
            season,
        }
    }
}