// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::gold {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"gold";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"amount"], ctx);
    }

    public fun get(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let value = sui::bcs::peel_u64(&mut amount_bcs);
        value
    }

    public(package) fun set(user_storage: &mut UserStorage, value: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"amount"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }


    // ─── fungible add / sub ─────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";

    public(package) fun add(user_storage: &mut UserStorage, amount: u64, ctx: &mut TxContext) {
        let current = if (has(user_storage)) { get(user_storage) } else { 0 };
        set(user_storage, current + amount, ctx);
    }

    public(package) fun sub(user_storage: &mut UserStorage, amount: u64, ctx: &mut TxContext) {
        let current = get(user_storage);
        assert!(current >= amount, EInsufficientAmount);
        set(user_storage, current - amount, ctx);
    }

    // ─── transferable: User ↔ VaultStorage (fungible) ─────────────
    public(package) fun transfer_user_to_vault(
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::ObjectStorage<example::vault::Vault>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        example::vault::add_gold(target, amount);
    }

    public(package) fun transfer_vault_to_user(
        source: &mut dubhe::dapp_service::ObjectStorage<example::vault::Vault>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        example::vault::sub_gold(source, amount);
        add(user, amount, ctx);
    }

    // ─── transferable: User ↔ ArenaStorage (fungible) ──────────
    public(package) fun transfer_user_to_arena(
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::SceneStorage<example::arena::Arena>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        example::arena::add_gold(target, amount);
    }

    // ★ No expiry check on withdraw direction — prevents asset lock-in expired scenes.
    public(package) fun transfer_arena_to_user(
        source: &mut dubhe::dapp_service::SceneStorage<example::arena::Arena>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        example::arena::sub_gold(source, amount);
        add(user, amount, ctx);
    }

    // ─── transferable: User ↔ DungeonStorage (fungible) ──────────
    public(package) fun transfer_user_to_dungeon(
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::SceneStorage<example::dungeon::Dungeon>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        example::dungeon::add_gold(target, amount);
    }

    // ★ No expiry check on withdraw direction — prevents asset lock-in expired scenes.
    public(package) fun transfer_dungeon_to_user(
        source: &mut dubhe::dapp_service::SceneStorage<example::dungeon::Dungeon>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        example::dungeon::sub_gold(source, amount);
        add(user, amount, ctx);
    }
}