  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource8 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"resource8";
    const OFFCHAIN: bool = false;

    public struct Resource8 has copy, drop, store {
        player: address,
        name: String,
    }

    public fun new(player: address, name: String): Resource8 {
        Resource8 {
            player,
            name,
        }
    }

    public fun player(self: &Resource8): address {
        self.player
    }

    public fun name(self: &Resource8): String {
        self.name
    }

    public fun update_player(self: &mut Resource8, player: address) {
        self.player = player
    }

    public fun update_name(self: &mut Resource8, name: String) {
        self.name = name
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"player", b"name"], ctx);
    }

    public fun get_player(user_storage: &UserStorage): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        player
    }

    public(package) fun set_player(user_storage: &mut UserStorage, player: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&player);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"player", value, ctx);
    }

    public fun get_name(user_storage: &UserStorage): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        name
    }

    public(package) fun set_name(user_storage: &mut UserStorage, name: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&into_bytes(name));
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"name", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (address, String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        (player, name)
    }

    public(package) fun set(user_storage: &mut UserStorage, player: address, name: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"player", b"name"];
        let value_tuple = encode(player, name);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): Resource8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let player_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"player");
        let mut player_bcs = sui::bcs::new(player_raw);
        let player = sui::bcs::peel_address(&mut player_bcs);
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_string(&mut name_bcs);
        Resource8 { player, name }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, resource8: Resource8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"player", b"name"];
        let value_tuple = encode_struct(resource8);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(player: address, name: String): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&player));
        value_tuple.push_back(to_bytes(&into_bytes(name)));
        value_tuple
    }

    public fun encode_struct(resource8: Resource8): vector<vector<u8>> {
        encode(resource8.player, resource8.name)
    }

    public fun decode(data: vector<u8>): Resource8 {
        let mut bsc_type = sui::bcs::new(data);
        let player = sui::bcs::peel_address(&mut bsc_type);
        let name = string(sui::bcs::peel_vec_u8(&mut bsc_type));
        Resource8 {
            player,
            name,
        }
    }
}