// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module example::resource9 {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"resource9";
    const OFFCHAIN: bool = false;

    public struct Resource9 has copy, drop, store {
        name: vector<String>,
        age: u32,
    }

    public fun new(name: vector<String>, age: u32): Resource9 {
        Resource9 {
            name,
            age,
        }
    }

    public fun name(self: &Resource9): vector<String> {
        self.name
    }

    public fun age(self: &Resource9): u32 {
        self.age
    }

    public fun update_name(self: &mut Resource9, name: vector<String>) {
        self.name = name
    }

    public fun update_age(self: &mut Resource9, age: u32) {
        self.age = age
    }

    public fun has(user_storage: &UserStorage, player: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, player: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, player: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"name", b"age"], ctx);
    }

    public fun get_name(user_storage: &UserStorage, player: address): vector<String> {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        name
    }

    public(package) fun set_name(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, name: vector<String>, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value = to_bytes(&name);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"name", value, ctx);
    }

    public fun get_age(user_storage: &UserStorage, player: address): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u32(&mut age_bcs);
        age
    }

    public(package) fun set_age(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, age: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let value = to_bytes(&age);
        dapp_system::set_field<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, b"age", value, ctx);
    }

    public fun get(user_storage: &UserStorage, player: address): (vector<String>, u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u32(&mut age_bcs);
        (name, age)
    }

    public(package) fun set(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, name: vector<String>, age: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let field_names = vector[b"name", b"age"];
        let value_tuple = encode(name, age);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, player: address): Resource9 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let name_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"name");
        let mut name_bcs = sui::bcs::new(name_raw);
        let name = dubhe::bcs::peel_vec_string(&mut name_bcs);
        let age_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"age");
        let mut age_bcs = sui::bcs::new(age_raw);
        let age = sui::bcs::peel_u32(&mut age_bcs);
        Resource9 { name, age }
    }

    public(package) fun set_struct(dapp_hub: &DappHub, user_storage: &mut UserStorage, player: address, resource9: Resource9, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&player));
        let field_names = vector[b"name", b"age"];
        let value_tuple = encode_struct(resource9);
        dapp_system::set_record<DappKey>(dapp_key::new(), dapp_hub, user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(name: vector<String>, age: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&name));
        value_tuple.push_back(to_bytes(&age));
        value_tuple
    }

    public fun encode_struct(resource9: Resource9): vector<vector<u8>> {
        encode(resource9.name, resource9.age)
    }

    public fun decode(data: vector<u8>): Resource9 {
        let mut bcs_type = sui::bcs::new(data);
        let name = dubhe::bcs::peel_vec_string(&mut bcs_type);
        let age = sui::bcs::peel_u32(&mut bcs_type);
        Resource9 {
            name,
            age,
        }
    }
}