  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module example::resource1 { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use example::dapp_key;
    use example::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"resource1";
    const OFFCHAIN: bool = false;

    public struct Resource1 has copy, drop, store {
        player: address,
        value: u32,
    }

    public fun new(player: address, value: u32): Resource1 {
        Resource1 {
            player,
            value,
        }
    }

    public fun player(self: &Resource1): address {
        self.player
    }

    public fun value(self: &Resource1): u32 {
        self.value
    }

    public fun update_player(self: &mut Resource1, player: address) {
        self.player = player
    }

    public fun update_value(self: &mut Resource1, value: u32) {
        self.value = value
    }

    public fun has(dapp_hub: &DappHub, resource_account: String): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public fun get_player(dapp_hub: &DappHub, resource_account: String): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let player = sui::bcs::peel_address(&mut bsc_type);
        player
    }

    public(package) fun set_player(dapp_hub: &mut DappHub, resource_account: String, player: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&player);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 0, value, ctx);
    }

    public fun get_value(dapp_hub: &DappHub, resource_account: String): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 1);
        let mut bsc_type = sui::bcs::new(value);
        let value = sui::bcs::peel_u32(&mut bsc_type);
        value
    }

    public(package) fun set_value(dapp_hub: &mut DappHub, resource_account: String, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&value);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 1, value, ctx);
    }

    public fun get(dapp_hub: &DappHub, resource_account: String): (address, u32) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        let mut bsc_type = sui::bcs::new(value_tuple);
        let player = sui::bcs::peel_address(&mut bsc_type);
        let value = sui::bcs::peel_u32(&mut bsc_type);
        (player, value)
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, player: address, value: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = encode(player, value);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_hub: &DappHub, resource_account: String): Resource1 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        decode(value_tuple)
    }

    public(package) fun set_struct(dapp_hub: &mut DappHub, resource_account: String, resource1: Resource1, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value_tuple = encode_struct(resource1);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(player: address, value: u32): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&player));
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }

    public fun encode_struct(resource1: Resource1): vector<vector<u8>> {
        encode(resource1.player, resource1.value)
    }

    public fun decode(data: vector<u8>): Resource1 {
        let mut bsc_type = sui::bcs::new(data);
        let player = sui::bcs::peel_address(&mut bsc_type);
        let value = sui::bcs::peel_u32(&mut bsc_type);
        Resource1 {
            player,
            value,
        }
    }
}