  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::proxy_config { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappStorage};
    use dubhe::dapp_system;
    use dubhe::dapp_key;
    use dubhe::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"proxy_config";
    const OFFCHAIN: bool = false;

    public struct ProxyConfig has copy, drop, store {
        owner: String,
        expires_at: u64,
    }

    public fun new(owner: String, expires_at: u64): ProxyConfig {
        ProxyConfig {
            owner,
            expires_at,
        }
    }

    public fun owner(self: &ProxyConfig): String {
        self.owner
    }

    public fun expires_at(self: &ProxyConfig): u64 {
        self.expires_at
    }

    public fun update_owner(self: &mut ProxyConfig, owner: String) {
        self.owner = owner
    }

    public fun update_expires_at(self: &mut ProxyConfig, expires_at: u64) {
        self.expires_at = expires_at
    }

    public fun has(dapp_storage: &DappStorage, dapp_key: String, account: String): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage, dapp_key: String, account: String) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        dapp_service::delete_global_record<DappKey>(dapp_storage, key_tuple, vector[b"owner", b"expires_at"]);
    }

    public fun get_owner(dapp_storage: &DappStorage, dapp_key: String, account: String): String {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let owner_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = dubhe::bcs::peel_string(&mut owner_bcs);
        owner
    }

    public(package) fun set_owner(dapp_storage: &mut DappStorage, dapp_key: String, account: String, owner: String, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let value = to_bytes(&into_bytes(owner));
        dapp_service::set_global_field<DappKey>(dapp_storage, key_tuple, b"owner", value);
    }

    public fun get_expires_at(dapp_storage: &DappStorage, dapp_key: String, account: String): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let expires_at_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        expires_at
    }

    public(package) fun set_expires_at(dapp_storage: &mut DappStorage, dapp_key: String, account: String, expires_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let value = to_bytes(&expires_at);
        dapp_service::set_global_field<DappKey>(dapp_storage, key_tuple, b"expires_at", value);
    }

    public fun get(dapp_storage: &DappStorage, dapp_key: String, account: String): (String, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let owner_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = dubhe::bcs::peel_string(&mut owner_bcs);
        let expires_at_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        (owner, expires_at)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, dapp_key: String, account: String, owner: String, expires_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let field_names = vector[b"owner", b"expires_at"];
        let value_tuple = encode(owner, expires_at);
        dapp_service::set_global_record<DappKey>(dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_storage: &DappStorage, dapp_key: String, account: String): ProxyConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let owner_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"owner");
        let mut owner_bcs = sui::bcs::new(owner_raw);
        let owner = dubhe::bcs::peel_string(&mut owner_bcs);
        let expires_at_raw = dapp_service::get_global_field<DappKey>(dapp_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        ProxyConfig { owner, expires_at }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, dapp_key: String, account: String, proxy_config: ProxyConfig, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&dapp_key));
        key_tuple.push_back(to_bytes(&account));
        let field_names = vector[b"owner", b"expires_at"];
        let value_tuple = encode_struct(proxy_config);
        dapp_service::set_global_record<DappKey>(dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(owner: String, expires_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&into_bytes(owner)));
        value_tuple.push_back(to_bytes(&expires_at));
        value_tuple
    }

    public fun encode_struct(proxy_config: ProxyConfig): vector<vector<u8>> {
        encode(proxy_config.owner, proxy_config.expires_at)
    }

    public fun decode(data: vector<u8>): ProxyConfig {
        let mut bsc_type = sui::bcs::new(data);
        let owner = string(sui::bcs::peel_vec_u8(&mut bsc_type));
        let expires_at = sui::bcs::peel_u64(&mut bsc_type);
        ProxyConfig {
            owner,
            expires_at,
        }
    }
}