// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
#[allow(unused_use)]

/* Autogenerated file. Do not edit manually. */

module guild::weapon {
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, UserStorage};
    use dubhe::dapp_system;
    use guild::dapp_key;
    use guild::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"weapon";
    const OFFCHAIN: bool = false;

    public struct Weapon has copy, drop, store {
        damage: u32,
        rarity: u8,
    }

    public fun new(damage: u32, rarity: u8): Weapon {
        Weapon {
            damage,
            rarity,
        }
    }

    public fun damage(self: &Weapon): u32 {
        self.damage
    }

    public fun rarity(self: &Weapon): u8 {
        self.rarity
    }

    public fun update_damage(self: &mut Weapon, damage: u32) {
        self.damage = damage
    }

    public fun update_rarity(self: &mut Weapon, rarity: u8) {
        self.rarity = rarity
    }

    public fun has(user_storage: &UserStorage, item_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, item_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, item_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, item_id: u64, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"damage", b"rarity"], ctx);
    }

    public fun get_damage(user_storage: &UserStorage, item_id: u64): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let damage_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage");
        let mut damage_bcs = sui::bcs::new(damage_raw);
        let damage = sui::bcs::peel_u32(&mut damage_bcs);
        damage
    }

    public(package) fun set_damage(user_storage: &mut UserStorage, item_id: u64, damage: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let value = to_bytes(&damage);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"damage", value, ctx);
    }

    public fun get_rarity(user_storage: &UserStorage, item_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        rarity
    }

    public(package) fun set_rarity(user_storage: &mut UserStorage, item_id: u64, rarity: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let value = to_bytes(&rarity);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"rarity", value, ctx);
    }

    public fun get(user_storage: &UserStorage, item_id: u64): (u32, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let damage_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage");
        let mut damage_bcs = sui::bcs::new(damage_raw);
        let damage = sui::bcs::peel_u32(&mut damage_bcs);
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        (damage, rarity)
    }

    public(package) fun set(user_storage: &mut UserStorage, item_id: u64, damage: u32, rarity: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let field_names = vector[b"damage", b"rarity"];
        let value_tuple = encode(damage, rarity);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, item_id: u64): Weapon {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let damage_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage");
        let mut damage_bcs = sui::bcs::new(damage_raw);
        let damage = sui::bcs::peel_u32(&mut damage_bcs);
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        Weapon { damage, rarity }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, item_id: u64, weapon: Weapon, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&item_id));
        let field_names = vector[b"damage", b"rarity"];
        let value_tuple = encode_struct(weapon);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(damage: u32, rarity: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&damage));
        value_tuple.push_back(to_bytes(&rarity));
        value_tuple
    }

    public fun encode_struct(weapon: Weapon): vector<vector<u8>> {
        encode(weapon.damage, weapon.rarity)
    }

    public fun decode(data: vector<u8>): Weapon {
        let mut bcs_type = sui::bcs::new(data);
        let damage = sui::bcs::peel_u32(&mut bcs_type);
        let rarity = sui::bcs::peel_u8(&mut bcs_type);
        Weapon {
            damage,
            rarity,
        }
    }


    // ─── unique: mint with auto-generated item_id ───────────────────────
    public(package) fun mint(
        user_storage: &mut UserStorage,
        damage: u32, rarity: u8,
        ctx: &mut TxContext,
    ): u64 {
        let addr = ctx.fresh_object_address();
        let item_id = (sui::address::to_u256(addr) & 0xFFFFFFFFFFFFFFFF as u256) as u64;
        ensure_has_not(user_storage, item_id);
        set(user_storage, item_id, damage, rarity, ctx);
        item_id
    }

    // ─── transferable: User ↔ GuildStorage (unique) ────────────────────
    public(package) fun transfer_user_to_guild(
        user:     &mut UserStorage,
        target:   &mut guild::guild::GuildStorage,
        item_id: u64,
        ctx:      &mut TxContext,
    ) {
        ensure_has(user, item_id);
        let data = encode_struct(get_struct(user, item_id));
        delete(user, item_id, ctx);
        let raw: vector<u8> = sui::bcs::to_bytes(&data);
        guild::guild::set_weapon_data(target, item_id, raw);
    }

    public(package) fun transfer_guild_to_user(
        source:   &mut guild::guild::GuildStorage,
        user:     &mut UserStorage,
        item_id: u64,
        ctx:      &mut TxContext,
    ) {
        let raw = guild::guild::remove_weapon_data(source, item_id);
        let decoded = decode(raw);
        set_struct(user, item_id, decoded, ctx);
    }

    // ─── listable: market protocol (unique) ────────────────────────────
    public entry fun list(
        user_storage: &mut UserStorage,
        item_id:   u64,
        price:        u64,
        listed_until: std::option::Option<u64>,
        ctx:          &mut TxContext,
    ) {
        let mut record_key = vector::empty();
        record_key.push_back(TABLE_NAME);
        record_key.push_back(sui::bcs::to_bytes(&item_id));
        dubhe::dapp_system::take_record<DappKey>(
            dapp_key::new(),
            user_storage,
            b"weapon",
            record_key,
            vector[b"damage", b"rarity"],
            price,
            0,
            listed_until,
            ctx,
        );
    }

    public entry fun buy(
        listing:      dubhe::dapp_service::Listing,
        user_storage: &mut UserStorage,
        payment:      sui::coin::Coin<sui::sui::SUI>,
        ctx:          &mut TxContext,
    ) {
        let price = dubhe::dapp_service::listing_price(&listing);
        assert!(sui::coin::value(&payment) >= price, 0);
        let seller = dubhe::dapp_service::listing_seller(&listing);
        sui::transfer::public_transfer(payment, seller);
        dubhe::dapp_system::restore_record<DappKey>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public entry fun cancel_listing(
        listing:      dubhe::dapp_service::Listing,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::restore_record<DappKey>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public entry fun expire_listing(
        listing:      dubhe::dapp_service::Listing,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::expire_listing<DappKey>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }
}