// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::dungeon {
    use dubhe::dapp_service::DappStorage;
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::arena;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EFieldNotFound: vector<u8> = b"Field not found";
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const EDuplicateItemId: vector<u8> = b"Duplicate item id";

    const SCENE_TYPE: vector<u8> = b"dungeon";

    /// Phantom type that distinguishes this scene storage at compile time.
    public struct Dungeon has copy, drop {}

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_floor(storage: &dubhe::dapp_service::SceneStorage<Dungeon>): u32 {
        dubhe::dapp_system::get_scene_field<Dungeon, u32>(storage, b"floor")
    }

    public(package) fun set_floor(
        permit:       &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u32,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, example::dungeon_permit::DungeonPermit, Dungeon, u32>(
            dapp_key::new(), permit, storage, user_storage, b"floor", value, ctx
        );
    }

    public(package) fun remove_floor_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>): u32 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Dungeon, u32>(
            dapp_key::new(), storage, b"floor"
        )
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::SceneStorage<Dungeon>): u64 {
        if (dubhe::dapp_system::has_scene_field<Dungeon, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_scene_field<Dungeon, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(
        permit:  &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_scene_field<DappKey, example::dungeon_permit::DungeonPermit, Dungeon, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current + amount, ctx
        );
    }

    public(package) fun sub_gold(
        permit:  &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, example::dungeon_permit::DungeonPermit, Dungeon, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current - amount, ctx
        );
    }

    public fun has_sword(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64): bool {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key)
    }

    public fun get_sword_data(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::get_scene_field<Dungeon, vector<u8>>(storage, key)
    }

    public(package) fun set_sword_data(
        permit:  &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        item_id: u64,
        data:    vector<u8>,
        ctx:     &TxContext,
    ) {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(!dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key), EDuplicateItemId);
        dubhe::dapp_system::set_scene_field<DappKey, example::dungeon_permit::DungeonPermit, Dungeon, vector<u8>>(
            dapp_key::new(), permit, storage, user_storage, key, data, ctx
        );
    }

    public(package) fun remove_sword_data(
        permit:  &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        item_id: u64,
        ctx:     &TxContext,
    ): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key), EFieldNotFound);
        dubhe::dapp_system::remove_scene_field<DappKey, example::dungeon_permit::DungeonPermit, Dungeon, vector<u8>>(
            dapp_key::new(), permit, storage, user_storage, key, ctx
        )
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    public(package) fun transfer_arena_to_dungeon_gold(
        source_permit: &dubhe::dapp_service::ScenePermit<example::arena_permit::ArenaPermit>,
        dest_permit: &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        from:   &mut dubhe::dapp_service::SceneStorage<example::arena::Arena>,
        to:     &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount: u64,
        ctx:         &TxContext,
    ) {
        arena::sub_gold(source_permit, from, user_storage, amount, ctx);
        add_gold(dest_permit, to, user_storage, amount, ctx);
    }

    // ─── SceneStorage lifecycle wrappers ──────────────────────────────────

    public(package) fun new_dungeon_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        ctx:          &mut TxContext,
    ): dubhe::dapp_service::SceneStorage<Dungeon> {
        dubhe::dapp_system::new_typed_scene_with_permit<DappKey, example::dungeon_permit::DungeonPermit, Dungeon>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        )
    }

    public(package) fun create_dungeon_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<example::dungeon_permit::DungeonPermit>,
        ctx:          &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_permit<DappKey, example::dungeon_permit::DungeonPermit, Dungeon>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        );
    }

    public(package) fun share_dungeon(storage: dubhe::dapp_service::SceneStorage<Dungeon>) {
        dubhe::dapp_system::share_scene_storage<DappKey, Dungeon>(
            dapp_key::new(), storage
        );
    }

    public(package) fun destroy_dungeon(storage: dubhe::dapp_service::SceneStorage<Dungeon>) {
        dubhe::dapp_system::destroy_typed_scene<DappKey, Dungeon>(
            dapp_key::new(), storage
        );
    }
}
