// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module example::dungeon {
    use dubhe::dapp_service::{Self, DappStorage};
    use example::dapp_key;
    use example::dapp_key::DappKey;
    use example::arena;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EFieldNotFound: vector<u8> = b"Field not found";
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";
    #[error]
    const EDuplicateItemId: vector<u8> = b"Duplicate item id";
    #[error]
    const ESceneExpired: vector<u8> = b"Scene has expired";
    #[error]
    const ESceneNotExpiredYet: vector<u8> = b"Scene is still active and cannot be destroyed yet";

    const SCENE_TYPE: vector<u8> = b"dungeon";

    // ─── Phantom marker type ───────────────────────────────────────────────
    /// Phantom type that distinguishes this scene from others at compile time.
    /// All functions use SceneStorage<Dungeon> directly in their signatures.
    public struct Dungeon has copy, drop {}

    // ─── SceneMetadata helpers ─────────────────────────────────────────────

    public fun meta(storage: &dubhe::dapp_service::SceneStorage<Dungeon>): &dubhe::dapp_service::SceneMetadata {
        dubhe::dapp_service::scene_storage_meta(storage)
    }

    public fun is_active(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, now_ms: u64): bool {
        dubhe::dapp_service::is_scene_active(dubhe::dapp_service::scene_storage_meta(storage), now_ms)
    }

    public fun is_participant(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, addr: address): bool {
        dubhe::dapp_service::is_participant_in_scene_storage(storage, addr)
    }

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_floor(storage: &dubhe::dapp_service::SceneStorage<Dungeon>): u32 {
        dubhe::dapp_system::get_scene_field<Dungeon, u32>(storage, b"floor")
    }

    public(package) fun set_floor(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>, value: u32) {
        dubhe::dapp_system::set_scene_field<DappKey, Dungeon, u32>(
            dapp_key::new(), storage, b"floor", value
        );
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::SceneStorage<Dungeon>): u64 {
        if (dubhe::dapp_system::has_scene_field<Dungeon, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_scene_field<Dungeon, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>, amount: u64) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_scene_field<DappKey, Dungeon, u64>(
            dapp_key::new(), storage, b"gold", current + amount
        );
    }

    public(package) fun sub_gold(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>, amount: u64) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, Dungeon, u64>(
            dapp_key::new(), storage, b"gold", current - amount
        );
    }

    public fun has_sword(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64): bool {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key)
    }

    public fun get_sword_data(storage: &dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        dubhe::dapp_system::get_scene_field<Dungeon, vector<u8>>(storage, key)
    }

    public(package) fun set_sword_data(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64, data: vector<u8>) {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(!dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key), EDuplicateItemId);
        dubhe::dapp_system::set_scene_field<DappKey, Dungeon, vector<u8>>(
            dapp_key::new(), storage, key, data
        );
    }

    public(package) fun remove_sword_data(storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>, item_id: u64): vector<u8> {
        let key = sui::bcs::to_bytes(&item_id);
        assert!(dubhe::dapp_system::has_scene_field<Dungeon, vector<u8>>(storage, key), EFieldNotFound);
        dubhe::dapp_system::remove_scene_field<DappKey, Dungeon, vector<u8>>(dapp_key::new(), storage, key)
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────

    /// Transfer gold (fungible) from arena into this dungeon.
    public(package) fun transfer_arena_to_dungeon_gold(
        from:   &mut dubhe::dapp_service::SceneStorage<example::arena::Arena>,
        to:     &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        amount: u64,
    ) {
        arena::sub_gold(from, amount);
        add_gold(to, amount);
    }

    // ─── Scene lifecycle entry functions ───────────────────────────────────

    /// Create an open scene.
    /// participants can be empty — use join_dungeon to add dynamically.
    /// expires_at is optional: pass none() for a scene that never auto-expires.
    /// max_participants caps the participant list size; pass none() for unlimited.
    public fun create_dungeon(
        dapp_storage:     &DappStorage,
        participants:     vector<address>,
        expires_at:       std::option::Option<u64>,
        max_participants: std::option::Option<u64>,
        ctx:              &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene<DappKey, Dungeon>(
            dapp_key::new(), dapp_storage, SCENE_TYPE, participants, expires_at, max_participants, ctx
        );
    }

    /// Create a scene with an invitation list — supports ALL Sui wallet types
    /// including zkLogin, multisig, Passkey, and Ed25519.
    ///
    /// Each invitee must call accept_dungeon from their own wallet to confirm.
    public fun create_dungeon_with_invitations(
        dapp_storage:      &DappStorage,
        invitees:          vector<address>,
        invites_expire_at: std::option::Option<u64>,
        scene_expires_at:  std::option::Option<u64>,
        max_participants:  std::option::Option<u64>,
        ctx:               &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_invitations<DappKey, Dungeon>(
            dapp_key::new(), dapp_storage, SCENE_TYPE, invitees, invites_expire_at, scene_expires_at, max_participants, ctx
        );
    }

    /// Accept an invitation to this scene.
    ///
    /// The caller (ctx.sender()) must be in the invitees list and the invitation
    /// window must not have expired.
    public fun accept_dungeon(
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        ctx:     &TxContext,
    ) {
        dubhe::dapp_system::accept_typed_scene_invitation<DappKey, Dungeon>(
            dapp_key::new(), storage, ctx
        );
    }

    /// Dynamically join an open scene.
    ///
    /// NOTE: public(package) — DApp system functions should add admission guards
    /// (registration check, payment, whitelist) before calling this.
    public(package) fun join_dungeon(
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        ctx:     &TxContext,
    ) {
        assert!(
            dapp_service::is_scene_active(dapp_service::scene_storage_meta(storage), ctx.epoch_timestamp_ms()),
            ESceneExpired
        );
        dubhe::dapp_system::join_typed_scene<Dungeon>(storage, ctx);
    }

    /// Leave this scene voluntarily.
    ///
    /// NOTE: public(package) to prevent griefing. DApp system functions should
    /// add guard logic before calling this.
    public(package) fun leave_dungeon(
        storage: &mut dubhe::dapp_service::SceneStorage<Dungeon>,
        ctx:     &TxContext,
    ) {
        dubhe::dapp_system::leave_typed_scene<Dungeon>(storage, ctx);
    }

    /// Expire and destroy a scene once its deadline has passed.
    /// The scene's Bag must be empty before this can succeed.
    ///
    /// IMPORTANT — Dynamic Field cleanup:
    /// Participant membership is stored as Dynamic Fields on the scene's UID.
    /// Calling this function while participants remain will orphan those DFs
    /// (their storage rebate cannot be recovered).
    ///
    /// Recommended usage:
    ///   - Small/competitive scenes (PvP, dungeon runs): ensure all participants
    ///     have called leave_dungeon before expiring to reclaim storage rebate.
    ///   - Large open-world or long-lived scenes: skip expiry altogether.
    ///     Expired scenes are completely inert (reactive writes abort, join aborts)
    ///     and safe to leave on-chain indefinitely.
    public fun expire_dungeon(
        storage: dubhe::dapp_service::SceneStorage<Dungeon>,
        ctx:     &TxContext,
    ) {
        assert!(
            !dapp_service::is_scene_active(dapp_service::scene_storage_meta(&storage), ctx.epoch_timestamp_ms()),
            ESceneNotExpiredYet
        );
        dubhe::dapp_system::destroy_typed_scene<DappKey, Dungeon>(dapp_key::new(), storage);
    }
}
