[package]
name = "Dubhe"
edition = "2024.alpha"
published-at = "0xf0334377b345bf2775672b0ccca08820308f20ffca1d3aff82b5b32c87fb28bc"
 license = "MIT"
 authors = ["Obelisk Labs"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.36.2" }

[addresses]
dubhe = "0xf0334377b345bf2775672b0ccca08820308f20ffca1d3aff82b5b32c87fb28bc"
#dubhe = "0x0"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

