// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::brawl {
    use dubhe::dapp_service::DappStorage;
    use card_duel::dapp_key;
    use card_duel::dapp_key::DappKey;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";

    const SCENE_TYPE: vector<u8> = b"brawl";

    /// Phantom type that distinguishes this scene storage at compile time.
    public struct Brawl has copy, drop {}

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_host(storage: &dubhe::dapp_service::SceneStorage<Brawl>): address {
        dubhe::dapp_system::get_scene_field<Brawl, address>(storage, b"host")
    }

    public(package) fun set_host(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, address>(
            dapp_key::new(), permit, storage, user_storage, b"host", value, ctx
        );
    }

    public(package) fun remove_host_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, address>(
            dapp_key::new(), storage, b"host"
        )
    }

    public fun get_entry_fee(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::get_scene_field<Brawl, u64>(storage, b"entry_fee")
    }

    public(package) fun set_entry_fee(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"entry_fee", value, ctx
        );
    }

    public(package) fun remove_entry_fee_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u64>(
            dapp_key::new(), storage, b"entry_fee"
        )
    }

    public fun get_max_players(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::get_scene_field<Brawl, u64>(storage, b"max_players")
    }

    public(package) fun set_max_players(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"max_players", value, ctx
        );
    }

    public(package) fun remove_max_players_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u64>(
            dapp_key::new(), storage, b"max_players"
        )
    }

    public fun get_state(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u8 {
        dubhe::dapp_system::get_scene_field<Brawl, u8>(storage, b"state")
    }

    public(package) fun set_state(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u8,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u8>(
            dapp_key::new(), permit, storage, user_storage, b"state", value, ctx
        );
    }

    public(package) fun remove_state_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u8 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u8>(
            dapp_key::new(), storage, b"state"
        )
    }

    public fun get_round(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u32 {
        dubhe::dapp_system::get_scene_field<Brawl, u32>(storage, b"round")
    }

    public(package) fun set_round(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u32,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u32>(
            dapp_key::new(), permit, storage, user_storage, b"round", value, ctx
        );
    }

    public(package) fun remove_round_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u32 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u32>(
            dapp_key::new(), storage, b"round"
        )
    }

    public fun get_turn_index(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::get_scene_field<Brawl, u64>(storage, b"turn_index")
    }

    public(package) fun set_turn_index(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"turn_index", value, ctx
        );
    }

    public(package) fun remove_turn_index_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u64>(
            dapp_key::new(), storage, b"turn_index"
        )
    }

    public fun get_players(storage: &dubhe::dapp_service::SceneStorage<Brawl>): vector<address> {
        dubhe::dapp_system::get_scene_field<Brawl, vector<address>>(storage, b"players")
    }

    public(package) fun set_players(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        vector<address>,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, vector<address>>(
            dapp_key::new(), permit, storage, user_storage, b"players", value, ctx
        );
    }

    public(package) fun remove_players_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): vector<address> {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, vector<address>>(
            dapp_key::new(), storage, b"players"
        )
    }

    public fun get_alive(storage: &dubhe::dapp_service::SceneStorage<Brawl>): vector<address> {
        dubhe::dapp_system::get_scene_field<Brawl, vector<address>>(storage, b"alive")
    }

    public(package) fun set_alive(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        vector<address>,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, vector<address>>(
            dapp_key::new(), permit, storage, user_storage, b"alive", value, ctx
        );
    }

    public(package) fun remove_alive_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): vector<address> {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, vector<address>>(
            dapp_key::new(), storage, b"alive"
        )
    }

    public fun get_winner(storage: &dubhe::dapp_service::SceneStorage<Brawl>): address {
        dubhe::dapp_system::get_scene_field<Brawl, address>(storage, b"winner")
    }

    public(package) fun set_winner(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, address>(
            dapp_key::new(), permit, storage, user_storage, b"winner", value, ctx
        );
    }

    public(package) fun remove_winner_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, address>(
            dapp_key::new(), storage, b"winner"
        )
    }

    public fun get_last_action_ms(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::get_scene_field<Brawl, u64>(storage, b"last_action_ms")
    }

    public(package) fun set_last_action_ms(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"last_action_ms", value, ctx
        );
    }

    public(package) fun remove_last_action_ms_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Brawl, u64>(
            dapp_key::new(), storage, b"last_action_ms"
        )
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::SceneStorage<Brawl>): u64 {
        if (dubhe::dapp_system::has_scene_field<Brawl, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_scene_field<Brawl, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(
        permit:  &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current + amount, ctx
        );
    }

    public(package) fun sub_gold(
        permit:  &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Brawl>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current - amount, ctx
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────


    // ─── SceneStorage lifecycle wrappers ──────────────────────────────────

    public(package) fun new_brawl_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        ctx:          &mut TxContext,
    ): dubhe::dapp_service::SceneStorage<Brawl> {
        dubhe::dapp_system::new_typed_scene_with_permit<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        )
    }

    public(package) fun create_brawl_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        ctx:          &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_permit<DappKey, card_duel::brawl_permit::BrawlPermit, Brawl>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        );
    }

    public(package) fun share_brawl(storage: dubhe::dapp_service::SceneStorage<Brawl>) {
        dubhe::dapp_system::share_scene_storage<DappKey, Brawl>(
            dapp_key::new(), storage
        );
    }

    public(package) fun destroy_brawl(storage: dubhe::dapp_service::SceneStorage<Brawl>) {
        dubhe::dapp_system::destroy_typed_scene<DappKey, Brawl>(
            dapp_key::new(), storage
        );
    }
}
