// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::duel {
    use dubhe::dapp_service::DappStorage;
    use card_duel::dapp_key;
    use card_duel::dapp_key::DappKey;

    // ─── Error constants ───────────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";

    const SCENE_TYPE: vector<u8> = b"duel";

    /// Phantom type that distinguishes this scene storage at compile time.
    public struct Duel has copy, drop {}

    // ─── Field accessors (own fields) ──────────────────────────────────────

    public fun get_challenger(storage: &dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::get_scene_field<Duel, address>(storage, b"challenger")
    }

    public(package) fun set_challenger(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, address>(
            dapp_key::new(), permit, storage, user_storage, b"challenger", value, ctx
        );
    }

    public(package) fun remove_challenger_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, address>(
            dapp_key::new(), storage, b"challenger"
        )
    }

    public fun get_opponent(storage: &dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::get_scene_field<Duel, address>(storage, b"opponent")
    }

    public(package) fun set_opponent(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, address>(
            dapp_key::new(), permit, storage, user_storage, b"opponent", value, ctx
        );
    }

    public(package) fun remove_opponent_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, address>(
            dapp_key::new(), storage, b"opponent"
        )
    }

    public fun get_stake(storage: &dubhe::dapp_service::SceneStorage<Duel>): u64 {
        dubhe::dapp_system::get_scene_field<Duel, u64>(storage, b"stake")
    }

    public(package) fun set_stake(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u64>(
            dapp_key::new(), permit, storage, user_storage, b"stake", value, ctx
        );
    }

    public(package) fun remove_stake_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, u64>(
            dapp_key::new(), storage, b"stake"
        )
    }

    public fun get_state(storage: &dubhe::dapp_service::SceneStorage<Duel>): u8 {
        dubhe::dapp_system::get_scene_field<Duel, u8>(storage, b"state")
    }

    public(package) fun set_state(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u8,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u8>(
            dapp_key::new(), permit, storage, user_storage, b"state", value, ctx
        );
    }

    public(package) fun remove_state_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): u8 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, u8>(
            dapp_key::new(), storage, b"state"
        )
    }

    public fun get_turn_addr(storage: &dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::get_scene_field<Duel, address>(storage, b"turn_addr")
    }

    public(package) fun set_turn_addr(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, address>(
            dapp_key::new(), permit, storage, user_storage, b"turn_addr", value, ctx
        );
    }

    public(package) fun remove_turn_addr_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, address>(
            dapp_key::new(), storage, b"turn_addr"
        )
    }

    public fun get_round(storage: &dubhe::dapp_service::SceneStorage<Duel>): u32 {
        dubhe::dapp_system::get_scene_field<Duel, u32>(storage, b"round")
    }

    public(package) fun set_round(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u32,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u32>(
            dapp_key::new(), permit, storage, user_storage, b"round", value, ctx
        );
    }

    public(package) fun remove_round_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): u32 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, u32>(
            dapp_key::new(), storage, b"round"
        )
    }

    public fun get_winner(storage: &dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::get_scene_field<Duel, address>(storage, b"winner")
    }

    public(package) fun set_winner(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        address,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, address>(
            dapp_key::new(), permit, storage, user_storage, b"winner", value, ctx
        );
    }

    public(package) fun remove_winner_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): address {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, address>(
            dapp_key::new(), storage, b"winner"
        )
    }

    public fun get_used_cards_a(storage: &dubhe::dapp_service::SceneStorage<Duel>): vector<address> {
        dubhe::dapp_system::get_scene_field<Duel, vector<address>>(storage, b"used_cards_a")
    }

    public(package) fun set_used_cards_a(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        vector<address>,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, vector<address>>(
            dapp_key::new(), permit, storage, user_storage, b"used_cards_a", value, ctx
        );
    }

    public(package) fun remove_used_cards_a_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): vector<address> {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, vector<address>>(
            dapp_key::new(), storage, b"used_cards_a"
        )
    }

    public fun get_used_cards_b(storage: &dubhe::dapp_service::SceneStorage<Duel>): vector<address> {
        dubhe::dapp_system::get_scene_field<Duel, vector<address>>(storage, b"used_cards_b")
    }

    public(package) fun set_used_cards_b(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        vector<address>,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, vector<address>>(
            dapp_key::new(), permit, storage, user_storage, b"used_cards_b", value, ctx
        );
    }

    public(package) fun remove_used_cards_b_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): vector<address> {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, vector<address>>(
            dapp_key::new(), storage, b"used_cards_b"
        )
    }

    public fun get_last_action_ms(storage: &dubhe::dapp_service::SceneStorage<Duel>): u64 {
        dubhe::dapp_system::get_scene_field<Duel, u64>(storage, b"last_action_ms")
    }

    public(package) fun set_last_action_ms(
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage:      &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        value:        u64,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u64>(
            dapp_key::new(), permit, storage, user_storage, b"last_action_ms", value, ctx
        );
    }

    public(package) fun remove_last_action_ms_system_maintenance(storage: &mut dubhe::dapp_service::SceneStorage<Duel>): u64 {
        dubhe::dapp_system::remove_scene_field_system_maintenance<DappKey, Duel, u64>(
            dapp_key::new(), storage, b"last_action_ms"
        )
    }

    // ─── Bag accessors for accepted resources ─────────────────────────────

    public fun get_gold(storage: &dubhe::dapp_service::SceneStorage<Duel>): u64 {
        if (dubhe::dapp_system::has_scene_field<Duel, u64>(storage, b"gold")) {
            dubhe::dapp_system::get_scene_field<Duel, u64>(storage, b"gold")
        } else { 0 }
    }

    public(package) fun add_gold(
        permit:  &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current + amount, ctx
        );
    }

    public(package) fun sub_gold(
        permit:  &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        storage: &mut dubhe::dapp_service::SceneStorage<Duel>,
        user_storage: &dubhe::dapp_service::UserStorage,
        amount:  u64,
        ctx:     &TxContext,
    ) {
        let current = get_gold(storage);
        assert!(current >= amount, EInsufficientAmount);
        dubhe::dapp_system::set_scene_field<DappKey, card_duel::duel_permit::DuelPermit, Duel, u64>(
            dapp_key::new(), permit, storage, user_storage, b"gold", current - amount, ctx
        );
    }

    // ─── acceptsFrom: cross-storage transfer functions ─────────────────────


    // ─── SceneStorage lifecycle wrappers ──────────────────────────────────

    public(package) fun new_duel_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        ctx:          &mut TxContext,
    ): dubhe::dapp_service::SceneStorage<Duel> {
        dubhe::dapp_system::new_typed_scene_with_permit<DappKey, card_duel::duel_permit::DuelPermit, Duel>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        )
    }

    public(package) fun create_duel_with_permit(
        dapp_storage: &DappStorage,
        permit:       &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        ctx:          &mut TxContext,
    ) {
        dubhe::dapp_system::create_and_share_typed_scene_with_permit<DappKey, card_duel::duel_permit::DuelPermit, Duel>(
            dapp_key::new(), dapp_storage, permit, SCENE_TYPE, ctx
        );
    }

    public(package) fun share_duel(storage: dubhe::dapp_service::SceneStorage<Duel>) {
        dubhe::dapp_system::share_scene_storage<DappKey, Duel>(
            dapp_key::new(), storage
        );
    }

    public(package) fun destroy_duel(storage: dubhe::dapp_service::SceneStorage<Duel>) {
        dubhe::dapp_system::destroy_typed_scene<DappKey, Duel>(
            dapp_key::new(), storage
        );
    }
}
