[package]
name = "sov-prover-incentives"
description = "A Sovereign SDK module for incentivizing provers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
sov-prover-incentives = { path = ".", features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-mock-zkvm = { workspace = true, features = ["native"] }
sov-modules-api = { workspace = true, features = ["native", "test-utils"] }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }
sov-test-utils = { workspace = true }

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }

sov-bank = { workspace = true }
sov-modules-api = { workspace = true }
sov-state = { workspace = true }
sov-chain-state = { workspace = true }

[features]
default = []
native = [
    "jsonrpsee",
    "schemars",
    "sov-bank/native",
    "sov-chain-state/native",
    "sov-mock-da/native",
    "sov-mock-zkvm/native",
    "sov-modules-api/native",
    "sov-prover-incentives/native",
    "sov-state/native",
]
