[package]
name = "sov-eth-dev-signer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"
publish = false

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
revm = { workspace = true, features = [
    "std",
    "secp256k1",
] }
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
secp256k1 = { workspace = true }
