[package]
name = "sov-capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }

sov-rollup-interface = { workspace = true }
sov-modules-api = { workspace = true }
sov-bank = { workspace = true }
sov-accounts = { workspace = true }
sov-nonces = { workspace = true }
sov-sequencer-registry = { workspace = true }
sov-prover-incentives = { workspace = true }

[lints]
workspace = true

[features]
default = []
native = [
    "sov-accounts/native",
    "sov-bank/native",
    "sov-modules-api/native",
    "sov-nonces/native",
    "sov-prover-incentives/native",
    "sov-sequencer-registry/native",
    "sov-rollup-interface/native",
]
