[package]
name = "sov-stf-runner"
authors = { workspace = true }
description = "Runs Sovereign SDK rollups and their verifiers"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["tokio", "http1", "http2"], optional = true }
derivative = { workspace = true, optional = true }
backon = { workspace = true, optional = true }
num_cpus = { workspace = true }
thiserror = { workspace = true, optional = true }
borsh = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
strum = { version = "0.26", features = ["derive"], optional = true }
toml = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"], optional = true }
tokio = { workspace = true, optional = true, features = ["net", "sync", "rt-multi-thread", "time"] }
hex = { workspace = true }
tracing = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
sov-db = { workspace = true, optional = true }
sov-rollup-interface = { workspace = true }
sov-metrics = { workspace = true }

[dev-dependencies]
backon = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }

sov-sequencer-registry = { workspace = true, features = ["native"] }
sov-bank = { workspace = true, features = ["native"] }
sov-modules-stf-blueprint = { workspace = true, features = ["native"] }

sov-accounts = { workspace = true, features = ["native"] }
sov-celestia-adapter = { workspace = true, features = ["native"] }
sov-sequencer = { workspace = true }

sov-state = { workspace = true, features = ["native"] }
sov-modules-api = { workspace = true, features = ["native"] }
sov-stf-runner = { workspace = true, features = ["mock"] }

sov-mock-da = { workspace = true, features = ["native"] }
sov-mock-zkvm = { workspace = true, features = ["native"] }
sov-prover-storage-manager = { workspace = true, features = ["test-utils"] }

tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tokio = { workspace = true, features = ["test-util", "macros"] }

[features]
default = []
mock = ["native"]
native = [
    "async-trait",
    "axum",
    "derivative",
    "backon",
    "futures",
    "jsonrpsee",
    "rayon",
    "sov-accounts/native",
    "sov-bank/native",
    "sov-celestia-adapter/native",
    "sov-db",
    "sov-mock-da/native",
    "sov-mock-zkvm/native",
    "sov-modules-api/native",
    "sov-modules-stf-blueprint/native",
    "sov-rollup-interface/native",
    "sov-sequencer-registry/native",
    "sov-state/native",
    "sov-stf-runner/native",
    "strum",
    "thiserror",
    "tokio",
    "toml",
    "tracing",
    "sov-metrics/native"
]