[package]
published-at = "0xfd69a55cd72e9ae2e38809dd085774d3e00132fd28c6916857df0dc7cbce7e7a"
name = "Dubhe"
edition = "2024"
version = "1.0.0"
license = "apache2.0"
authors = ["Obelisk Labs"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.46.3" }

[addresses]
dubhe = "0xfd69a55cd72e9ae2e38809dd085774d3e00132fd28c6916857df0dc7cbce7e7a"

[environments]
testnet = "4c78adac"
mainnet = "35834a8a"

