// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module card_duel::gold {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::{UserStorage, DappStorage};
    use dubhe::dapp_system;
    use card_duel::dapp_key;
    use card_duel::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"gold";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"amount"], ctx);
    }

    public fun get(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let amount_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"amount");
        let mut amount_bcs = sui::bcs::new(amount_raw);
        let value = sui::bcs::peel_u64(&mut amount_bcs);
        value
    }

    public(package) fun set(user_storage: &mut UserStorage, value: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"amount"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }


    // ─── fungible add / sub ─────────────────────────────────────────────
    #[error]
    const EInsufficientAmount: vector<u8> = b"Insufficient amount";

    public(package) fun add(user_storage: &mut UserStorage, amount: u64, ctx: &mut TxContext) {
        let current = if (has(user_storage)) { get(user_storage) } else { 0 };
        set(user_storage, current + amount, ctx);
    }

    public(package) fun sub(user_storage: &mut UserStorage, amount: u64, ctx: &mut TxContext) {
        let current = get(user_storage);
        assert!(current >= amount, EInsufficientAmount);
        set(user_storage, current - amount, ctx);
    }

    // ─── transferable: User ↔ ArenaStorage (fungible) ─────────────
    public(package) fun transfer_user_to_arena(
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::ObjectStorage<card_duel::arena::Arena>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        card_duel::arena::add_gold(target, amount);
    }

    public(package) fun transfer_arena_to_user(
        source: &mut dubhe::dapp_service::ObjectStorage<card_duel::arena::Arena>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        card_duel::arena::sub_gold(source, amount);
        add(user, amount, ctx);
    }

    // ─── transferable: User ↔ DuelStorage (fungible) ──────────
    public(package) fun transfer_user_to_duel(
        permit: &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::SceneStorage<card_duel::duel::Duel>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        card_duel::duel::add_gold(permit, target, user, amount, ctx);
    }

    // ★ No expiry check on withdraw direction — prevents asset lock-in expired scenes.
    public(package) fun transfer_duel_to_user(
        permit: &dubhe::dapp_service::ScenePermit<card_duel::duel_permit::DuelPermit>,
        source: &mut dubhe::dapp_service::SceneStorage<card_duel::duel::Duel>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        card_duel::duel::sub_gold(permit, source, user, amount, ctx);
        add(user, amount, ctx);
    }

    // ─── transferable: User ↔ BrawlStorage (fungible) ──────────
    public(package) fun transfer_user_to_brawl(
        permit: &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        user:   &mut UserStorage,
        target: &mut dubhe::dapp_service::SceneStorage<card_duel::brawl::Brawl>,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        sub(user, amount, ctx);
        card_duel::brawl::add_gold(permit, target, user, amount, ctx);
    }

    // ★ No expiry check on withdraw direction — prevents asset lock-in expired scenes.
    public(package) fun transfer_brawl_to_user(
        permit: &dubhe::dapp_service::ScenePermit<card_duel::brawl_permit::BrawlPermit>,
        source: &mut dubhe::dapp_service::SceneStorage<card_duel::brawl::Brawl>,
        user:   &mut UserStorage,
        amount: u64,
        ctx:    &mut TxContext,
    ) {
        card_duel::brawl::sub_gold(permit, source, user, amount, ctx);
        add(user, amount, ctx);
    }

    // ─── listable: market protocol (fungible) ──────────────────────────
    // Package-level helpers: call these from your system functions.
    // Add pause checks, access control, and custom logic there.
    public(package) fun list<CoinType>(
        user_storage: &mut UserStorage,
        amount:       u64,
        price:        u64,
        listed_until: std::option::Option<u64>,
        ctx:          &mut TxContext,
    ) {
        dubhe::dapp_system::take_fungible_record<DappKey, CoinType>(
            dapp_key::new(),
            user_storage,
            b"gold",
            { let mut k = vector::empty(); k.push_back(TABLE_NAME); k },
            b"amount",
            amount,
            price,
            listed_until,
            ctx,
        );
    }

    public(package) fun buy<CoinType>(
        dh:            &dubhe::dapp_service::DappHub,
        dapp_storage:  &mut DappStorage,
        listing:       dubhe::dapp_service::Listing<CoinType>,
        user_storage:  &mut UserStorage,
        payment:       sui::coin::Coin<CoinType>,
        ctx:           &mut TxContext,
    ): sui::coin::Coin<CoinType> {
        dubhe::dapp_system::buy_fungible_record<DappKey, CoinType>(
            dapp_key::new(), dh, dapp_storage, listing, user_storage, payment, ctx
        )
    }

    public(package) fun cancel_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::cancel_fungible_listing<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public(package) fun expire_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::expire_fungible_listing<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }
}